# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## OS.Linux.get_local_users test
## Auto-generated by ./noc debug-script at 2011-11-02 19:30:56
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class OS_Linux_get_local_users_Test(ScriptTestCase):
    script = "OS.Linux.get_local_users"
    vendor = "OS"
    platform = 'NanoStation2'
    version = '3.6.1.4866.110330.1244'
    input = {}
    result = [{'class': 'superuser', 'is_active': True, 'username': 'ubnt'},
 {'class': 'superuser', 'is_active': True, 'username': 'mcuser'}]
    motd = "\n\nBusyBox v1.01 (2011.03.30-09:47+0000) Built-in shell (ash)\nEnter 'help' for a list of built-in commands.\n\n"
    cli = {
'export LANG=en_GB.UTF-8':  'export LANG=en_GB.UTF-8\n', 
'cat /etc/passwd':  'cat /etc/passwd\nubnt:VvpvCwhccFv6Q:0:0:Administrator:/etc/persistent:/bin/sh\nmcuser:!VvDE8C2EB1:0:0::/etc/persistent/mcuser:/bin/sh\n', 
}
    snmp_get = {}
    snmp_getnext = {}
