# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Eltex.MES.add_vlan test
## Auto-generated by ./noc debug-script at 2011-10-21 16:43:59
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Eltex_MES_add_vlan_Test(ScriptTestCase):
    script = "Eltex.MES.add_vlan"
    vendor = "Eltex"
    platform = 'MES3124F'
    version = '2.1.7'
    input = {'name': 'test', 'tagged_ports': ['te0/3', 'te0/4'], 'vlan_id': 777}
    result = True
    motd = '*****\n\n'
    cli = {
'':  '\n', 
'end':  'end\n', 
'configure':  'configure\n', 
## 'show vlan'
'show vlan': """show vlan

Vlan       Name                   Ports                Type     Authorization 
---- ----------------- --------------------------- ------------ ------------- 
 1           1              gi0/1-24,te0/1-4         Default      Required    
 53  area_Lermontova8       gi0/1-24,te0/1-4        permanent     Required    
111     commutators         gi0/1-24,te0/1-4        permanent     Required    
777        test                 gi0/15-16           permanent     Required    
""", 
'switchport trunk allowed vlan add  777':  'switchport trunk allowed vlan add  777\n', 
'interface range te0/3,te0/4':  'interface range te0/3,te0/4\n', 
'terminal datadump':  'terminal datadump\n', 
}
    snmp_get = {}
    snmp_getnext = {}
