# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Eltex.MES.ping test
## Auto-generated by ./noc debug-script at 2011-10-31 16:54:04
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Eltex_MES_ping_Test(ScriptTestCase):
    script = "Eltex.MES.ping"
    vendor = "Eltex"
    platform = 'MES-3124F'
    version = '2.1.7'
    input = {'address': '10.8.4.9'}
    result = {'count': 4, 'success': 0}
    motd = '*****\n\n'
    cli = {
'terminal datadump':  'terminal datadump\n', 
## 'ping ip 10.8.4.9'
'ping ip 10.8.4.9': """ping ip 10.8.4.9
Pinging 10.8.4.9 with 18 bytes of data:

PING: no reply from 10.8.4.9
PING: timeout
PING: no reply from 10.8.4.9
PING: timeout
PING: no reply from 10.8.4.9
PING: timeout
PING: no reply from 10.8.4.9
PING: timeout

----10.8.4.9 PING Statistics----
4 packets transmitted, 0 packets received, 100% packet loss
""", 
}
    snmp_get = {}
    snmp_getnext = {}
