# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Eltex.MES.get_interface_status test
## Auto-generated by ./noc debug-script at 2011-10-31 16:52:32
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Eltex_MES_get_interface_status_Test(ScriptTestCase):
    script = "Eltex.MES.get_interface_status"
    vendor = "Eltex"
    platform = 'MES-3124F'
    version = '2.1.7'
    input = {}
    result = [{'interface': 'gi0/1', 'status': True},
 {'interface': 'gi0/2', 'status': True},
 {'interface': 'gi0/3', 'status': True},
 {'interface': 'gi0/4', 'status': False},
 {'interface': 'gi0/5', 'status': False},
 {'interface': 'gi0/6', 'status': False},
 {'interface': 'gi0/7', 'status': False},
 {'interface': 'gi0/8', 'status': False},
 {'interface': 'gi0/9', 'status': False},
 {'interface': 'gi0/10', 'status': False},
 {'interface': 'gi0/11', 'status': False},
 {'interface': 'gi0/12', 'status': False},
 {'interface': 'gi0/13', 'status': False},
 {'interface': 'gi0/14', 'status': False},
 {'interface': 'gi0/15', 'status': False},
 {'interface': 'gi0/16', 'status': False},
 {'interface': 'gi0/17', 'status': False},
 {'interface': 'gi0/18', 'status': False},
 {'interface': 'gi0/19', 'status': False},
 {'interface': 'gi0/20', 'status': False},
 {'interface': 'gi0/21', 'status': False},
 {'interface': 'gi0/22', 'status': False},
 {'interface': 'gi0/23', 'status': False},
 {'interface': 'gi0/24', 'status': False},
 {'interface': 'te0/1', 'status': True},
 {'interface': 'te0/2', 'status': False},
 {'interface': 'te0/3', 'status': False},
 {'interface': 'te0/4', 'status': False}]
    motd = '*****\n\n'
    cli = {
'terminal datadump':  'terminal datadump\n', 
## 'show interfaces status'
'show interfaces status': """show interfaces status
                                             Flow Link          Back   Mdix
Port     Type         Duplex  Speed Neg      ctrl State       Pressure Mode
-------- ------------ ------  ----- -------- ---- ----------- -------- -------
gi0/1    1G-Fiber     Full    1000  Disabled Off  Up          Disabled Off    
gi0/2    1G-Fiber     Full    1000  Disabled Off  Up          Disabled Off    
gi0/3    1G-Fiber     Full    1000  Disabled Off  Up          Disabled Off    
gi0/4    1G-Fiber       --      --     --     --  Down           --     --    
gi0/5    1G-Fiber       --      --     --     --  Down           --     --    
gi0/6    1G-Fiber       --      --     --     --  Down           --     --    
gi0/7    1G-Fiber       --      --     --     --  Down           --     --    
gi0/8    1G-Fiber       --      --     --     --  Down           --     --    
gi0/9    1G-Fiber       --      --     --     --  Down           --     --    
gi0/10   1G-Fiber       --      --     --     --  Down           --     --    
gi0/11   1G-Combo-C     --      --     --     --  Down           --     --    
gi0/12   1G-Combo-C     --      --     --     --  Down           --     --    
gi0/13   1G-Fiber       --      --     --     --  Down           --     --    
gi0/14   1G-Fiber       --      --     --     --  Down           --     --    
gi0/15   1G-Fiber       --      --     --     --  Down           --     --    
gi0/16   1G-Fiber       --      --     --     --  Down           --     --    
gi0/17   1G-Fiber       --      --     --     --  Down           --     --    
gi0/18   1G-Fiber       --      --     --     --  Down           --     --    
gi0/19   1G-Fiber       --      --     --     --  Down           --     --    
gi0/20   1G-Fiber       --      --     --     --  Down           --     --    
gi0/21   1G-Fiber       --      --     --     --  Down           --     --    
gi0/22   1G-Fiber       --      --     --     --  Down           --     --    
gi0/23   1G-Combo-C     --      --     --     --  Down           --     --    
gi0/24   1G-Combo-C     --      --     --     --  Down           --     --    
te0/1    1G-Fiber     Full    1000  Disabled Off  Up          Disabled Off    
te0/2    10G-Fiber      --      --     --     --  Down           --     --    
te0/3    10G-Fiber      --      --     --     --  Down           --     --    
te0/4    10G-Fiber      --      --     --     --  Down           --     --    

                                          Flow    Link        
Ch       Type    Duplex  Speed  Neg      control  State       
-------- ------- ------  -----  -------- -------  ----------- 
Po1         --     --      --      --       --    Not Present 
Po2         --     --      --      --       --    Not Present 
Po3         --     --      --      --       --    Not Present 
Po4         --     --      --      --       --    Not Present 
Po5         --     --      --      --       --    Not Present 
Po6         --     --      --      --       --    Not Present 
Po7         --     --      --      --       --    Not Present 
Po8         --     --      --      --       --    Not Present """, 
}
    snmp_get = {}
    snmp_getnext = {}
