# ----------------------------------------------------------------------
# Create initial protocols for migration purposes
# ----------------------------------------------------------------------
# Copyright (C) 2007-2023 The NOC Project
# See LICENSE for details
# ----------------------------------------------------------------------

# Python modules
from uuid import UUID
import base64

# Third-party modules
from bson.objectid import ObjectId
from bson.int64 import Int64
from pymongo import UpdateOne

# NOC modules
from noc.core.migration.base import BaseMigration


class Migration(BaseMigration):
    depends_on = [("inv", "0017_initial_technologies")]
    protocols = [
        {
            "name": "2.5GBASE-T",
            "code": "2.5GBASET",
            "description": "2.5GBASE-T, 2.5Gbit/s",
            "uuid": "C8SKaLs4RSG2IFnG8eD2aw==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 6927626307504239558,
        },
        {
            "name": "5GBASE-T",
            "code": "5GBASET",
            "description": "5GBASE-T, 5Gbit/s",
            "uuid": "gpl2gt5jQjOP/kRTBgoXOA==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 9050177851948862195,
        },
        {
            "name": "10GBASECX4",
            "code": "10GBASECX4",
            "description": "10GBASE-CX4, 10GBit/s, copper",
            "uuid": "IM1k7u3uRquHjVm01GUZ9A==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 1199237845749904882,
        },
        {
            "name": "10GBASE-T",
            "code": "10GBASET",
            "description": "10GBASE-T, 10GBit/s, copper",
            "uuid": "vbABynodRwm0+QNpIipo1Q==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 2452661867444268482,
        },
        {
            "name": "G.703",
            "code": "G703",
            "uuid": "8NenuqphS2GKHAIRv9Zo1w==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 8606721829582200464,
        },
        {
            "name": "100BASE-FX",
            "code": "100BASEFX",
            "uuid": "Ji8szJYcTTaKhhWE5RUjIQ==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminator_source": "protocol",
            "discriminators": [
                {
                    "code": "1310",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1310}],
                },
                {
                    "code": "1490",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1490}],
                },
                {
                    "code": "1550",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1550}],
                },
            ],
            "bi_id": 1710675769716251419,
            "description": "100BASE-FX is a version of Fast Ethernet over optical fiber. 100BASE-FX is still used for existing installation of multimode fiber where more speed is not required, like industrial automation plants.",
        },
        {
            "name": "100BASE-LX10",
            "code": "100BASELX10",
            "uuid": "zXaiNT8kS0ycFATxR8/5ew==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminator_source": "protocol",
            "discriminators": [
                {
                    "code": "1310",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1310}],
                },
                {
                    "code": "1490",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1490}],
                },
                {
                    "code": "1550",
                    "data": [{"interface": "optical", "attr": "tx_wavelength", "value": 1550}],
                },
            ],
            "bi_id": 8117216786517600207,
            "description": "100BASE-LX10 is a version of Fast Ethernet over optical fiber standardized in 802.3ah-2004 clause 58. It has a 10 km reach over a pair of single-mode fibers.",
        },
        {
            "name": "1000BASE-SX",
            "code": "1000BASESX",
            "uuid": "jz2GzzpRSFuc2qQD4dl16A==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 1229578176699207409,
            "description": "1000BASE-SX is an optical fiber Gigabit Ethernet standard for operation over multi-mode fiber using a 770 to 860 nanometer, near infrared (NIR) light wavelength.",
        },
        {
            "name": "1000BASE-LX",
            "code": "1000BASELX",
            "description": "1000BASE-LX is an optical fiber Gigabit Ethernet standard specified in IEEE 802.3 Clause 38 which uses a long wavelength laser (1,270–1,355 nm), and a maximum RMS spectral width of 4 nm.",
            "uuid": "GyepL7VoTyy2jPMHvbCdKw==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 3024007961580521791,
        },
        {
            "name": "1000BASE-EX",
            "code": "1000BASEEX",
            "description": "1000BASE-EX is a non-standard but industry accepted term[31] to refer to Gigabit Ethernet transmission. It is very similar to 1000BASE-LX10 but achieves longer distances up to 40 km over a pair of single-mode fibers due to higher quality optics than a LX10, running on 1310 nm wavelength lasers.",
            "uuid": "nyy72ofRQD6/UAgC3MV3Iw==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 4903366298845197128,
        },
        {
            "name": "1000BASE-ZX",
            "code": "1000BASEZX",
            "description": "1000BASE-ZX is a non-standard but multi-vendor[32] term to refer to Gigabit Ethernet transmission using 1,550 nm wavelength to achieve distances of at least 70 kilometres (43 miles) over single-mode fiber.",
            "uuid": "C7pbIST7Ra+VnHrcpdqiwg==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 3529477277638934517,
        },
        {
            "name": "1000BASE‑CWDM",
            "code": "1000BASECWDM",
            "description": "1000BASE-CWDM is a non-standard but industry accepted term[23][24] to refer to Gigabit Ethernet transmission. It is very similar to 1000BASE-LX10 but achieves longer distances up 40–120 km, and up to 18 parallel channels over a pair of single-mode fibers due to higher quality optics than LX10 and use of CWDM, running on 1270-1610 nm wavelength lasers.",
            "uuid": "26VETl9SRWizG5cWJdyxkg==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 2890811726276050308,
        },
        {
            "name": "10GBASE-SR",
            "code": "10GBASESR",
            "description": '10GBASE-SR ("short range") is a port type for multi-mode fiber and uses 850 nm lasers.[28] Its Physical Coding Sublayer (PCS) is 64b/66b and is defined in IEEE 802.3 Clause 49 and its Physical Medium Dependent (PMD) sublayer in Clause 52.',
            "uuid": "a7GEa9noTR6+wj6GBMgzfQ==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 4122434868207201221,
        },
        {
            "name": "CWDM",
            "code": "CWDM",
            "uuid": "xTk4bQlzROq6gwoRRzOwWA==",
            "technology": ObjectId("65335aeac0fe77cd7156a8eb"),
            "data": [],
            "connection_schema": "BD",
            "discriminator_source": "optical_cwdm",
            "discriminators": [],
            "bi_id": 7744549627978701209,
        },
        {
            "name": "10GBASE-LR",
            "code": "10GBASELR",
            "description": "10GBASE-LR (long reach) is a port type for single-mode fiber and uses 1310 nm lasers. Its 64b/66b PCS is defined in IEEE 802.3 Clause 49 and its PMD sublayer in Clause 52. It delivers serialized data at a line rate of 10.3125 GBd",
            "uuid": "AVrJGSABRLKSWpth2Gj4Tg==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 8922380252874840570,
        },
        {
            "name": "10GBASE-ER",
            "code": "10GBASEER",
            "description": "10GBASE-ER (extended reach) is a port type for single-mode fiber and uses 1550 nm lasers. Its 64b/66b PCS is defined in IEEE 802.3 Clause 49 and its PMD sublayer in Clause 52. It delivers serialized data at a line rate of 10.3125 GBd",
            "uuid": "rf2L4G3wR8+3MydVxOeijQ==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 8740287283368274726,
        },
        {
            "name": "10GBASE-ZR",
            "code": "10GBASEZR",
            "description": "Several manufacturers have introduced 80 km (50 mi) range under the name 10GBASE-ZR. This 80 km PHY is not specified within the IEEE 802.3ae standard and manufacturers have created their own specifications based upon the 80 km PHY described in the OC-192/STM-64 SDH/SONET specifications",
            "uuid": "2VrQZX1PQB6sSun3PIX02Q==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 2808188311729498239,
        },
        {
            "name": "USB 2.0",
            "code": "USB20",
            "description": "USB 1.1",
            "uuid": "s8i1u7yDRzimvHlPdpYLMQ==",
            "technology": ObjectId("65327510bf6b74584155a94f"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 6578796252121372417,
        },
        {
            "name": "TransEth25G",
            "code": "TransEth25G",
            "description": "Interface for device transievers module",
            "uuid": "MNFMIavOQ8qBndZxa15zvQ==",
            "technology": ObjectId("653277c66aad5b611082bf5e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 2413686549206602007,
        },
        {
            "name": "V.92",
            "code": "V92",
            "description": "V.92 is an ITU-T recommendation, titled Enhancements to Recommendation V.90, that establishes a modem standard allowing near 56 kb/s download and 48 kb/s upload rates",
            "uuid": "A8ujO1LmRwWGcp9zxnOTCw==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 7554449735462717598,
        },
        {
            "name": "V.42bis",
            "code": "V42bis",
            "description": 'V.42bis, also an adaptive data compression standard, is based on the Lempel Ziv dynamic dictionary approach, and may go to "transparent mode," in which data is transmitted uncompressed.',
            "uuid": "OML3SyPzTCuqFnES8sTUFw==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 8224464043106425691,
        },
        {
            "name": "V.44",
            "code": "V44",
            "description": "V.44 is based on LZJH (Lempel-Ziv-Jeff-Heath) adaptive data compression developed by Hughes Electronics for its DirecPC satellite Internet, and incorporated into the v.92 dial-up modem standard.",
            "uuid": "yi73/xX0RoWqebVcpKCo1A==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 3658986147881680941,
        },
        {
            "name": "V.34",
            "code": "V34",
            "description": "V.34 (09/94) is an ITU-T recommendation (superseded) for a modem, allowing up to 28.8 kbit/s bidirectional data transfer using TCM modulation. Other additional defined data transfer rates are 24.0 kbit/s and 19.2 kbit/s as well as all the permitted V.32 and V.32bis rates",
            "uuid": "BFRlVl9jTDuYP8vJX4kozw==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 2002259140332145180,
        },
        {
            "name": "V.90",
            "code": "V90",
            "description": "V.90 is an ITU-T recommendation for a modem, allowing 56 kbit/s digital download and 33.6 kbit/s analog upload. It replaced two vendor standards (K56flex and X2) and was designed to allow modems from both prior standards to be flash upgraded to support it.",
            "uuid": "yAbQnfnoSDKJL+WKNMYKCg==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 1398881885846001206,
        },
        {
            "name": "V.35",
            "code": "V35",
            "description": "V.35 is an ITU-T standard located on layer 1 on the OSI model. Max speed is 2 Mbit/s and synchronous only. Withdrawn ITU-T recommendation for 48 kbit/s data transmission over wideband circuits.",
            "uuid": "N3zRm8IkQsyb0mAHvmpshQ==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 4257820208497742914,
        },
        {
            "name": "EPON",
            "code": "EPON",
            "uuid": "x8RMqsv2Q5u6jYhtpKUhGg==",
            "technology": ObjectId("65327760bf6b74584155a953"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 3398853177351457448,
        },
        {
            "name": "ADSL",
            "code": "ADSL",
            "description": "Asymmetric digital subscriber line (ADSL) is a type of digital subscriber line (DSL) technology, a data communications technology that enables faster data transmission over copper telephone lines than a conventional voiceband modem can provide.",
            "uuid": "FPp/V+hnRKyyaJo0jAZQ2g==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 5556246714174382660,
        },
        {
            "name": "SHDSL",
            "code": "SHDSL",
            "description": "Single-pair high-speed digital subscriber line (SHDSL) is a form of symmetric digital subscriber line (SDSL), a data communications technology for equal transmit and receive (i.e. symmetric) data rate over copper telephone lines, faster than a conventional voiceband modem can provide",
            "uuid": "mnI+UZs2SVeMf6mAqXDxzg==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 5959593571718780749,
        },
        {
            "name": "ADSL2",
            "code": "ADSL2",
            "description": "ITU G.992.3 is an ITU (International Telecommunication Union) standard, also referred to as ADSL2 or G.dmt.bis. It optionally extends the capability of basic ADSL in data rates to 12 Mbit/s downstream and, depending on Annex version, up to 3.5 Mbit/s upstream (with a mandatory capability of ADSL2 transceivers of 8 Mbit/s downstream and 800 kbit/s upstream).[1] ADSL2 uses the same bandwidth as ADSL but achieves higher throughput via improved modulation techniques",
            "uuid": "LIBD4JYoQleQbvgdsA3/aw==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 8230497091480883416,
        },
        {
            "name": "FXS",
            "code": "FXS",
            "description": "The foreign exchange station (FXS) interface is located at the wire center of the subscriber equipment, supplying battery power and dial tone, and generating ringing voltage toward the subscriber station of the foreign exchange service. ",
            "uuid": "lfYXjOPxSBWMpkDqnH5t+Q==",
            "technology": ObjectId("653376058989dc8dd4489152"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 7716693445543174968,
        },
        {
            "name": "FXO",
            "code": "FXO",
            "description": "The foreign exchange office (FXO) interface is a telephone signaling interface that terminates the foreign exchange line at the central office that provides the telephone number and the call switching for the service. It generates the off-hook and on-hook indications through loop closure and non-closure of a direct current (DC) circuit powered by the serving central office switch.",
            "uuid": "9BdAiQyfSsy3zFrhO5iTYQ==",
            "technology": ObjectId("653376058989dc8dd4489152"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 311773846711355176,
        },
        {
            "name": "ADSL2+",
            "code": "ADSL2+",
            "description": "G.992.5 (also referred to as ADSL2+, G.dmt.bis+, and G.adslplus)[1] is an ITU-T standard for asymmetric digital subscriber line (ADSL) broadband Internet access. The standard has a maximum theoretical downstream sync speed of 24 megabits per second (Mbit/s). Utilizing G.992.5 Annex M upstream sync speeds of 3.3 Mbit/s can be achieved.",
            "uuid": "9M0rhebIT/q+s+SpzLURCA==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 7637212110588578783,
        },
        {
            "name": "Cisco HWIC",
            "code": "CISCOHWIC",
            "description": "Cisco High Speed WAN Interface Card.",
            "uuid": "+eia4rqIQVa+4KoY3qgHhg==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 8857803808872137407,
        },
        {
            "name": "Cisco WIC",
            "code": "CISCOWIC",
            "description": "Cisco WAN Interface Card.",
            "uuid": "9HsGquSuRtaxX4NdVNZ0Ew==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 448100531483846228,
        },
        {
            "name": "Cisco VWIC",
            "code": "CISCOVWIC",
            "description": "Cisco Voice/WAN Interface Card.",
            "uuid": "4qhDej76T9u23Nqiemhm8w==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 1899484467890967915,
        },
        {
            "name": "Cisco VWIC3",
            "code": "CISCOVWIC3",
            "description": "Cisco Voice/WAN Interface Card. version 3",
            "uuid": "9/cIOcmmRCGSia2CYuDIjA==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 3390633164335875857,
        },
        {
            "name": "Cisco EHWIC",
            "code": "CISCOEHWIC",
            "description": "Enhanced High-Speed WAN Interface Card",
            "uuid": "zSIhA/WNSeugWXBMyPulmw==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 6343241022323138930,
        },
        {
            "name": "Cisco VIC",
            "code": "CISCOVIC",
            "description": "Cisco Voice Interface Card",
            "uuid": "XVgSCHEGTM6muOVH9arQlQ==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 719288899200590191,
        },
        {
            "name": "VDSL2",
            "code": "VDSL2",
            "description": "VDSL2 is an enhancement to VDSL designed to support the wide deployment of triple play services such as voice, video, data and high-definition television (HDTV) VDSL2 is intended to enable operators and carriers to gradually, flexibly, and cost-efficiently upgrade existing xDSL infrastructure",
            "uuid": "f9sGuYu2SIeWK8vF79UkaQ==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 1203118152031643259,
        },
        {
            "name": "VDSL",
            "code": "VDSL",
            "description": "Very high-speed digital subscriber line (VDSL)[1] and very high-speed digital subscriber line 2 (VDSL2)[2] are digital subscriber line (DSL) technologies providing data transmission faster than the earlier standards of asymmetric digital subscriber line (ADSL) G.992.1, G.992.3 (ADSL2) and G.992.5 (ADSL2+)",
            "uuid": "L5ywSSdxQuqTtXmzgQpz1Q==",
            "technology": ObjectId("653375108989dc8dd448914c"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 7611684915758525218,
        },
        {
            "name": "EIA-530",
            "code": "EIA530",
            "description": "Currently known as TIA-530-A, but often called EIA-530, or RS-530, is a balanced serial interface standard that generally uses a 25-pin connector, originally created by the Telecommunications Industry Association.",
            "uuid": "6dkpUa4XQEuZgR8P/I7zBA==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 8995918324847197074,
        },
        {
            "name": "RS-449",
            "code": "RS449",
            "description": "The RS-449 specification, also known as EIA-449 or TIA-449, defines the functional and mechanical characteristics of the interface between data terminal equipment, typically a computer, and data communications equipment, typically a modem or terminal server. The full title of the standard is EIA-449 General Purpose 37-Position and 9-Position Interface for Data Terminal Equipment and Data Circuit-Terminating Equipment Employing Serial Binary Data Interchange.",
            "uuid": "L8H+QwtNRoyYjZ0/NZxmkQ==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 8873268898073853186,
        },
        {
            "name": "PSTN",
            "code": "PSTN",
            "description": "Generic PSTN protocol.",
            "uuid": "UMyI6n7NQ9eRCDTTjXS9Bg==",
            "technology": ObjectId("653376058989dc8dd4489152"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 1131795986490303147,
        },
        {
            "name": "Dry contact",
            "code": "DryContact",
            "description": 'A dry contact is the synonym of volt free — it is not "wetted" by a voltage source. Dry contact can refer to a secondary set of contacts of a relay circuit which does not make or break the primary current being controlled by the relay.',
            "uuid": "ZdjCxo0nRz2E2mYlChtVaA==",
            "technology": ObjectId("6532734d6aad5b611082bf55"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 6460272635171306747,
        },
        {
            "name": "T1",
            "code": "T1",
            "description": "The first version, the Transmission System 1 (T1), was introduced in 1962 in the Bell System, and could transmit up to 24 telephone calls simultaneously over a single transmission line of copper wire. Subsequent specifications carried multiples of the basic T1 (1.544 Mbit/s) data rates, such as T2 (6.312 Mbit/s) with 96 channels, T3 (44.736 Mbit/s) with 672 channels, and others.",
            "uuid": "a1axlfBuSkOb84pL+w93lw==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 126811953513775451,
        },
        {
            "name": "E1",
            "code": "E1",
            "description": "The E-carrier is a member of the series of carrier systems developed for digital transmission of many simultaneous telephone calls by time-division multiplexing.",
            "uuid": "XK9sYVAUTnSUMdEfGnf/iA==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 1372449007792198993,
        },
        {
            "name": "E&M",
            "code": "E&M",
            "description": 'E and M signaling is a type of supervisory line signaling that uses DC signals on separate leads, called the "E" lead and "M" lead, traditionally used in the telecommunications industry between telephone switches.',
            "uuid": "QSYPf3F7TN+8m+w0WGArKg==",
            "technology": ObjectId("65327d056aad5b611082bf6e"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 743276769076947570,
        },
        {
            "name": "V.42",
            "code": "V42",
            "description": "V.42 software is designed for optimum asynchronous-to-synchronous conversion as well as error detection and retransmission of damaged data.",
            "uuid": "DBunJDc8T/+ofmiLkXp/tQ==",
            "technology": ObjectId("65336f2d8989dc8dd4489148"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 2144356384812250065,
        },
        {
            "name": "12 VDC",
            "code": "12VDC",
            "uuid": "35bbAMSAR8Sbw1+bHgfD7g==",
            "technology": ObjectId("6532734d6aad5b611082bf55"),
            "data": [],
            "connection_schema": "U",
            "discriminators": [],
            "bi_id": 1957528276849716450,
        },
        {
            "name": "802.11a",
            "code": "802.11a",
            "description": "IEEE802.11a is the first wireless standard to employ packet based OFDM, based on a proposal from Richard van Nee[7] from Lucent Technologies in Nieuwegein. OFDM was adopted as a draft 802.11a standard in July 1998 after merging with an NTT proposal.",
            "uuid": "zpQLHeqDTdO8ITGwbZWFgg==",
            "technology": ObjectId("6533b6aee74019b4dc11adbf"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 4371934772522378990,
        },
        {
            "name": "PVDM2",
            "code": "PVDM2",
            "uuid": "+9cs3T+fQS2dNekrXEMDsg==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BD",
            "discriminators": [],
            "bi_id": 7436516949408484713,
        },
        {
            "name": "Cisco VIC3",
            "code": "CISCOVIC3",
            "description": "Cisco Voice Interface Card revision 3",
            "uuid": "J07KhI3OSEi9Wsf4as1/Dw==",
            "technology": ObjectId("6533a1268989dc8dd4489158"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 6320628920533514684,
        },
        {
            "name": "1000BASE‑LX10",
            "code": "1000BASELX10",
            "description": "1000BASE-LX10 was standardized six years after the initial gigabit fiber versions as part of the Ethernet in the First Mile task group. It is practically identical to 1000BASE-LX, but achieves longer distances up to 10 km over a pair of single-mode fiber due to higher quality optics",
            "uuid": "TONTtq8VRV+TnDDQUVkBKQ==",
            "technology": ObjectId("653277006aad5b611082bf5c"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "bi_id": 6771223019792057667,
        },
        {
            "name": "Time-of-Day Measurement",
            "code": "ToD",
            "description": "Time-of-day (TOD) traffic signal control is based on the principle where multiple TOD signal timing plans (STPs) are scheduled to operate during the day. TOD plans are characterized by a unique cycle length that is highly correlated with traffic volumes",
            "uuid": "xfDGcTQlRmmU+LGChE179Q==",
            "technology": ObjectId("6534f9ac03acbb1a94714f2f"),
            "data": [],
            "connection_schema": "U",
            "discriminators": [],
            "bi_id": 7927514704554548423,
        },
        {
            "name": "TransEth200G",
            "code": "TransEth200G",
            "description": "Interface for device transievers module",
            "uuid": "g8Pn6y4OSwKMwL/1jEwpDw==",
            "technology": ObjectId("653277c66aad5b611082bf5e"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "transport_protocols": [],
            "bi_id": 6812499707781942403,
        },
        {
            "name": "IEEE1588",
            "code": "IEEE1588",
            "description": "The Precision Time Protocol (PTP) is a protocol used to synchronize clocks throughout a computer network.",
            "uuid": "et/0oIBLRyKDNIMOlq7drw==",
            "technology": ObjectId("6534f9ac03acbb1a94714f2f"),
            "data": [],
            "connection_schema": "U",
            "discriminators": [],
            "transport_protocols": [],
            "bi_id": 2046169047292611198,
        },
        {
            "name": "TL1",
            "code": "TL1",
            "description": "TL1 is an ASCII-based management protocol mainly used for managing telecommunication networks.",
            "uuid": "5Z2lGR1GRJ+r14Nlr3GHYw==",
            "technology": ObjectId("6534fb1303acbb1a94714f31"),
            "data": [],
            "connection_schema": "BO",
            "discriminators": [],
            "transport_protocols": [],
            "bi_id": 2755677725645302549,
        },
    ]

    def migrate(self):
        # Insert Technologies
        bulk = [
            UpdateOne(
                {"_id": ObjectId("6532734d6aad5b611082bf55")},
                {
                    "$set": {
                        "name": "Energetics",
                        "uuid": UUID("80a9c79c-3f43-4718-8d60-55815090cdc3"),
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(5829566886584370399),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("65327510bf6b74584155a94f")},
                {
                    "$set": {
                        "name": "USB",
                        "uuid": UUID("05aa3539-fed0-4253-b2fa-c6670264f1b8"),
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(789474188471280328),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("653277006aad5b611082bf5c")},
                {
                    "$set": {
                        "name": "Ethernet",
                        "uuid": UUID("533cdc92-b6f7-4769-9ffd-253693aa28b2"),
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(8517014800812630690),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("65327760bf6b74584155a953")},
                {
                    "$set": {
                        "name": "XPON",
                        "uuid": UUID("2904804b-8bd8-4de8-b727-2deacf48c5a9"),
                        "description": "A passive optical network (PON) is a fiber-optic telecommunications technology for delivering broadband network access to end-customers",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(9177230454852081095),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("653277c66aad5b611082bf5e")},
                {
                    "$set": {
                        "name": "Trasceiver",
                        "uuid": UUID("aef9bb4a-4ff1-4c6e-b7d7-cd7309b8debd"),
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(2211136824221559425),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("65327d056aad5b611082bf6e")},
                {
                    "$set": {
                        "name": "Serial",
                        "uuid": UUID("1b36e203-e78a-4389-bbc9-ad1c59d034ac"),
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(6974045341783340635),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("65335aeac0fe77cd7156a8eb")},
                {
                    "$set": {
                        "name": "WDM",
                        "uuid": UUID("10338c90-ba17-4cba-bcfb-6d4884d743fe"),
                        "description": "In fiber-optic communications, wavelength-division multiplexing (WDM) is a technology which multiplexes a number of optical carrier signals onto a single optical fiber by using different wavelengths (i.e., colors) of laser light.[1] ",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(4386911184028583206),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("65336f2d8989dc8dd4489148")},
                {
                    "$set": {
                        "name": "Modulator-Demodulator",
                        "uuid": UUID("f405cc3d-cbe8-4e43-8c58-2bd7266fb8d5"),
                        "description": "A modulator-demodulator or modem is a computer hardware device that converts data from a digital format into a format suitable for an analog transmission medium such as telephone or radio",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(8030802649834209715),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("653375108989dc8dd448914c")},
                {
                    "$set": {
                        "name": "XDSL",
                        "uuid": UUID("d2aac109-6506-4014-9a98-15537ec4c41f"),
                        "description": "Digital subscriber line (DSL; originally digital subscriber loop) is a family of technologies that are used to transmit digital data over telephone lines. In telecommunications marketing, the term DSL is widely understood to mean asymmetric digital subscriber line (ADSL), the most commonly installed DSL technology, for Internet access.",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(270365769819082249),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("653376058989dc8dd4489152")},
                {
                    "$set": {
                        "name": "PSTN",
                        "uuid": UUID("8e987de1-e2a0-4393-9d98-37b0f5cb55f1"),
                        "description": "The public switched telephone network (PSTN) is the aggregate of the world's telephone networks that are operated by national, regional, or local telephony operators.",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(6193662985572453528),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("6533a1268989dc8dd4489158")},
                {
                    "$set": {
                        "name": "Cisco | Interface Card",
                        "uuid": UUID("29426285-f1e7-4251-ad5f-a32cbc35709a"),
                        "description": "Technology connect interface card (IC) to integrated router.",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(5369425707749880806),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("6533b6aee74019b4dc11adbf")},
                {
                    "$set": {
                        "name": "IEEE 802.11",
                        "uuid": UUID("bd76f5ae-cc89-47ee-8b42-b8d8e89eefe3"),
                        "description": "IEEE 802.11 is part of the IEEE 802 set of local area network (LAN) technical standards, and specifies the set of media access control (MAC) and physical layer (PHY) protocols for implementing wireless local area network (WLAN) computer communication.",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(9135212433141383564),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("6534f9ac03acbb1a94714f2f")},
                {
                    "$set": {
                        "name": "Time Syncrinization",
                        "uuid": UUID("efc7fccd-aa98-4844-912e-ba87ccd410a9"),
                        "description": "Syncronization technology",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(2536936546278884355),
                    }
                },
                upsert=True,
            ),
            UpdateOne(
                {"_id": ObjectId("6534fb1303acbb1a94714f31")},
                {
                    "$set": {
                        "name": "Management",
                        "uuid": UUID("d8854fef-e3df-424f-af2d-4b4533c9c043"),
                        "description": "Device management",
                        "single_service": False,
                        "single_client": False,
                        "allow_children": False,
                        "bi_id": Int64(3178691302554606134),
                    }
                },
                upsert=True,
            ),
        ]
        self.mongo_db.technologies.bulk_write(bulk)
        # Protocols
        bulk = []
        for p in self.protocols:
            p["uuid"] = UUID(bytes=base64.b64decode(p["uuid"]))
            bulk += [
                UpdateOne(
                    {"code": p["code"]},
                    {"$set": p},
                    upsert=True,
                )
            ]
        if bulk:
            self.mongo_db.protocols.bulk_write(bulk)
