#!/bin/sh
##----------------------------------------------------------------------
## NOC CLI
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

cd `dirname $0`

error_exit ( ) {
    printf "\033[1;31m$PROGNAME: ${1:-'Unknown error'}\033[0m\n" 1>&2
    exit 1
}

CMD=$1
if [ -f "./commands/$CMD.sh" ]; then
    shift
    exec /bin/sh ./commands/$CMD.sh "$@"
fi

if [ -f "./commands/$CMD.py" ]; then
    shift
    exec ./commands/$CMD.py "$@"
fi

case "$1" in
    "conf")
        shift
        exec ./scripts/conf.py "$@"
        ;;
    "generate-ssh-keys")
        exec ./scripts/generate-ssh-keys.py "$@"
        ;;
    "get-uuid")
        exec ./scripts/get-uuid.py
        ;;
    "paste")
        shift
        exec ./scripts/paste.py "$@"
        ;;
    "runserver")
        shift
        exec ./scripts/noc-web.py
        ;;
    "upgrade")
        exec ./scripts/upgrade
        ;;
    *)
        exec ./bin/python manage.py "$@"
        ;;
esac
