//---------------------------------------------------------------------
//  Probe Config
//---------------------------------------------------------------------
// Generated by ./noc update-probe-config
//---------------------------------------------------------------------
// Copyright (C) 2007-2015 The NOC Project
// See LICENSE for details
//---------------------------------------------------------------------
console.debug("Defining NOC.metricconfig.pm.probes.test.sin.SinConfig");

Ext.define("NOC.metricconfig.pm.probes.test.sin.SinConfig", {
    extend: "NOC.core.ProbeConfig",
    form: [
        {
            name: "Period",
            xtype: "numberfield",
            fieldLabel: "Period",
            allowBlank: false,
            defaultValue: 60
        },
        {
            name: "Scale",
            xtype: "numberfield",
            fieldLabel: "Scale",
            allowBlank: false,
            defaultValue: 1
        }
    ]
});
