##
## openSUSE 12.3 NOC Vagrantfile
##
Vagrant.configure("2") do |config|
    config.vm.box = "noc-x86_64-openSUSE-12.3";
    config.vm.box_url = "http://cdn.nocproject.org/box/noc-x86_64-openSUSE-12.3.box"
    config.vm.hostname = "noc"
    config.vm.provision :shell, :path => "./bootstrap.sh", :args => "--test"
    config.ssh.default.username = "user"
end
