#!/bin/bash
set -e
echo ${NOC_PG_USER} ${NOC_PG_DB} ${NOC_PG_PASSWORD} end

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${NOC_PG_USER} WITH password '${NOC_PG_PASSWORD}';
    CREATE DATABASE ${NOC_PG_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${NOC_PG_USER} TO ${NOC_PG_DB};
EOSQL