# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## 3Com.SuperStack.get_version test
## Auto-generated by manage.py debug-script at 2010-11-08 10:26:58
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase

class _3Com_SuperStack_get_version_Test(ScriptTestCase):
    script="3Com.SuperStack.get_version"
    vendor="3Com"
    platform='3Com'
    version='2.72'
    input={}
    result={'platform': 'SuperStack 3 Switch 3300XM',
 'vendor': '3Com',
 'version': '2.72'}
    motd=' \n\nMenu options: -------------3Com SuperStack 3 Switch 3300XM--------------\n bridge             - Administer bridging/VLANS\n ethernet           - Administer Ethernet ports\n feature            - Administer system features\n ip                 - Administer IP\n logout             - Logout of the Command Line Interface\n snmp               - Administer SNMP\n system             - Administer system-level functions\n\nType ? for help.\n-----------------------------------Stepan-14(1) (1)---------------------\n'
    cli={
## 'system inventory'
'system inventory': """ system inventory
Position        Description          Unit Name            State
    1           Switch 3300XM                             Operational
""",
## 'system display'
'system display': """ system display
3Com SuperStack 3
System Name\t\t: switch-1
Location\t\t: switch address
Contact\t\t\t: admin@domain.ru

Time Since Reset\t\t: 1147 Hrs 38 Mins 1 Seconds
Operational Version\t\t: 2.72
Hardware Version\t\t: 0
Boot Version\t\t\t: 1.00
MAC Address\t\t\t: 00:04:0b:51:d8:f8
Product Number\t\t\t: 3C16985B
Serial Number\t\t\t: 7MAV551D8F8
""",
}
    snmp_get={}
    snmp_getnext={}
