// Generated by CoffeeScript 1.10.0
(function() {
  Ext.define('Report.settings.Grid', {
    extend: 'Report.settings.Abstract',
    xtype: 'settingsGrid'
  });

}).call(this);

//# sourceMappingURL=Grid.js.map
