# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Force10.FTOS.get_version test
## Auto-generated by manage.py debug-script at 2011-02-02 14:05:49
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Force10_FTOS_get_version_Test(ScriptTestCase):
    script="Force10.FTOS.get_version"
    vendor="Force10"
    platform='S50N'
    version='8.4.2.1'
    input={}
    result={'platform': 'S50N', 'vendor': 'Force10', 'version': '8.4.2.1'}
    motd=' \n'
    cli={
## 'show version'
'show version': """show version
Force10 Networks Real Time Operating System Software
Force10 Operating System Version: 1.0
Force10 Application Software Version: 8.4.2.1
Copyright (c) 1999-2010 by Force10 Networks, Inc.
Build Time: Sun Dec 26 20:21:44 2010
Build Path: /sites/sjc/work/build/buildSpaces/build18/E8-4-2/SW/SRC/Cp_src/Tacacs
sw-15-x2 uptime is 1 day(s), 4 hour(s), 23 minute(s)

System Type: S50N 
Control Processor: Freescale MPC8541E with 268435456 bytes of memory.

32M bytes of boot flash memory.

  1 48-port E/FE/GE (SB)
 48 GigabitEthernet/IEEE 802.3 interface(s)""",
'terminal length 0':  'terminal length 0\n',
}
    snmp_get={}
    snmp_getnext={}
