# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Force10.FTOS.get_local_users test
## Auto-generated by manage.py debug-script at 2010-12-27 10:38:42
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Force10_FTOS_get_local_users_Test(ScriptTestCase):
    script="Force10.FTOS.get_local_users"
    vendor="Force10"
    platform='E600i'
    version='8.3.1.3e'
    input={}
    result=[{'class': 'superuser', 'is_active': True, 'username': 'force10'},
 {'class': 'superuser', 'is_active': True, 'username': 'nocsa'}]
    motd=' \n'
    cli={
'terminal length 0':  'terminal length 0\n',
## 'show running-config | grep ^username'
'show running-config | grep ^username': """show running-config | grep ^username
username force10 password 7 3f8bd22fa7ef9085bff706dba3fe1947 privilege 15
username nocsa secret 5 052e218c9f0c8aba5935824164446b3a privilege 15
""",
}
    snmp_get={}
    snmp_getnext={}
