# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Force10.FTOS.get_version test
## Auto-generated by ./noc debug-script at 2011-09-22 17:04:21
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Force10_FTOS_get_version_Test(ScriptTestCase):
    script = "Force10.FTOS.get_version"
    vendor = "Force10"
    platform = 'S60'
    version = '8.3.3.6'
    input = {}
    result = {'platform': 'S60', 'vendor': 'Force10', 'version': '8.3.3.6'}
    motd = ''
    cli = {
## 'show version'
'show version': """show version
Force10 Networks Real Time Operating System Software
Force10 Operating System Version: 1.0
Force10 Application Software Version: 8.3.3.6
Copyright (c) 1999-2011 by Force10 Networks, Inc.
Build Time: Thu Jun 30 09:47:54 PDT 2011
Build Path: /sites/sjc/work/build/buildSpaces/build14/E8-3-3/SW/SRC
f10stack1 uptime is 6 week(s), 0 day(s), 17 hour(s), 49 minute(s)

System image file is "system://A"

System Type: S60 
Control Processor: Freescale MPC8536E with 2147483648 bytes of memory.

128M bytes of boot flash memory.

  3 48-port E/FE/GE (SC)
144 GigabitEthernet/IEEE 802.3 interface(s)
  6 Ten GigabitEthernet/IEEE 802.3 interface(s)""", 
'terminal length 0':  'terminal length 0\n', 
}
    snmp_get = {}
    snmp_getnext = {}
