# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## HP.ProCurve.get_mac_address_table test
## Auto-generated by ./noc debug-script at 21.01.2013 18:09:55
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class HP_ProCurve_get_mac_address_table_Test(ScriptTestCase):
    script = "HP.ProCurve.get_mac_address_table"
    vendor = "HP"
    platform = "2520"
    version = "S.14.03"
    input = {}
    result = [{'interfaces': ['26'], 'mac': '00:1C:2E:3B:2E:80', 'type': 'D', 'vlan_id': 1},
 {'interfaces': ['25'], 'mac': '58:8D:09:4B:FD:6A', 'type': 'D', 'vlan_id': 1},
 {'interfaces': ['26'],
  'mac': '00:00:0C:07:AC:0A',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '00:14:38:47:C8:06',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '00:1C:2E:3B:2E:80',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['18'],
  'mac': '00:1E:37:1E:22:C1',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '2C:41:38:82:80:F4',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['21'],
  'mac': '2C:41:38:88:4B:EA',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '44:1E:A1:32:61:12',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['25'],
  'mac': '58:8D:09:4B:FD:6A',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['13'],
  'mac': '58:8D:09:AE:00:C9',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '58:8D:09:AE:00:CA',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['24'],
  'mac': 'B4:39:D6:33:DB:C0',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['24'],
  'mac': 'B4:39:D6:33:DB:E8',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['22'],
  'mac': 'E4:11:5B:DD:93:84',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': 'E8:39:35:8E:73:12',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['14'],
  'mac': 'E8:39:35:8F:ED:68',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['17'],
  'mac': 'F0:DE:F1:3A:39:AC',
  'type': 'D',
  'vlan_id': 10},
 {'interfaces': ['26'],
  'mac': '00:00:0C:07:AC:14',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['20'],
  'mac': '00:0B:82:27:C2:88',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['5'], 'mac': '00:0B:82:29:16:F1', 'type': 'D', 'vlan_id': 20},
 {'interfaces': ['26'],
  'mac': '00:0B:82:29:29:A3',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['14'],
  'mac': '00:0B:82:29:2C:1F',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['4'], 'mac': '00:0B:82:29:2C:25', 'type': 'D', 'vlan_id': 20},
 {'interfaces': ['26'],
  'mac': '00:0B:82:29:2C:26',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['17'],
  'mac': '00:0B:82:29:79:D8',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['16'],
  'mac': '00:0B:82:29:79:DC',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['19'],
  'mac': '00:0B:82:29:79:DE',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['10'],
  'mac': '00:0B:82:30:0A:E5',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['1'], 'mac': '00:0B:82:30:0B:18', 'type': 'D', 'vlan_id': 20},
 {'interfaces': ['2'], 'mac': '00:0B:82:30:0B:19', 'type': 'D', 'vlan_id': 20},
 {'interfaces': ['6'], 'mac': '00:0B:82:30:8F:47', 'type': 'D', 'vlan_id': 20},
 {'interfaces': ['12'],
  'mac': '00:0B:82:30:8F:53',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['15'],
  'mac': '00:0B:82:3C:1B:0B',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['23'],
  'mac': '00:0B:82:3C:1B:0C',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['18'],
  'mac': '00:0B:82:3C:1B:12',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['24'],
  'mac': '00:0E:08:4D:6F:68',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['24'],
  'mac': '00:0E:08:4D:6F:AB',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['25'],
  'mac': '58:8D:09:4B:FD:6A',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['26'],
  'mac': '58:8D:09:AE:00:CA',
  'type': 'D',
  'vlan_id': 20},
 {'interfaces': ['26'],
  'mac': '00:00:0C:07:AC:1E',
  'type': 'D',
  'vlan_id': 30},
 {'interfaces': ['25'],
  'mac': '58:8D:09:4B:FD:6A',
  'type': 'D',
  'vlan_id': 30},
 {'interfaces': ['26'],
  'mac': '58:8D:09:AE:00:CA',
  'type': 'D',
  'vlan_id': 30},
 {'interfaces': ['9'],
  'mac': '00:0B:FC:DB:94:1B',
  'type': 'D',
  'vlan_id': 200},
 {'interfaces': ['13'],
  'mac': '58:8D:09:AE:00:C9',
  'type': 'D',
  'vlan_id': 200},
 {'interfaces': ['9'],
  'mac': '64:D9:89:DE:8C:06',
  'type': 'D',
  'vlan_id': 200},
 {'interfaces': ['11'],
  'mac': 'F4:55:9C:ED:FA:60',
  'type': 'D',
  'vlan_id': 250},
 {'interfaces': ['7'],
  'mac': '8C:89:A5:53:D9:69',
  'type': 'D',
  'vlan_id': 300},
 {'interfaces': ['24'],
  'mac': 'C8:60:00:02:28:4A',
  'type': 'D',
  'vlan_id': 300}]
    motd = ''
    cli = {
## 'walkMIB ifName'
'walkMIB ifName': """walkMIB ifNameifName.1 = 1
ifName.2 = 2
ifName.3 = 3
ifName.4 = 4
ifName.5 = 5
ifName.6 = 6
ifName.7 = 7
ifName.8 = 8
ifName.9 = 9
ifName.10 = 10
ifName.11 = 11
ifName.12 = 12
ifName.13 = 13
ifName.14 = 14
ifName.15 = 15
ifName.16 = 16
ifName.17 = 17
ifName.18 = 18
ifName.19 = 19
ifName.20 = 20
ifName.21 = 21
ifName.22 = 22
ifName.23 = 23
ifName.24 = 24
ifName.25 = 25
ifName.26 = 26
ifName.27 = 27
ifName.28 = 28
ifName.58 = DEFAULT_VLAN
ifName.67 = VLAN10
ifName.77 = VLAN20
ifName.87 = VLAN30
ifName.257 = VLAN200
ifName.307 = VLAN250
ifName.357 = VLAN300
ifName.4152 = lo0
ifName.4153 = lo1
ifName.4154 = lo2
ifName.4155 = lo3
ifName.4156 = lo4
ifName.4157 = lo5
ifName.4158 = lo6
ifName.4159 = lo7""", 
## 'walkMIB dot1qVlanFdbId'
'walkMIB dot1qVlanFdbId': """walkMIB dot1qVlanFdbIddot1qVlanFdbId.0.1 = 1
dot1qVlanFdbId.0.10 = 2
dot1qVlanFdbId.0.20 = 3
dot1qVlanFdbId.0.30 = 4
dot1qVlanFdbId.0.200 = 5
dot1qVlanFdbId.0.250 = 6
dot1qVlanFdbId.0.300 = 7""", 
'terminal length 1000':  'terminal length ', 
## 'walkMIB dot1qTpFdbPort'
'walkMIB dot1qTpFdbPort': """walkMIB dot1qTpFdbPortdot1qTpFdbPort.1.0.28.46.59.46.128 = 26
dot1qTpFdbPort.1.8.46.95.224.155.128 = 0
dot1qTpFdbPort.1.88.141.9.75.253.106 = 25
dot1qTpFdbPort.2.0.0.12.7.172.10 = 26
dot1qTpFdbPort.2.0.20.56.71.200.6 = 26
dot1qTpFdbPort.2.0.28.46.59.46.128 = 26
dot1qTpFdbPort.2.0.30.55.30.34.193 = 18
dot1qTpFdbPort.2.8.46.95.224.155.128 = 0
dot1qTpFdbPort.2.44.65.56.130.128.244 = 26
dot1qTpFdbPort.2.44.65.56.136.75.234 = 21
dot1qTpFdbPort.2.68.30.161.50.97.18 = 26
dot1qTpFdbPort.2.88.141.9.75.253.106 = 25
dot1qTpFdbPort.2.88.141.9.174.0.201 = 13
dot1qTpFdbPort.2.88.141.9.174.0.202 = 26
dot1qTpFdbPort.2.180.57.214.51.219.192 = 24
dot1qTpFdbPort.2.180.57.214.51.219.232 = 24
dot1qTpFdbPort.2.228.17.91.221.147.132 = 22
dot1qTpFdbPort.2.232.57.53.142.115.18 = 26
dot1qTpFdbPort.2.232.57.53.143.237.104 = 14
dot1qTpFdbPort.2.240.222.241.58.57.172 = 17
dot1qTpFdbPort.3.0.0.12.7.172.20 = 26
dot1qTpFdbPort.3.0.11.130.39.194.136 = 20
dot1qTpFdbPort.3.0.11.130.41.22.241 = 5
dot1qTpFdbPort.3.0.11.130.41.41.163 = 26
dot1qTpFdbPort.3.0.11.130.41.44.31 = 14
dot1qTpFdbPort.3.0.11.130.41.44.37 = 4
dot1qTpFdbPort.3.0.11.130.41.44.38 = 26
dot1qTpFdbPort.3.0.11.130.41.121.216 = 17
dot1qTpFdbPort.3.0.11.130.41.121.220 = 16
dot1qTpFdbPort.3.0.11.130.41.121.222 = 19
dot1qTpFdbPort.3.0.11.130.48.10.229 = 10
dot1qTpFdbPort.3.0.11.130.48.11.24 = 1
dot1qTpFdbPort.3.0.11.130.48.11.25 = 2
dot1qTpFdbPort.3.0.11.130.48.143.71 = 6
dot1qTpFdbPort.3.0.11.130.48.143.83 = 12
dot1qTpFdbPort.3.0.11.130.60.27.11 = 15
dot1qTpFdbPort.3.0.11.130.60.27.12 = 23
dot1qTpFdbPort.3.0.11.130.60.27.18 = 18
dot1qTpFdbPort.3.0.14.8.77.111.104 = 24
dot1qTpFdbPort.3.0.14.8.77.111.171 = 24
dot1qTpFdbPort.3.8.46.95.224.155.128 = 0
dot1qTpFdbPort.3.88.141.9.75.253.106 = 25
dot1qTpFdbPort.3.88.141.9.174.0.202 = 26
dot1qTpFdbPort.4.0.0.12.7.172.30 = 26
dot1qTpFdbPort.4.8.46.95.224.155.128 = 0
dot1qTpFdbPort.4.88.141.9.75.253.106 = 25
dot1qTpFdbPort.4.88.141.9.174.0.202 = 26
dot1qTpFdbPort.5.0.11.252.219.148.27 = 9
dot1qTpFdbPort.5.8.46.95.224.155.128 = 0
dot1qTpFdbPort.5.88.141.9.174.0.201 = 13
dot1qTpFdbPort.5.100.217.137.222.140.6 = 9
dot1qTpFdbPort.6.8.46.95.224.155.128 = 0
dot1qTpFdbPort.6.244.85.156.237.250.96 = 11
dot1qTpFdbPort.7.8.46.95.224.155.128 = 0
dot1qTpFdbPort.7.140.137.165.83.217.105 = 7
dot1qTpFdbPort.7.200.96.0.2.40.74 = 24""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
