# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## HP.ProCurve.get_chassis_id test
## Auto-generated by ./noc debug-script at 21.01.2013 18:05:32
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class HP_ProCurve_get_chassis_id_Test(ScriptTestCase):
    script = "HP.ProCurve.get_chassis_id"
    vendor = "HP"
    platform = "2510"
    version = "Q.11.17"
    input = {}
    result = {'first_chassis_mac': '00:18:FE:57:1F:80',
 'last_chassis_mac': '00:18:FE:57:1F:80'}
    motd = ''
    cli = {
'terminal length 1000':  'terminal length ', 
## 'show management'
'show management': """show management
 Status and Counters - Management Address Information

  Time Server Address : Disabled                  

  SNTP Server Address Protocol Version
  ------------------- ----------------
  192.168.72.100      3               
 

  Default Gateway     : 192.168.2.3    

  VLAN Name    MAC Address         | IP Address         
  ------------ ------------------- + -------------------
  DEFAULT_VLAN 0018fe-571f80       | Disabled           
  VLAN2        0018fe-571f80       | 192.168.2.11       
  VLAN25       0018fe-571f80       | Disabled           
  VLAN28       0018fe-571f80       | Disabled           
  VLAN36       0018fe-571f80       | Disabled           
  Edu          0018fe-571f80       | Disabled           
 
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
