# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## HP.ProCurve.get_lldp_neighbors test
## Auto-generated by ./noc debug-script at 21.01.2013 18:19:49
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class HP_ProCurve_get_lldp_neighbors_Test(ScriptTestCase):
    script = "HP.ProCurve.get_lldp_neighbors"
    vendor = "HP"
    platform = "5406zl"
    version = "K.12.57"
    input = {}
    result = [{'local_interface': 'A1',
  'local_interface_id': 1,
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:17:08:CA:8F:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '1',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'hp54_3'}]},
 {'local_interface': 'B16',
  'local_interface_id': 40,
  'neighbors': [{'remote_capabilities': 36,
                 'remote_chassis_id': '00:0B:82:39:ED:03',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '00 0b 82 39 ed 03',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'gxp1450_000b8239ed03'}]},
 {'local_interface': 'C1',
  'local_interface_id': 49,
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:17:08:CC:03:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '49',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'hp54_6'}]},
 {'local_interface': 'C10',
  'local_interface_id': 58,
  'neighbors': [{'remote_capabilities': 36,
                 'remote_chassis_id': '00:0B:82:2D:82:4E',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '00 0b 82 2d 82 4e',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'gxp1450_000b822d824e'}]},
 {'local_interface': 'D1',
  'local_interface_id': 73,
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:15:60:EE:01:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '73',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'hp54_8'}]},
 {'local_interface': 'E23',
  'local_interface_id': 119,
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:15:60:EF:A4:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '93',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'hp54_7'}]},
 {'local_interface': 'F14',
  'local_interface_id': 134,
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:1C:2E:82:33:40',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '25',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'food_switch'}]}]
    motd = ''
    cli = {
## 'show lldp info remote-device'
'show lldp info remote-device': """show lldp info remote-device
 LLDP Remote Devices Information

  LocalPort | ChassisId                 PortId PortDescr SysName               
  --------- + ------------------------- ------ --------- ----------------------
  A1        | 00 17 08 ca 8f 00         1      A1        hp54_3                
  B16       | 00 0b 82 39 ed 03         00 ... eth0      gxp1450_000b8239ed03  
  C1        | 00 17 08 cc 03 00         49     C1        hp54_6                
  C10       | 00 0b 82 2d 82 4e         00 ... eth0      gxp1450_000b822d824e  
  D1        | 00 15 60 ee 01 00         73     D1        hp54_8                
  E23       | 00 15 60 ef a4 00         93     D21       hp54_7                
  F14       | 00 1c 2e 82 33 40         25     25        food_switch           
 
""", 
## 'show lldp info remote-device A1'
'show lldp info remote-device A1': """show lldp info remote-device A1
 LLDP Remote Device Information Detail

  Local Port   : A1
  ChassisType  : mac-address         
  ChassisId    : 00 17 08 ca 8f 00        
  PortType     : local  
  PortId       : 1                        
  SysName      : hp54_3                        
  System Descr : ProCurve J8697A Switch 5406zl, revision K.12.57, ROM K.12...
  PortDescr    : A1                                                          

  System Capabilities Supported  : bridge, router
  System Capabilities Enabled    : bridge

  Remote Management Address
     Type    : ipv4
     Address : 192.168.2.5

""", 
## 'show lldp info local-device'
'show lldp info local-device': """show lldp info local-device
 LLDP Local Device Information

  Chassis Type : mac-address      
  Chassis Id   : 00 17 08 cb aa 00        
  System Name  : hp54_4                        
  System Description : ProCurve J8697A Switch 5406zl, revision K.12.57, ROM...
  System Capabilities Supported:bridge, router
  System Capabilities Enabled:bridge

  Management Address  :
     Type:ipv4
     Address:192.168.2.6

 LLDP Port Information

  Port     | PortType PortId   PortDesc
  -------- + -------- -------- --------
  A1       | local    1        A1      
  A2       | local    2        A2      
  A3       | local    3        A3      
  A4       | local    4        A4      
  A5       | local    5        A5      
  A6       | local    6        A6      
  A7       | local    7        A7      
  A8       | local    8        A8      
  A9       | local    9        A9      
  A10      | local    10       A10     
  A11      | local    11       A11     
  A12      | local    12       A12     
  A13      | local    13       A13     
  A14      | local    14       A14     
  A15      | local    15       A15     
  A16      | local    16       A16     
  A17      | local    17       A17     
  A18      | local    18       A18     
  A19      | local    19       A19     
  A20      | local    20       A20     
  A21      | local    21       A21     
  A22      | local    22       A22     
  A23      | local    23       A23     
  A24      | local    24       A24     
  B1       | local    25       B1      
  B2       | local    26       B2      
  B3       | local    27       B3      
  B4       | local    28       B4      
  B5       | local    29       B5      
  B6       | local    30       B6      
  B7       | local    31       B7      
  B8       | local    32       B8      
  B9       | local    33       B9      
  B10      | local    34       B10     
  B11      | local    35       B11     
  B12      | local    36       B12     
  B13      | local    37       B13     
  B14      | local    38       B14     
  B15      | local    39       B15     
  B16      | local    40       B16     
  B17      | local    41       B17     
  B18      | local    42       B18     
  B19      | local    43       B19     
  B20      | local    44       B20     
  B21      | local    45       B21     
  B22      | local    46       B22     
  B23      | local    47       B23     
  B24      | local    48       B24     
  C1       | local    49       C1      
  C2       | local    50       C2      
  C3       | local    51       C3      
  C4       | local    52       C4      
  C5       | local    53       C5      
  C6       | local    54       C6      
  C7       | local    55       C7      
  C8       | local    56       C8      
  C9       | local    57       C9      
  C10      | local    58       C10     
  C11      | local    59       C11     
  C12      | local    60       C12     
  C13      | local    61       C13     
  C14      | local    62       C14     
  C15      | local    63       C15     
  C16      | local    64       C16     
  C17      | local    65       C17     
  C18      | local    66       C18     
  C19      | local    67       C19     
  C20      | local    68       C20     
  C21      | local    69       C21     
  C22      | local    70       C22     
  C23      | local    71       C23     
  C24      | local    72       C24     
  D1       | local    73       D1      
  D2       | local    74       D2      
  D3       | local    75       D3      
  D4       | local    76       D4      
  D5       | local    77       D5      
  D6       | local    78       D6      
  D7       | local    79       D7      
  D8       | local    80       D8      
  D9       | local    81       D9      
  D10      | local    82       D10     
  D11      | local    83       D11     
  D12      | local    84       D12     
  D13      | local    85       D13     
  D14      | local    86       D14     
  D15      | local    87       D15     
  D16      | local    88       D16     
  D17      | local    89       D17     
  D18      | local    90       D18     
  D19      | local    91       D19     
  D20      | local    92       D20     
  D21      | local    93       D21     
  D22      | local    94       D22     
  D23      | local    95       D23     
  D24      | local    96       D24     
  E1       | local    97       E1      
  E2       | local    98       E2      
  E3       | local    99       E3      
  E4       | local    100      E4      
  E5       | local    101      E5      
  E6       | local    102      E6      
  E7       | local    103      E7      
  E8       | local    104      E8      
  E9       | local    105      E9      
  E10      | local    106      E10     
  E11      | local    107      E11     
  E12      | local    108      E12     
  E13      | local    109      E13     
  E14      | local    110      E14     
  E15      | local    111      E15     
  E16      | local    112      E16     
  E17      | local    113      E17     
  E18      | local    114      E18     
  E19      | local    115      E19     
  E20      | local    116      E20     
  E21      | local    117      E21     
  E22      | local    118      E22     
  E23      | local    119      E23     
  E24      | local    120      E24     
  F1       | local    121      F1      
  F2       | local    122      F2      
  F3       | local    123      F3      
  F4       | local    124      F4      
  F5       | local    125      F5      
  F6       | local    126      F6      
  F7       | local    127      F7      
  F8       | local    128      F8      
  F9       | local    129      F9      
  F10      | local    130      F10     
  F11      | local    131      F11     
  F12      | local    132      F12     
  F13      | local    133      F13     
  F14      | local    134      F14     
  F15      | local    135      F15     
  F16      | local    136      F16     
  F17      | local    137      F17     
  F18      | local    138      F18     
  F19      | local    139      F19     
  F20      | local    140      F20     
  F21      | local    141      F21     
  F22      | local    142      F22     
  F23      | local    143      F23     
  F24      | local    144      F24     
 """, 
## 'show lldp info remote-device C1'
'show lldp info remote-device C1': """show lldp info remote-device C1
 LLDP Remote Device Information Detail

  Local Port   : C1
  ChassisType  : mac-address         
  ChassisId    : 00 17 08 cc 03 00        
  PortType     : local  
  PortId       : 49                       
  SysName      : hp54_6                        
  System Descr : ProCurve J8697A Switch 5406zl, revision K.12.57, ROM K.12...
  PortDescr    : C1                                                          

  System Capabilities Supported  : bridge, router
  System Capabilities Enabled    : bridge

  Remote Management Address
     Type    : ipv4
     Address : 192.168.2.8

""", 
## 'show lldp info remote-device E23'
'show lldp info remote-device E23': """show lldp info remote-device E23
 LLDP Remote Device Information Detail

  Local Port   : E23
  ChassisType  : mac-address         
  ChassisId    : 00 15 60 ef a4 00        
  PortType     : local  
  PortId       : 93                       
  SysName      : hp54_7                        
  System Descr : ProCurve J8697A Switch 5406zl, revision K.12.57, ROM K.12...
  PortDescr    : D21                                                         

  System Capabilities Supported  : bridge, router
  System Capabilities Enabled    : bridge

  Remote Management Address
     Type    : ipv4
     Address : 192.168.2.9

""", 
'terminal length 1000':  'terminal length ', 
## 'show lldp info remote-device F14'
'show lldp info remote-device F14': """show lldp info remote-device F14
 LLDP Remote Device Information Detail

  Local Port   : F14
  ChassisType  : mac-address         
  ChassisId    : 00 1c 2e 82 33 40        
  PortType     : local  
  PortId       : 25                       
  SysName      : food_switch                   
  System Descr : ProCurve J4900C Switch 2626, revision H.10.83, ROM H.08.0...
  PortDescr    : 25                                                          

  System Capabilities Supported  : bridge, router
  System Capabilities Enabled    : bridge

  Remote Management Address
     Type    : ipv4
     Address : 192.168.2.31

""", 
## 'show lldp info remote-device D1'
'show lldp info remote-device D1': """show lldp info remote-device D1
 LLDP Remote Device Information Detail

  Local Port   : D1
  ChassisType  : mac-address         
  ChassisId    : 00 15 60 ee 01 00        
  PortType     : local  
  PortId       : 73                       
  SysName      : hp54_8                        
  System Descr : ProCurve J8697A Switch 5406zl, revision K.12.57, ROM K.12...
  PortDescr    : D1                                                          

  System Capabilities Supported  : bridge, router
  System Capabilities Enabled    : bridge

  Remote Management Address
     Type    : ipv4
     Address : 192.168.2.10

""", 
## 'show lldp info remote-device C10'
'show lldp info remote-device C10': """show lldp info remote-device C10
 LLDP Remote Device Information Detail

  Local Port   : C10
  ChassisType  : mac-address         
  ChassisId    : 00 0b 82 2d 82 4e        
  PortType     : mac-...
  PortId       : 00 0b 82 2d 82 4e        
  SysName      : gxp1450_000b822d824e          
  System Descr : GXP1450 1.0.4.9                                             
  PortDescr    : eth0                                                        

  System Capabilities Supported  : bridge, telephone
  System Capabilities Enabled    : bridge, telephone

  Remote Management Address
     Type    : ipv4
     Address : 192.168.16.191

  MED Information Detail 
    EndpointClass          :Class3
    Media Policy Vlan id   :0
    Media Policy Priority  :0
    Media Policy Dscp      :0
    Media Policy Tagged    :False
    Poe Device Type        :PD
    Power Requested        :38
    Power Source           :From PSE
    Power Priority         :Unknown

""", 
## 'show lldp info remote-device B16'
'show lldp info remote-device B16': """show lldp info remote-device B16
 LLDP Remote Device Information Detail

  Local Port   : B16
  ChassisType  : mac-address         
  ChassisId    : 00 0b 82 39 ed 03        
  PortType     : mac-...
  PortId       : 00 0b 82 39 ed 03        
  SysName      : gxp1450_000b8239ed03          
  System Descr : GXP1450 1.0.4.9                                             
  PortDescr    : eth0                                                        

  System Capabilities Supported  : bridge, telephone
  System Capabilities Enabled    : bridge, telephone

  Remote Management Address
     Type    : ipv4
     Address : 192.168.16.166

  MED Information Detail 
    EndpointClass          :Class3
    Media Policy Vlan id   :0
    Media Policy Priority  :0
    Media Policy Dscp      :0
    Media Policy Tagged    :False
    Poe Device Type        :PD
    Power Requested        :38
    Power Source           :From PSE
    Power Priority         :Unknown

""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
