# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.FWSM.get_version test
## Auto-generated by manage.py debug-script at 2011-03-25 23:37:51
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Cisco_FWSM_get_version_Test(ScriptTestCase):
    script="Cisco.FWSM.get_version"
    vendor="Cisco"
    platform='WS-SVC-FWM-1'
    version='4.0(2)'
    input={}
    result={'platform': 'WS-SVC-FWM-1', 'vendor': 'Cisco', 'version': '4.0(2)'}
    motd="Type help or '?' for a list of available commands.\n"
    cli={
'terminal pager 0':  ' terminal pager 0\n', 
## 'show version'
'show version': """ show version

FWSM Firewall Version 4.0(2) <context>
Device Manager Version 6.1(1)F

Compiled on Tue 29-Jul-08 15:50 by fwsmbld

fwsm2 up 207 days 0 hours

Hardware:   WS-SVC-FWM-1, 1024 MB RAM, CPU Pentium III 1000 MHz
Flash STI Flash 7.2.0 @ 0xc321, 20MB

 0: Int: Not licensed        : irq 5
 1: Int: Not licensed        : irq 7
 2: Int: Not licensed        : irq 11

Licensed features for this platform:
Maximum Interfaces          : 100       
Inside Hosts                : Unlimited 
Failover                    : Active/Active
VPN-DES                     : Enabled   
VPN-3DES-AES                : Enabled   
Cut-through Proxy           : Enabled   
Guards                      : Enabled   
URL Filtering               : Enabled   
Security Contexts           : 20        
GTP/GPRS                    : Disabled  
BGP Stub                    : Disabled  
Service Acceleration        : Disabled  
VPN Peers                   : Unlimited 

Serial Number: SAD10450227
Running Activation Key: 0xfd06b9ff 0xe422be60 0x26911f6d 0x2ff0d965 
Configuration has not been modified since last system restart.""", 
}
    snmp_get={}
    snmp_getnext={}
