# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Alentis.NetPing.get_chassis_id test
## Auto-generated by ./noc debug-script at 2012-01-16 16:43:19
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Alentis_NetPing_get_chassis_id_Test(ScriptTestCase):
    script = "Alentis.NetPing.get_chassis_id"
    vendor = "Alentis"
    platform = 'UniPing-RS232'
    version = '50.8.7.A-2'
    input = {}
    result = '00:A2:E0:CF:00:00'
    motd = ''
    cli = {
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {'/setup_get.cgi': 'var packfmt={mac:{offs:0,len:6},ip:{offs:6,len:4},gate:{offs:10,len:4},mask:{offs:14,len:1},http_port:{offs:16,len:2},uname:{offs:18,len:18},passwd:{offs:36,len:18},community_r:{offs:54,len:18},community_w:{offs:72,len:18},filt_ip1:{offs:90,len:4},filt_mask1:{offs:94,len:1},trap_ip1:{offs:105,len:4},ntp_ip1:{offs:113,len:4},ntp_ip2:{offs:117,len:4},timezone:{offs:121,len:1},syslog_ip1:{offs:122,len:4},facility:{offs:130,len:1},severity:{offs:131,len:1},__len:132};\r\nvar data={serial:"SN:53216 [00.2008]",mac:\'00:a2:e0:cf:00:00\',ip:\'10.8.29.2\',gate:\'10.8.29.1\',mask:\'255.255.255.0\',http_port:80,uname:"visor",passwd:"ping",community_r:"SWITCH",community_w:"SWITCH",filt_ip1:\'0.0.0.0\',filt_mask1:\'0.0.0.0\',trap_ip1:\'10.8.4.19\',ntp_ip1:\'62.33.189.253\',ntp_ip2:\'0.0.0.0\',timezone:8,syslog_ip1:\'0.0.0.0\',facility:0,severity:0};'}
