# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Juniper.JUNOSe.get_version test
## Auto-generated by manage.py debug-script at 2010-12-24 18:40:27
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Juniper_JUNOSe_get_version_Test(ScriptTestCase):
    script="Juniper.JUNOSe.get_version"
    vendor="Juniper"
    platform='ERX-310'
    version='9.2.0 patch-1.0'
    input={}
    result={'platform': 'ERX-310',
 'vendor': 'Juniper',
 'version': '9.2.0 patch-1.0'}
    motd=' ********\nLogged in on vty 0 via telnet.\nCopyright (c) 1999-2008 Juniper Networks, Inc.  All rights reserved.\n\n'
    cli={
## 'show version'
'show version': """show version
Juniper Edge Routing Switch ERX-310
Copyright (c) 1999-2008 Juniper Networks, Inc.  All rights reserved.
System Release: erx310_9-2-0p1-0.rel
\tVersion: 9.2.0 patch-1.0 [BuildId 9793]   (July 22, 2008  14:13)
System running for: 80 days, 8 hours, 35 minutes, 11 seconds
\t(since TUE OCT 05 2010 07:05:11 UTC)

slot state     type     admin  spare   running release     slot uptime  
---- ------ ---------- ------- ----- -------------------- --------------
0    online SRP310-10G enabled  ---  erx310_9-2-0p1-0.rel 80d08h:32m:42s
1     ---      ---       ---    ---          ---               ---      
2    online GE-HDE-8   enabled  ---  erx310_9-2-0p1-0.rel 80d08h:32m:22s
""",
'terminal length 0':  'terminal length 0\n',
}
    snmp_get={}
    snmp_getnext={}
