#!./bin/python
# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Generate etc/supervisord.conf
##----------------------------------------------------------------------
## Copyright (C) 2007-2015 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## Python modules
import sys
import glob
import ConfigParser
import cStringIO
import sys
import os
import subprocess
## Third party modules
import yaml


SUPERVISORD_CFG = "etc/supervisord.conf"
NOC_CFG = "etc/noc.yml"

ENV_MAP = {
    "loglevel": "NOC_LOGLEVEL",
    "listen": "NOC_LISTEN"
}


def format_env(env):
    """
    Build environment string
    """
    def q(s):
        return str(s).replace("%", "%%")
    return ",".join("%s=\"%s\"" % (k, q(env[k])) for k in env)


def build(node):
    with open(NOC_CFG) as f:
        jcfg = yaml.load(f)
    config = ConfigParser.RawConfigParser()
    # Read configs
    for ge in [
        "etc/defaults/supervisor/*.conf",
        "etc/defaults/services/*.conf",
        "etc/config/supervisor/*.conf",
    ]:
        for path in glob.glob(ge):
            config.read(path)
    # Node environment
    ne = {
        "NOC_ENV": jcfg["nodes"][node]["environment"],
        "NOC_DC": jcfg["nodes"][node]["datacenter"],
        "NOC_NODE": node,
        "NOC_USER": jcfg["config"]["noc"]["user"]
    }
    # Build config
    out = ConfigParser.ConfigParser()
    for s in config.sections():
        if s != "supervisord" and not s.startswith("program:"):
            # Copy section
            out.add_section(s)
            for o in config.options(s):
                v = config.get(s, o)
                for e in ne:
                    v = v.replace("%%(ENV_%s)s" % e, ne[e])
                out.set(s, o, v)
            continue
        se = ne.copy()
        # Read environment setting
        if config.has_option(s, "environment"):
            for ec in config.get(s, "environment").split(","):
                k, v = ec.split("=", 1)
                if v.startswith("\"") and v.endswith("\""):
                    v = v[1:-1]
                se[k] = v
        # Process program secrion
        if s.startswith("program:"):
            s = s[8:]  # Strip "program:"
            # Apply global service config
            if s in jcfg["config"]:
                for k in ENV_MAP:
                    if k in jcfg["config"][s]:
                        se[ENV_MAP[k]] = jcfg["config"][s][k]
            # Build pools configuration
            js = [
                sn for sn in jcfg["config"]
                if sn.startswith("%s-" % s) and sn.endswith("-%s" % node)
            ]
            for j in js:
                # Build pool environment
                pe = se.copy()
                pool = j.split("-", 1)[1].split("-", 1)[0]
                if pool == "global":
                    sn = "program:%s" % s
                else:
                    sn = "program:%s-%s" % (s, pool)
                    pe["NOC_POOL"] = pool
                # Build pool environment
                for k in ENV_MAP:
                    if k in jcfg["config"][j]:
                        pe[ENV_MAP[k]] = jcfg["config"][j][k]
                # Build configuration
                out.add_section(sn)
                pn = "program:%s" % s
                # Copy config
                for o in config.options(pn):
                    v = config.get(pn, o)
                    # Apply environment variables
                    for e in pe:
                        v = v.replace("%%(ENV_%s)s" % e, pe[e])
                    #
                    out.set(sn, o, v)
                out.set(sn, "environment", format_env(pe))
                out.set(sn, "autostart", "true")
        elif s == "supervisord":
            out.add_section(s)
            # Copy config
            for o in config.options(s):
                v = config.get(s, o)
                # Apply environment variables
                for e in se:
                    v = v.replace("%%(ENV_%s)s" % e, se[e])
                #
                out.set(s, o, v)
            out.set(s, "environment", format_env(se))
    # Convert to .ini format
    buffer = cStringIO.StringIO()
    out.write(buffer)
    cfg = buffer.getvalue()
    # Read old config
    if os.path.exists(SUPERVISORD_CFG):
        with open(SUPERVISORD_CFG) as f:
            old = f.read()
    else:
        old = None
    if old == cfg:
        print "OK"
    else:
        # Rewrite
        with open(SUPERVISORD_CFG, "w") as f:
            f.write(cfg)
        print "CHANGED"


def apply():
    """
    Apply changes and update config
    """
    subprocess.check_call(["./bin/supervisorctl", "reread"])
    subprocess.check_call(["./bin/supervisorctl", "update"])


if __name__ == "__main__":
    build(sys.argv[1])
    if "--apply" in sys.argv:
        apply()
