#!./bin/python
# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Generate clickhouse dictionaries
##----------------------------------------------------------------------
## Copyright (C) 2007-2016 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## Python modules
import os
import sys
## NOC modules
from noc.core.clickhouse.dictionary import Dictionary
from noc.lib.fileutils import safe_rewrite


def main(path):
    for f in os.listdir("core/bi/dictionaries"):
        if not f.endswith(".py") or f.startswith("_"):
            continue
        dc = Dictionary.get_dictionary_class(f[:-3])
        xml = dc.get_config()
        safe_rewrite(os.path.join(path, "%s.xml" % f[:-3]), xml)


if __name__ == "__main__":
    main(sys.argv[1])
