#!./bin/python
# ----------------------------------------------------------------------
# Generate clickhouse dictionaries
# ----------------------------------------------------------------------
# Copyright (C) 2007-2017 The NOC Project
# See LICENSE for details
# ----------------------------------------------------------------------

# Python modules
import os
import sys
from typing import Optional

# NOC modules
from noc.core.bi.dictionaries.loader import loader
from noc.core.clickhouse.model import DictionaryModel
from noc.core.fileutils import safe_rewrite


def main(path):
    for dcls_name in loader:
        dcls: Optional["DictionaryModel"] = loader[dcls_name]
        if not dcls:
            continue
        xml = dcls.get_config()
        safe_rewrite(
            os.path.join(path, "%s.xml" % dcls._meta.name),
            xml
        )


if __name__ == "__main__":
    main(sys.argv[1])
