# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Linksys.SPS2xx.get_arp test
## Auto-generated by ./noc debug-script at 2011-11-21 15:11:21
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Linksys_SPS2xx_get_arp_Test(ScriptTestCase):
    script = "Linksys.SPS2xx.get_arp"
    vendor = "Linksys"
    platform = 'SPS-224G4'
    version = '1.0.2'
    input = {}
    result = [{'interface': 'g3', 'ip': '10.8.23.1', 'mac': '00:1B:21:1C:03:41'}]
    motd = '*******\n\n'
    cli = {
'terminal datadump':  'terminal datadump\n', 
## 'show arp'
'show arp': """show arp

ARP timeout: 900 Seconds

  VLAN    Interface     IP address        HW address          status      
--------------------- --------------- ------------------- --------------- 
vlan 111   g3         10.8.23.1    00:1b:21:1c:03:41   dynamic         

""", 
}
    snmp_get = {}
    snmp_getnext = {}
