# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Linksys.SPS2xx.get_vlans test
## Auto-generated by ./noc debug-script at 2011-11-21 15:22:54
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Linksys_SPS2xx_get_vlans_Test(ScriptTestCase):
    script = "Linksys.SPS2xx.get_vlans"
    vendor = "Linksys"
    platform = 'SPS-224G4'
    version = '1.0.2'
    input = {}
    result = [{'name': '1', 'vlan_id': 1},
 {'name': 'area_SmileLink', 'vlan_id': 72},
 {'name': 'commutators', 'vlan_id': 111},
 {'name': 'clients', 'vlan_id': 140},
 {'name': 'Test', 'vlan_id': 777}]
    motd = '*******\n\n'
    cli = {
'terminal datadump':  'terminal datadump\n', 
## 'show vlan'
'show vlan': """show vlan

Vlan       Name                   Ports                Type     Authorization 
---- ----------------- --------------------------- ------------ ------------- 
 1           1               g(3-4),ch(1-8)           other       Required    
 72   area_SmileLink         e(2-24),g(1-4)         permanent     Required    
111     commutators              g(3-4)             permanent     Required    
140       clients               e1,g(3-4)           permanent     Required    
777        Test                e(10-11),g1          permanent     Required    
""", 
}
    snmp_get = {}
    snmp_getnext = {}
