# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## MikroTik.RouterOS.get_version test
## Auto-generated by manage.py debug-script at 2011-01-25 17:12:46
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class MikroTik_RouterOS_get_version_Test(ScriptTestCase):
    script="MikroTik.RouterOS.get_version"
    vendor="MikroTik"
    platform='RouterOS'
    version='3.6'
    input={}
    result={'platform': 'RouterOS', 'vendor': 'MikroTik', 'version': '3.6'}
    motd=' \n\n  MMM      MMM       KKK                          TTTTTTTTTTT      KKK\n  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK\n  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK\n  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK\n  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK\n  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK\n\n  MikroTik RouterOS 3.6 (c) 1999-2008       http://www.mikrotik.com/\n\n  '
    cli={
'system package print detail where name="system"':  'system package print detail where name="system"\nFlags: X - disabled \n 0   name="system" version="3.6" build-time=mar/20/2008 13:49:37 scheduled="" \n',
}
    snmp_get={}
    snmp_getnext={}
