# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## MikroTik.RouterOS.get_vlans test
## Auto-generated by ./noc debug-script at 2012-02-09 12:45:52
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class MikroTik_RouterOS_get_vlans_Test(ScriptTestCase):
    script = "MikroTik.RouterOS.get_vlans"
    vendor = "MikroTik"
    platform = 'RB750GL'
    version = '5.12'
    input = {}
    result = [{'vlan_id': 100}]
    motd = ''
    cli = {
'interface ethernet switch vlan print terse':  'interface ethernet switch vlan print terse\n 0   switch=switch1 vlan-id=100 ports=ether5-local-slave independent-learning=no \n\n', 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
