#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=noc
ARGS=
PREFIX=/opt/noc
LAUNCHER=./scripts/noc-launcher.py

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

PID=$(get_pid $DAEMON)

if [ ! -d ${PREFIX} ]; then
 stat_busy "NOC not installed!"
 exit 5
fi

cd $PREFIX

case "$1" in
   start)
       stat_busy "Starting noc-launcher"
       [ -z "$PID" ] && $LAUNCHER start &>/dev/null
       if [ $? = 0 ]; then
           add_daemon $DAEMON
           stat_done
       else
           stat_fail
           exit 1
       fi
       ;;
   stop)
       stat_busy "Stopping noc-launcher"
       [ -z "$PID" ] && $LAUNCHER stop &>/dev/null
       if [ $? = 0 ]; then
           rm_daemon $DAEMON
           stat_done
       else
           stat_fail
           exit 1
       fi
       ;;
   restart)
       $0 stop
       sleep 1
       $0 start
       ;;
   *)
       echo "Usage: $0 {start|stop|restart}"
       ;;
esac
