# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Alcatel.OS62xx.get_version test
## Auto-generated by manage.py debug-script at 2010-09-23 00:37:28
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Alcatel_OS62xx_get_version_Test(ScriptTestCase):
    script="Alcatel.OS62xx.get_version"
    vendor="Alcatel"
    platform='OmniStack LS 6200'
    version='1.5.1.7'
    input={}
    result={'platform': 'OmniStack LS 6200', 'vendor': 'Alcatel', 'version': '1.5.1.7'}
    motd='*********\n\n'
    cli={'show system': ' show system\nSystem Description:                       OmniStack LS 6200\nSystem Up Time (days,hour:min:sec):       40,10:30:40\nSystem Contact:                           \nSystem Name:                              sw-34-ti\nSystem Location:                          \nSystem MAC Address:                       00:12:cf:af:5f:60\nSystem Object ID:                         1.3.6.1.4.1.6486.800.1.1.2.2.4.1.1\nMain Power Supply Status:                 OK\nFan 1 Status:                             OK\n\n\n          Unit            Temperature (Celsius)            Status          \n------------------------ ------------------------ ------------------------ \n           1                        41                       OK            \n\n\n',
 'show version': ' show version\nSW version    1.5.1.7 ( date  26-Feb-2008 time  17:04:09 )\nBoot version    1.0.0.12 ( date  19-Oct-2006 time  09:07:37 )\nHW version    00.00.01\n',
 'terminal datadump': ' terminal datadump\n'}
    snmp_get={}
    snmp_getnext={}
        