# ----------------------------------------------------------------------
# Create utility labels labels
# ----------------------------------------------------------------------
# Copyright (C) 2007-2023 The NOC Project
# See LICENSE for details
# ----------------------------------------------------------------------

# Third-party modules
from pymongo import InsertOne

# NOC modules
from noc.core.migration.base import BaseMigration


class Migration(BaseMigration):
    def migrate(self):
        # Create wildcard labels
        l_coll = self.mongo_db["labels"]
        current_labels = {ll["name"]: ll["_id"] for ll in l_coll.find()}
        bulk = []
        if "noc::is_member_interface::=" not in current_labels:
            bulk += [
                InsertOne(
                    {
                        "name": "noc::is_member_interface::=",
                        "description": "Builtin Labels mark if Interface members on aggregation link",
                        "bg_color1": 16777215,
                        "fg_color1": 0,
                        "bg_color2": 16777215,
                        "fg_color2": 0,
                        "is_protected": False,
                        "is_autogenerated": False,
                        "expose_alarm": True,
                    }
                )
            ]
        if "noc::is_member_interface::=" not in current_labels:
            bulk += [
                InsertOne(
                    {
                        "name": "noc::is_aggregate_interface::=",
                        "description": "Builtin Labels mark if Interface has aggregate type",
                        "bg_color1": 16777215,
                        "fg_color1": 0,
                        "bg_color2": 16777215,
                        "fg_color2": 0,
                        "is_protected": False,
                        "is_autogenerated": False,
                        "expose_alarm": True,
                    }
                ),
            ]
        if bulk:
            l_coll.bulk_write(bulk, ordered=True)
