# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## H3C.VRP.get_lldp_neighbors test
## Auto-generated by manage.py debug-script at 2011-03-11 09:53:53
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class H3C_VRP_get_lldp_neighbors_Test(ScriptTestCase):
    script="H3C.VRP.get_lldp_neighbors"
    vendor="H3C"
    platform='4500G'
    version='5.02.00s56p12'
    input={}
    result=[{'local_interface': 'GigabitEthernet1/0/1',
  'neighbors': [{'remote_capabilities': 20,
                 'remote_chassis_id': '00:24:73:C1:4C:40',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': 'GigabitEthernet4/0/49',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'CORE'}]},
 {'local_interface': 'GigabitEthernet1/0/28',
  'neighbors': [{'remote_capabilities': 20,
                 'remote_chassis_id': '00:24:73:2F:A9:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': 'GigabitEthernet1/0/1',
                 'remote_port_subtype': 5,
                 'remote_system_name': '5500G-EI-TEC5'}]}]
    motd='\n'
    cli={
## 'display version'
'display version': """display version
3Com Corporation
3Com Switch 4500G 24-Port Software Version 3Com OS V5.02.00s56p12
Copyright (c) 2004-2009 3Com Corp. and its licensors. All rights reserved.
3Com Switch 4500G 24-Port uptime is 41 weeks, 2 days, 5 hours, 12 minutes

3Com Switch 4500G 24-Port with 1 Processor
128M    bytes SDRAM
16384K  bytes Flash Memory

Hardware Version is REV.B
CPLD Version is 007
Bootrom Version is 503
[SubSlot 0] 24GE+4SFP Hardware Version is REV.B
""",
## 'display lldp neighbor'
'display lldp neighbor': """display lldp neighbor

LLDP neighbor-information of port 1[GigabitEthernet1/0/1]:
  Neighbor index   : 5
  Update time      : 194 days,4 hours,0 minutes,24 seconds
  Chassis type     : MAC address
  Chassis ID       : 0024-73c1-4c40
  Port ID type     : Interface name
  Port ID          : GigabitEthernet4/0/49
  Port description : GigabitEthernet4/0/49
  System name        : CORE
  System description : Switch 4500 50-Port
  System capabilities supported : Bridge,Router 
  System capabilities enabled   : Bridge,Router

  Management address type           : ipV4
  Management address                : 192.168.20.182
  Management address interface type : IfIndex
  Management address interface ID   : 31
  Management address OID            : 0

  Port VLAN ID(PVID): 1

  Port and protocol VLAN ID(PPVID) : 1
                  Port and protocol VLAN supported : No
  Port and protocol VLAN enabled   : No

  VLAN name of VLAN 1: VLAN 0001

  Auto-negotiation supported : Yes
  Auto-negotiation enabled   : Yes
  OperMau                    : speed(1000)/duplex(Full)

  Power port class          : PD
  PSE power supported       : No
  PSE power enabled         : No
  PSE pairs control ability : No
  Power pairs               : Signal
  Port power classification : Class 0

  Link aggregation supported : Yes
  Link aggregation enabled   : No
  Aggregation port ID        : 0

  Maximum frame Size: 9216


                LLDP neighbor-information of port 28[GigabitEthernet1/0/28]:
  Neighbor index   : 1
  Update time      : 194 days,4 hours,0 minutes,20 seconds
  Chassis type     : MAC address
  Chassis ID       : 0024-732f-a900
  Port ID type     : Interface name
  Port ID          : GigabitEthernet1/0/1
  Port description : GigabitEthernet1/0/1
  System name        : 5500G-EI-TEC5
  System description : Switch 5500G-EI SFP 24-Port
  System capabilities supported : Bridge,Router 
  System capabilities enabled   : Bridge,Router

  Management address type           : ipV4
  Management address                : 192.168.20.254
  Management address interface type : IfIndex
  Management address interface ID   : 31
  Management address OID            : 0

  Port VLAN ID(PVID): 1

  Port and protocol VLAN ID(PPVID) : 1
  Port and protocol VLAN supported : Yes
                  Port and protocol VLAN enabled   : No

  VLAN name of VLAN 1: VLAN 0001

  Auto-negotiation supported : Yes
  Auto-negotiation enabled   : Yes
  OperMau                    : speed(1000)/duplex(Full)

  Power port class          : PD
  PSE power supported       : No
  PSE power enabled         : No
  PSE pairs control ability : No
  Power pairs               : Signal
  Port power classification : Class 0

  Link aggregation supported : Yes
  Link aggregation enabled   : No
  Aggregation port ID        : 0

  Maximum frame Size: 1522
""",
}
    snmp_get={}
    snmp_getnext={}
