# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## H3C.VRP.get_vlans test
## Auto-generated by manage.py debug-script at 2011-03-11 09:14:58
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class H3C_VRP_get_vlans_Test(ScriptTestCase):
    script="H3C.VRP.get_vlans"
    vendor="H3C"
    platform='5500-EI'
    version='3.03.02s56ep05'
    input={}
    result=[{'name': 'VLAN 0001', 'vlan_id': 1},
 {'name': 'VLAN 0010', 'vlan_id': 10},
 {'name': 'VLAN 0030', 'vlan_id': 30},
 {'name': 'PRPOER', 'vlan_id': 31},
 {'name': 'T3-T4', 'vlan_id': 34},
 {'name': 'STK', 'vlan_id': 40},
 {'name': 'VLAN 0099', 'vlan_id': 99},
 {'name': 'EService', 'vlan_id': 110},
 {'name': 'VLAN 0132', 'vlan_id': 132},
 {'name': 'UMTS', 'vlan_id': 160},
 {'name': 'webcam-pgu', 'vlan_id': 170},
 {'name': 'VLAN 0603', 'vlan_id': 603}]
    motd='\n'
    cli={
## 'display vlan all'
'display vlan all': """display vlan all
 VLAN ID: 1
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.70.2
 Subnet Mask: 255.255.255.0
 Description: Default
 Name: VLAN 0001
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/20           GigabitEthernet1/0/28    

 VLAN ID: 10
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.131.31
 Subnet Mask: 255.255.255.0
 Description: VLAN 0010
 Name: VLAN 0010
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/21           

 VLAN ID: 30
 VLAN Type: static
                                           Route Interface: configured
 IP Address: 192.168.31.253
 Subnet Mask: 255.255.255.252
 Description: PRP
 Name: VLAN 0030
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/23           

 VLAN ID: 31
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.31.33
 Subnet Mask: 255.255.255.224
 Description: PRPOER
 Name: PRPOER
 Tagged   Ports: 
  Ethernet1/0/20           GigabitEthernet1/0/28    
 Untagged Ports: none

 VLAN ID: 34
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.135.253
                                           Subnet Mask: 255.255.255.252
 Description: T3-T4
 Name: T3-T4
 Tagged   Ports: 
  Ethernet1/0/24           
 Untagged Ports: none

 VLAN ID: 40
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.134.70
 Subnet Mask: 255.255.255.0
 Description: STK
 Name: STK
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/12           

 VLAN ID: 99
 VLAN Type: static
 Route Interface: configured
 IP Address: 10.99.70.2
 Subnet Mask: 255.255.240.0
 Description: Voice
                                           Name: VLAN 0099
 Tagged   Ports: 
  Ethernet1/0/20           GigabitEthernet1/0/28    
 Untagged Ports: 
  Ethernet1/0/6            Ethernet1/0/7            Ethernet1/0/8            
  Ethernet1/0/9            Ethernet1/0/10           Ethernet1/0/11           
  Ethernet1/0/12           

 VLAN ID: 110
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.111.1
 Subnet Mask: 255.255.255.0
 Description: EService
 Name: EService
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/22           

 VLAN ID: 132
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.132.70
 Subnet Mask: 255.255.255.240
                                           Description: Transport
 Name: VLAN 0132
 Tagged   Ports: 
  Ethernet1/0/2            Ethernet1/0/20           GigabitEthernet1/0/25    
  GigabitEthernet1/0/28    
 Untagged Ports: none

 VLAN ID: 160
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.161.253
 Subnet Mask: 255.255.255.252
 Description: UMTS
 Name: UMTS
 Tagged   Ports: 
  GigabitEthernet1/0/25    
 Untagged Ports: none

 VLAN ID: 170
 VLAN Type: static
 Route Interface: configured
 IP Address: 10.170.3.1
 Subnet Mask: 255.255.255.0
 Description: webcam-pgu
                                           Name: webcam-pgu
 Tagged   Ports: none
 Untagged Ports: 
  Ethernet1/0/5            

 VLAN ID: 603
 VLAN Type: static
 Route Interface: configured
 IP Address: 192.168.133.70
 Subnet Mask: 255.255.255.240
 Description: Transfer TEC3
 Name: VLAN 0603
 Tagged   Ports: 
  GigabitEthernet1/0/25    GigabitEthernet1/0/26    
 Untagged Ports: none
""",
## 'display version'
'display version': """
%Mar 11 09:14:50:226 2011 5500-EI-TEC3 SHELL/5/LOGIN:- 1 - admin(172.20.0.181) in unit1 logindisplay version
3Com Corporation
Switch 5500-EI Software Version 3Com OS V3.03.02s56ep05
Copyright (c) 2004-2009 3Com Corporation and its licensors, All rights reserved.
Switch 5500-EI uptime is 33 weeks, 3 days, 22 hours, 2 minutes

Switch 5500-EI 28-Port with 1 Processor
64M     bytes DRAM
16384K  bytes Flash Memory
Config Register points to FLASH

CPLD Version is CPLD 001
Bootrom Version is 4.02
[Subslot 0] 24 FE + 4 GE Hardware Version is 00.00.00 
""",
}
    snmp_get={}
    snmp_getnext={}
