# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Huawei.VRP.get_interface_status test
## Auto-generated by ./noc debug-script at 21.05.2012 10:06:47
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Huawei_VRP_get_interface_status_Test(ScriptTestCase):
    script = "Huawei.VRP.get_interface_status"
    vendor = "Huawei"
    platform = "S5328C-EI-24S"
    version = "5.70"
    input = {}
    result = [{'interface': 'GigabitEthernet0/0/1', 'status': True},
 {'interface': 'GigabitEthernet0/0/2', 'status': True},
 {'interface': 'GigabitEthernet0/0/3', 'status': True},
 {'interface': 'GigabitEthernet0/0/4', 'status': True},
 {'interface': 'GigabitEthernet0/0/5', 'status': False},
 {'interface': 'GigabitEthernet0/0/6', 'status': False},
 {'interface': 'GigabitEthernet0/0/7', 'status': False},
 {'interface': 'GigabitEthernet0/0/8', 'status': False},
 {'interface': 'GigabitEthernet0/0/9', 'status': False},
 {'interface': 'GigabitEthernet0/0/10', 'status': False},
 {'interface': 'GigabitEthernet0/0/11', 'status': False},
 {'interface': 'GigabitEthernet0/0/12', 'status': False},
 {'interface': 'GigabitEthernet0/0/13', 'status': False},
 {'interface': 'GigabitEthernet0/0/14', 'status': False},
 {'interface': 'GigabitEthernet0/0/15', 'status': False},
 {'interface': 'GigabitEthernet0/0/16', 'status': False},
 {'interface': 'GigabitEthernet0/0/17', 'status': False},
 {'interface': 'GigabitEthernet0/0/18', 'status': False},
 {'interface': 'GigabitEthernet0/0/19', 'status': False},
 {'interface': 'GigabitEthernet0/0/20', 'status': False},
 {'interface': 'GigabitEthernet0/0/21', 'status': False},
 {'interface': 'GigabitEthernet0/0/22', 'status': False},
 {'interface': 'GigabitEthernet0/0/23', 'status': False},
 {'interface': 'GigabitEthernet0/0/24', 'status': True},
 {'interface': 'M-Ethernet0/0/1', 'status': False},
 {'interface': 'NULL0', 'status': True},
 {'interface': 'Vlanif1', 'status': False},
 {'interface': 'Vlanif1000', 'status': True}]
    motd = ''
    cli = {
## 'display interface brief'
'display interface brief': """display interface brief
PHY: Physical
*down: administratively down
^down: standby
(l): loopback
(s): spoofing
(b): BFD down
(e): ETHOAM down
(d): Dampening Suppressed
InUti/OutUti: input utility/output utility
Interface                   PHY   Protocol InUti OutUti   inErrors  outErrors
GigabitEthernet0/0/1        up    up       5.29%  3.37%          0          0
GigabitEthernet0/0/2        up    up       0.61%  0.48%          0          0
GigabitEthernet0/0/3        up    up       0.01%  0.01%          0          0
GigabitEthernet0/0/4        up    up       0.46%  2.06%          0          0
GigabitEthernet0/0/5        down  down        0%     0%          0          0
GigabitEthernet0/0/6        down  down        0%     0%          0          0
GigabitEthernet0/0/7        down  down        0%     0%          0          0
GigabitEthernet0/0/8        down  down        0%     0%          0          0
GigabitEthernet0/0/9        down  down        0%     0%          0          0
GigabitEthernet0/0/10       down  down        0%     0%          0          0
GigabitEthernet0/0/11       down  down        0%     0%          0          0
GigabitEthernet0/0/12       down  down        0%     0%          0          0
GigabitEthernet0/0/13       down  down        0%     0%          0          0
GigabitEthernet0/0/14       down  down        0%     0%          0          0
GigabitEthernet0/0/15       down  down        0%     0%          0          0
GigabitEthernet0/0/16       down  down        0%     0%          0          0
GigabitEthernet0/0/17       down  down        0%     0%          0          0
GigabitEthernet0/0/18       down  down        0%     0%          0          0
GigabitEthernet0/0/19       down  down        0%     0%          0          0
GigabitEthernet0/0/20       down  down        0%     0%          0          0
GigabitEthernet0/0/21       down  down        0%     0%          0          0
GigabitEthernet0/0/22       down  down        0%     0%          0          0
GigabitEthernet0/0/23       down  down        0%     0%          0          0
GigabitEthernet0/0/24       up    up       5.95%  6.40%        232          0
MEth0/0/1                   down  down        0%     0%          0          0
NULL0                       up    up(s)       0%     0%          0          0
Vlanif1                     *down down        --     --          0          0
Vlanif1000                  up    up          --     --          0          0""", 
'screen-length 0 temporary':  'screen-length 0 temporary\nInfo: The configuration takes effect on the current user terminal interface only.\n', 
## 'display version'
'display version': """display version
Huawei Versatile Routing Platform Software
VRP (R) software, Version 5.70 (S5300 V100R005C01SPC100)
Copyright (C) 2000-2011 HUAWEI TECH CO., LTD
Quidway S5328C-EI-24S Routing Switch uptime is 0 week, 5 days, 19 hours, 56 minutes

EFGF 0(Master) : uptime is 0 week, 5 days, 19 hours, 55 minutes
256M bytes DDR Memory
32M bytes FLASH
Pcb      Version :  VER B
Basic  BOOTROM  Version :  107 Compiled at Jan 18 2011, 22:52:53
CPLD   Version : 69 
Software Version : VRP (R) Software, Version 5.70 (S5300 V100R005C01SPC100)
FANCARD information
Pcb      Version : FAN VER B
PWRCARD I information
Pcb      Version : PWR VER A""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
