# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## DLink.DFL.get_arp test
## Auto-generated by ./noc debug-script at 06.07.2012 12:46:48
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class DLink_DFL_get_arp_Test(ScriptTestCase):
    script = "DLink.DFL.get_arp"
    vendor = "DLink"
    platform = "DFL-210"
    version = "2.27.00.14-14093"
    input = {}
    result = [{'interface': 'lan', 'ip': '192.168.1.2', 'mac': '00:00:00:00:00:00'}]
    motd = ''
    cli = {
## 'arp'
'arp': """arp
ARP cache of iface lan
  Reslvng 192.168.1.2      = 00-00-00-00-00-00   Expire=1
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
