# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Alcatel.AOS.get_portchannel test
## Auto-generated by ./noc debug-script at 24.01.2013 16:40:59
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Alcatel_AOS_get_portchannel_Test(ScriptTestCase):
    script = "Alcatel.AOS.get_portchannel"
    vendor = "Alcatel"
    platform = "OS6850-U24X"
    version = "6.4.4.343.R01"
    input = {}
    result = [{'interface': 'Ag 1', 'members': ['1/4', '1/5'], 'type': 'L'},
 {'interface': 'Ag 2', 'members': [], 'type': 'L'}]
    motd = ''
    cli = {
## 'show linkagg 2 port'
'show linkagg 2 port': """show linkagg 2 port

Slot/Port Aggregate SNMP Id   Status   Agg  Oper Link Prim Standby
---------+---------+-------+----------+----+----+----+----+-------""", 
## 'show linkagg'
'show linkagg': """show linkagg

                                  Min                                           
Number  Aggregate  SNMP Id   Size Size Admin State  Oper State     Att/Sel Ports
-------+----------+---------+----+----+------------+--------------+-------------
   1     Static    40000001   4    1   ENABLED      DOWN            0   2
   2     Dynamic   40000002   8    1   ENABLED      DOWN            0   0""", 
## 'show linkagg 1 port'
'show linkagg 1 port': """show linkagg 1 port

Slot/Port Aggregate SNMP Id   Status   Agg  Oper Link Prim Standby
---------+---------+-------+----------+----+----+----+----+-------
   1/4    Static      1004  SELECTED     1  DOWN DOWN NO   NO
   1/5    Static      1005  SELECTED     1  DOWN DOWN NO   NO""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
