# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Juniper.JUNOS.get_version test
## Auto-generated by ./noc debug-script at 2012-01-25 02:53:13
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Juniper_JUNOS_get_version_Test(ScriptTestCase):
    script = "Juniper.JUNOS.get_version"
    vendor = "Juniper"
    platform = 'ex4200-24t'
    version = '10.4R6.5'
    input = {}
    result = {'platform': 'ex4200-24t', 'vendor': 'Juniper', 'version': '10.4R6.5'}
    motd = ''
    cli = {
## 'set cli screen-length 0'
'set cli screen-length 0': """ set cli screen-length 0 
Screen length set to 0

{master:0}""", 
## 'show version'
'show version': """ show version 
fpc0:
--------------------------------------------------------------------------
Hostname: x13-core
Model: ex4200-24t
JUNOS Base OS boot [10.4R6.5]
JUNOS Base OS Software Suite [10.4R6.5]
JUNOS Kernel Software Suite [10.4R6.5]
JUNOS Crypto Software Suite [10.4R6.5]
JUNOS Online Documentation [10.4R6.5]
JUNOS Enterprise Software Suite [10.4R6.5]
JUNOS Packet Forwarding Engine Enterprise Software Suite [10.4R6.5]
JUNOS Routing Software Suite [10.4R6.5]
JUNOS Web Management [10.4R6.5]

fpc1:
--------------------------------------------------------------------------
Hostname: x13-core
Model: ex4200-24t
JUNOS Base OS boot [10.4R6.5]
JUNOS Base OS Software Suite [10.4R6.5]
JUNOS Kernel Software Suite [10.4R6.5]
JUNOS Crypto Software Suite [10.4R6.5]
JUNOS Online Documentation [10.4R6.5]
JUNOS Enterprise Software Suite [10.4R6.5]
JUNOS Packet Forwarding Engine Enterprise Software Suite [10.4R6.5]
JUNOS Routing Software Suite [10.4R6.5]
JUNOS Web Management [10.4R6.5]
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
