# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Juniper.JUNOS.get_version test
## Auto-generated by manage.py debug-script at 2010-09-29 01:50:22
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Juniper_JUNOS_get_version_Test(ScriptTestCase):
    script="Juniper.JUNOS.get_version"
    vendor="Juniper"
    platform='srx650'
    version='10.3R1.9'
    input={}
    result={'platform': 'srx650', 'vendor': 'Juniper', 'version': '10.3R1.9'}
    motd=' \n--- JUNOS 10.3R1.9 built 2010-08-13 13:07:06 UTC\n'
    cli={
'set cli screen-length 0':  ' set cli screen-length 0 \nScreen length set to 0\n\n',
## 'show version'
'show version': """ show version 
Model: srx650
JUNOS Software Release [10.3R1.9]
""",
}
    snmp_get={}
    snmp_getnext={}
