# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## DLink.DxS_Cisco_CLI.get_lldp_neighbors test
## Auto-generated by ./noc debug-script at 19.07.2012 16:07:58
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class DLink_DxS_Cisco_CLI_get_lldp_neighbors_Test(ScriptTestCase):
    script = "DLink.DxS_Cisco_CLI.get_lldp_neighbors"
    vendor = "DLink"
    platform = "DGS-3610-26G"
    version = "10.3(5T16)"
    input = {}
    result = [{'local_interface': 'Gi 0/1',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:15:FA:74',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:15:FA:7D',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'GO_8'}]},
 {'local_interface': 'Gi 0/2',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:1E:97:20',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:1E:97:29',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'GO_43'}]},
 {'local_interface': 'Gi 0/3',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:56:BE:85',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:56:BE:8F',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'GO_35'}]},
 {'local_interface': 'Gi 0/4',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:15:FE:B4',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:15:FE:BD',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'GO_28'}]},
 {'local_interface': 'Gi 0/5',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:56:BE:B5',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:56:BE:BE',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'IN_67'}]},
 {'local_interface': 'Gi 0/6',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:16:00:E4',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:16:00:ED',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'IN_76'}]},
 {'local_interface': 'Gi 0/8',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:1C:F0:5B:24:00',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '24',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'VC_10'}]},
 {'local_interface': 'Gi 0/9',
  'neighbors': [{'remote_capabilities': 6,
                 'remote_chassis_id': '1C:BD:B9:9B:8B:5C',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '17',
                 'remote_port_subtype': 7,
                 'remote_system_name': 'BM_13'}]},
 {'local_interface': 'Gi 0/13',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:1E:97:70',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:1E:97:7A',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'KI_16'}]},
 {'local_interface': 'Gi 0/15',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:56:C3:65',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:56:C3:6E',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'LI_25'}]},
 {'local_interface': 'Gi 0/16',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:12:CF:F3:E0:06',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '00:12:CF:F3:E0:0F',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'LI_40'}]},
 {'local_interface': 'Gi 0/17',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '70:72:CF:15:FE:44',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '70:72:CF:15:FE:4D',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'S_3'}]},
 {'local_interface': 'Gi 0/18',
  'neighbors': [{'remote_capabilities': 6,
                 'remote_chassis_id': '1C:BD:B9:9B:9A:5C',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '17',
                 'remote_port_subtype': 7,
                 'remote_system_name': 'S_42'}]},
 {'local_interface': 'Gi 0/20',
  'neighbors': [{'remote_capabilities': 4,
                 'remote_chassis_id': '00:12:CF:F3:DE:D6',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '00:12:CF:F3:DE:E0',
                 'remote_port_subtype': 3,
                 'remote_system_name': 'GU_25'}]},
 {'local_interface': 'Gi 0/21',
  'neighbors': [{'remote_capabilities': 128,
                 'remote_chassis_id': '00:15:17:91:80:8C',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': 'em0',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'nas-1.localhost.com.ua.'}]},
 {'local_interface': 'Gi 0/22',
  'neighbors': [{'remote_capabilities': 20,
                 'remote_chassis_id': '00:12:CF:74:F9:21',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '24',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'ES4626'}]},
 {'local_interface': 'Gi 0/23',
  'neighbors': [{'remote_capabilities': 128,
                 'remote_chassis_id': '00:15:17:B8:FD:0C',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': 'em0',
                 'remote_port_subtype': 5,
                 'remote_system_name': 'nas-4.localhost.com.ua.'}]},
 {'local_interface': 'Te 1/1',
  'neighbors': [{'remote_capabilities': 20,
                 'remote_chassis_id': '00:E0:B1:88:7A:B8',
                 'remote_chassis_id_subtype': 4,
                 'remote_port': '1025',
                 'remote_port_subtype': 7,
                 'remote_system_name': 'Alcatel6850'}]}]
    motd = ''
    cli = {
## 'show lldp neighbor-information'
'show lldp neighbor-information': """show lldp neighbor-information
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/1]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 31minute 19second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf15.fa74
  System name                       : GO_8
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.10.2
  Interface numbering subtype       : ifIndex
  Interface number                  : 1080
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf15.fa7d
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 80
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 80              : vlan80
  VLAN name of VLAN 81              : vlan81
  VLAN name of VLAN 82              : vlan82
  VLAN name of VLAN 83              : vlan83
  VLAN name of VLAN 84              : vlan84
  VLAN name of VLAN 85              : vlan85
  VLAN name of VLAN 86              : vlan86
  VLAN name of VLAN 87              : vlan87
  VLAN name of VLAN 88              : vlan88
  VLAN name of VLAN 89              : vlan89
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/2]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 41minute 55second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf1e.9720
  System name                       : GO_43
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.10.66
  Interface numbering subtype       : ifIndex
  Interface number                  : 1090
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf1e.9729
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 90
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 90              : vlan90
  VLAN name of VLAN 91              : vlan91
  VLAN name of VLAN 92              : vlan92
  VLAN name of VLAN 93              : vlan93
  VLAN name of VLAN 94              : vlan94
  VLAN name of VLAN 95              : vlan95
  VLAN name of VLAN 96              : vlan96
  VLAN name of VLAN 97              : vlan97
  VLAN name of VLAN 98              : vlan98
  VLAN name of VLAN 99              : vlan99
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/3]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 20day 12hour 53minute 53second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf56.be85
  System name                       : GO_35
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.10.130
  Interface numbering subtype       : ifIndex
  Interface number                  : 1100
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf56.be8f
  Port description                  : Ethernet Port on unit 0, port 10

  802.1 organizationally information
  Port VLAN ID                      : 100
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 1               : DefaultVlan
  VLAN name of VLAN 100             : vlan100
  VLAN name of VLAN 101             : vlan101
  VLAN name of VLAN 102             : vlan102
  VLAN name of VLAN 103             : vlan103
  VLAN name of VLAN 104             : vlan104
  VLAN name of VLAN 105             : vlan105
  VLAN name of VLAN 106             : vlan106
  VLAN name of VLAN 107             : vlan107
  VLAN name of VLAN 108             : vlan108
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/4]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 41minute 53second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf15.feb4
  System name                       : GO_28
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.10.194
  Interface numbering subtype       : ifIndex
  Interface number                  : 1110
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf15.febd
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 110
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 110             : vlan110
  VLAN name of VLAN 111             : vlan111
  VLAN name of VLAN 112             : vlan112
  VLAN name of VLAN 113             : vlan113
  VLAN name of VLAN 114             : vlan114
  VLAN name of VLAN 115             : vlan115
  VLAN name of VLAN 116             : vlan116
  VLAN name of VLAN 117             : vlan117
  VLAN name of VLAN 118             : vlan118
  VLAN name of VLAN 119             : vlan119
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/5]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 3minute 52second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf56.beb5
  System name                       : IN_67
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.11.2
  Interface numbering subtype       : ifIndex
  Interface number                  : 1120
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf56.bebe
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 120
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 1               : DefaultVlan
  VLAN name of VLAN 120             : vlan120
  VLAN name of VLAN 121             : vlan121
  VLAN name of VLAN 122             : vlan122
  VLAN name of VLAN 123             : vlan123
  VLAN name of VLAN 124             : vlan124
  VLAN name of VLAN 125             : vlan125
  VLAN name of VLAN 126             : vlan126
  VLAN name of VLAN 127             : vlan127
  VLAN name of VLAN 128             : vlan128
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/6]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 43minute 53second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf16.00e4
  System name                       : IN_76
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.11.66
  Interface numbering subtype       : ifIndex
  Interface number                  : 1130
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf16.00ed
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 130
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 130             : vlan130
  VLAN name of VLAN 131             : vlan131
  VLAN name of VLAN 132             : vlan132
  VLAN name of VLAN 133             : vlan133
  VLAN name of VLAN 134             : vlan134
  VLAN name of VLAN 135             : vlan135
  VLAN name of VLAN 136             : vlan136
  VLAN name of VLAN 137             : vlan137
  VLAN name of VLAN 138             : vlan138
  VLAN name of VLAN 139             : vlan139
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/8]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 21day 23hour 59minute 2second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 001c.f05b.2400
  System name                       : VC_10
  System description                : DGS-3100-24 Gigabit stackable L2 Managed Switch
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.16.2
  Interface numbering subtype       : ifIndex
  Interface number                  : 100029
  Object identifier                 : 


  Port ID type                      : Interface name
  Port ID                           : 1:24
  Port description                  : Ethernet Interface

  802.1 organizationally information
  Port VLAN ID                      : 
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name                         : 
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : YES
  Auto-negotiation enabled          : YES
  PMD auto-negotiation advertised   : 1000BASE-T full duplex mode
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/9]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 8hour 7minute 31second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 1cbd.b99b.8b5c
  System name                       : BM_13
  System description                : Fast Ethernet Switch
  System capabilities supported     : Repeater, Bridge
  System capabilities enabled       : Repeater, Bridge


  Port ID type                      : Locally assigned
  Port ID                           : 1/17
  Port description                  : D-Link DES-3200-18 R1.60 Port 17

  802.1 organizationally information
  Port VLAN ID                      : 360
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name of VLAN 360             : 360
  VLAN name of VLAN 361             : 361
  VLAN name of VLAN 362             : 362
  VLAN name of VLAN 363             : 363
  VLAN name of VLAN 364             : 364
  VLAN name of VLAN 365             : 365
  VLAN name of VLAN 366             : 366
  VLAN name of VLAN 367             : 367
  VLAN name of VLAN 368             : 368
  VLAN name of VLAN 369             : 369
  VLAN name of VLAN 370             : 370
  VLAN name of VLAN 371             : 371
  VLAN name of VLAN 372             : 372
  VLAN name of VLAN 373             : 373
  VLAN name of VLAN 374             : 374
  VLAN name of VLAN 375             : 375
  VLAN name of VLAN 376             : 376
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/13]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 45minute 38second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf1e.9770
  System name                       : KI_16
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.12.130
  Interface numbering subtype       : ifIndex
  Interface number                  : 1250
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf1e.977a
  Port description                  : Ethernet Port on unit 0, port 10

  802.1 organizationally information
  Port VLAN ID                      : 250
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 250             : vlan250
  VLAN name of VLAN 251             : vlan251
  VLAN name of VLAN 252             : vlan252
  VLAN name of VLAN 253             : vlan253
  VLAN name of VLAN 254             : vlan254
  VLAN name of VLAN 255             : vlan255
  VLAN name of VLAN 256             : vlan256
  VLAN name of VLAN 257             : vlan257
  VLAN name of VLAN 258             : vlan258
  VLAN name of VLAN 259             : vlan259
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/15]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 5minute 6second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf56.c365
  System name                       : LI_25
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.14.66
  Interface numbering subtype       : ifIndex
  Interface number                  : 1150
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf56.c36e
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 150
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 150             : vlan150
  VLAN name of VLAN 151             : vlan151
  VLAN name of VLAN 152             : vlan152
  VLAN name of VLAN 153             : vlan153
  VLAN name of VLAN 154             : vlan154
  VLAN name of VLAN 155             : vlan155
  VLAN name of VLAN 156             : vlan156
  VLAN name of VLAN 157             : vlan157
  VLAN name of VLAN 158             : vlan158
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/16]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 47minute 2second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 0012.cff3.e006
  System name                       : LI_40
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.14.130
  Interface numbering subtype       : ifIndex
  Interface number                  : 1160
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 0012.cff3.e00f
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 160
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 160             : vlan160
  VLAN name of VLAN 161             : vlan161
  VLAN name of VLAN 162             : vlan162
  VLAN name of VLAN 163             : vlan163
  VLAN name of VLAN 164             : vlan164
  VLAN name of VLAN 165             : vlan165
  VLAN name of VLAN 166             : vlan166
  VLAN name of VLAN 167             : vlan167
  VLAN name of VLAN 168             : vlan168
  VLAN name of VLAN 1000            : vlan1000
  VLAN name of VLAN 1076            : vlan1076
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/17]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 41minute 55second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 7072.cf15.fe44
  System name                       : S_3
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.8.2
  Interface numbering subtype       : ifIndex
  Interface number                  : 1330
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 7072.cf15.fe4d
  Port description                  : Ethernet Port on unit 0, port 9

  802.1 organizationally information
  Port VLAN ID                      : 330
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 330             : vlan330
  VLAN name of VLAN 331             : vlan331
  VLAN name of VLAN 332             : vlan332
  VLAN name of VLAN 333             : vlan333
  VLAN name of VLAN 334             : vlan334
  VLAN name of VLAN 335             : vlan335
  VLAN name of VLAN 336             : vlan336
  VLAN name of VLAN 337             : vlan337
  VLAN name of VLAN 338             : vlan338
  VLAN name of VLAN 339             : vlan339
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/18]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 8hour 3minute 48second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 1cbd.b99b.9a5c
  System name                       : S_42
  System description                : Fast Ethernet Switch
  System capabilities supported     : Repeater, Bridge
  System capabilities enabled       : Repeater, Bridge


  Port ID type                      : Locally assigned
  Port ID                           : 1/17
  Port description                  : D-Link DES-3200-18 R1.60 Port 17

  802.1 organizationally information
  Port VLAN ID                      : 10
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name of VLAN 2               : 2
  VLAN name of VLAN 3               : 3
  VLAN name of VLAN 4               : 4
  VLAN name of VLAN 5               : 5
  VLAN name of VLAN 6               : 6
  VLAN name of VLAN 7               : 7
  VLAN name of VLAN 8               : 8
  VLAN name of VLAN 9               : 9
  VLAN name of VLAN 10              : 10
  VLAN name of VLAN 350             : 350
  VLAN name of VLAN 351             : 351
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/20]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 9day 7hour 41minute 53second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 0012.cff3.ded6
  System name                       : GU_25
  System description                : ES3510MA
  System capabilities supported     : Bridge
  System capabilities enabled       : Bridge

  Management address subtype        : ipv4
  Management address                : 10.200.15.130
  Interface numbering subtype       : ifIndex
  Interface number                  : 1210
  Object identifier                 : 


  Port ID type                      : MAC address
  Port ID                           : 0012.cff3.dee0
  Port description                  : Ethernet Port on unit 0, port 10

  802.1 organizationally information
  Port VLAN ID                      : 210
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : YES
      PPVID Enabled                 : NO
  VLAN name of VLAN 210             : vlan210
  VLAN name of VLAN 211             : vlan211
  VLAN name of VLAN 212             : vlan212
  VLAN name of VLAN 213             : vlan213
  VLAN name of VLAN 214             : vlan214
  VLAN name of VLAN 215             : vlan215
  VLAN name of VLAN 216             : vlan216
  VLAN name of VLAN 217             : vlan217
  VLAN name of VLAN 218             : vlan218
  VLAN name of VLAN 219             : vlan219
  VLAN name of VLAN 1000            : vlan1000
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/21]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 1minute 59second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 0015.1791.808c
  System name                       : nas-1.localhost.com.ua.
  System description                : amd64/FreeBSD 7.4-RELEASE
  System capabilities supported     : Station Only
  System capabilities enabled       : Station Only

  Management address subtype        : ipv4
  Management address                : 10.100.110.61
  Interface numbering subtype       : system port number
  Interface number                  : 16777216
  Object identifier                 : 


  Port ID type                      : Interface name
  Port ID                           : em0
  Port description                  : em0

  802.1 organizationally information
  Port VLAN ID                      : 
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name                         : 
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/22]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 2minute 2second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 0012.cf74.f921
  System name                       : ES4626
  System description                : ES4626 Device, Compiled Aug 17 18:18:36 2010
 SoftWare Version Vco.6.1.83.3
 BootRom Version 2.0.14
 HardWare Version R02
 Device serial number DCKD0747000038
 Copyright (C) 2001-2007 by Accton Technology Corp.
 All rights reserved

  System capabilities supported     : Bridge, Router
  System capabilities enabled       : Bridge, Router


  Port ID type                      : Interface name
  Port ID                           : Ethernet1/24
  Port description                  : Ethernet1/24

  802.1 organizationally information
  Port VLAN ID                      : 
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name                         : 
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [GigabitEthernet 0/23]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 13hour 3minute 21second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 0015.17b8.fd0c
  System name                       : nas-4.localhost.com.ua.
  System description                : amd64/FreeBSD 8.2-STABLE
  System capabilities supported     : Station Only
  System capabilities enabled       : Station Only

  Management address subtype        : ipv4
  Management address                : 10.100.110.64
  Interface numbering subtype       : system port number
  Interface number                  : 16777216
  Object identifier                 : 


  Port ID type                      : Interface name
  Port ID                           : em0
  Port description                  : em0

  802.1 organizationally information
  Port VLAN ID                      : 
  Port and protocol VLAN ID(PPVID)  : 
      PPVID Supported               : 
      PPVID Enabled                 : 
  VLAN name                         : 
  Protocol Identity                 : 


  802.3 organizationally information
  Auto-negotiation supported        : 
  Auto-negotiation enabled          : 
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : 
----------------------------------------------------------------------------
Lldp neighbor-information of port [TenGigabitEthernet 1/1]
----------------------------------------------------------------------------
  Neighbor index                    : 1
  Device type                       : LLDP Device
  Update time                       : 13day 16hour 57minute 54second 

  Chassis ID type                   : MAC address
  Chassis ID                        : 00e0.b188.7ab8
  System name                       : Alcatel6850
  System description                : Alcatel-Lucent OS6850-U24X 6.4.4.343.R01 GA, June 23, 2011.
  System capabilities supported     : Bridge, Router
  System capabilities enabled       : Bridge, Router

  Management address subtype        : ipv4
  Management address                : 10.201.114.1
  Interface numbering subtype       : ifIndex
  Interface number                  : 13600121
  Object identifier                 : 


  Port ID type                      : Locally assigned
  Port ID                           : 1025
  Port description                  : Alcatel-Lucent 1/25

  802.1 organizationally information
  Port VLAN ID                      : 1011
  Port and protocol VLAN ID(PPVID)  : 0
      PPVID Supported               : NO
      PPVID Enabled                 : NO
  VLAN name of VLAN 1011            : vlan1011
  Protocol Identity (index = 1   )  : 
  0x88 0xcc 


  802.3 organizationally information
  Auto-negotiation supported        : NO
  Auto-negotiation enabled          : NO
  PMD auto-negotiation advertised   : 
  Operational MAU type              : 
  PoE support                       : NO
  Link aggregation supported        : 
  Link aggregation enabled          : 
  Aggregation port ID               : 
  Maximum frame Size                : """, 
'terminal length 0':  'terminal length 0\n', 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
