# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## DLink.DxS_Cisco_CLI.get_switchport test
## Auto-generated by manage.py debug-script at 2011-02-10 14:34:55
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class DLink_DxS_Cisco_CLI_get_switchport_Test(ScriptTestCase):
    script="DLink.DxS_Cisco_CLI.get_switchport"
    vendor="DLink"
    platform='DGS-3610-26G'
    version='10.3(5T16)'
    input={}
    result=[{'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/1',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/2',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/3',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/4',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/5',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/6',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/7',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/8',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/9',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/10',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/11',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/12',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/13',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/14',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/15',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/16',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/17',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/18',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/19',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/20',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/21',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/22',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': True,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/23',
  'members': [],
  'status': True,
  'tagged': [2, 3],
  'untagged': 2},
 {'802.1Q Enabled': False,
  '802.1ad Tunnel': False,
  'interface': 'Gi 0/24',
  'members': [],
  'status': True,
  'tagged': [],
  'untagged': 1},
 {'802.1Q Enabled': True,
  '802.1ad Tunnel': False,
  'interface': 'Ag 1',
  'members': ['Gi 0/1', 'Gi 0/2'],
  'status': True,
  'tagged': [2, 3],
  'untagged': 1}]
    motd='\n\n'
    cli={
## 'show interfaces switchport'
'show interfaces switchport': """show interfaces switchport
Interface                Switchport Mode      Access Native Protected VLAN lists
------------------------ ---------- --------- ------ ------ --------- ----------
GigabitEthernet 0/1      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/2      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/3      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/4      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/5      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/6      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/7      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/8      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/9      enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/10     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/11     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/12     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/13     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/14     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/15     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/16     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/17     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/18     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/19     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/20     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/21     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/22     enabled    ACCESS    1      1      Disabled  ALL
GigabitEthernet 0/23     enabled    TRUNK     1      2      Disabled  2-3
GigabitEthernet 0/24     enabled    ACCESS    1      1      Disabled  ALL
AggregatePort 1          enabled    TRUNK     1      1      Disabled  2-3""",
'show interfaces status | i AggregatePort':  'show interfaces status | i AggregatePort\nAggregatePort 1          down      1     Unknown  Unknown   fiber\n',
'terminal length 0':  'terminal length 0\n',
'show interfaces AggregatePort 1 | i Link Status:':  'show interfaces AggregatePort 1 | i Link Status:\n        GigabitEthernet 0/1 Link Status: Down\n        GigabitEthernet 0/2 Link Status: Down\n',
}
    snmp_get={}
    snmp_getnext={}
