# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Dell.Powerconnect62xx.get_vlans test
## Auto-generated by ./noc debug-script at 16.01.2013 15:23:44
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Dell_Powerconnect_get_vlans_Test(ScriptTestCase):
    script = "Dell.Powerconnect62xx.get_vlans"
    vendor = "Dell"
    platform = "PCT6224"
    version = "3.2.0.7"
    input = {}
    result = [{'name': 'Default', 'vlan_id': 1},
 {'name': 'itm-lab', 'vlan_id': 504},
 {'name': 'DHCP', 'vlan_id': 1141}]
    motd = ''
    cli = {
## 'show vlan'
'show vlan': """show vlan

VLAN       Name                         Ports          Type      Authorization
-----  ---------------                  -------------  -----     -------------
1      Default                          ch1-48,        Default   Required     
                                        1/g2-1/g22,
                                        1/xg3-1/xg4
504    itm-lab                          1/g23-1/g24    Static    Required     
1141   DHCP                             1/g1,          Static    Required     
                                        1/g23-1/g24
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
