# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Dell.Powerconnect62xx.get_chassis_id test
## Auto-generated by ./noc debug-script at 16.01.2013 15:20:53
##----------------------------------------------------------------------
## Copyright (C) 2007-2013 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Dell_Powerconnect_get_chassis_id_Test(ScriptTestCase):
    script = "Dell.Powerconnect62xx.get_chassis_id"
    vendor = "Dell"
    platform = "PCT6224"
    version = "3.2.0.7"
    input = {}
    result = {'first_chassis_mac': 'A4:BA:DB:5D:D4:D8',
 'last_chassis_mac': 'A4:BA:DB:5D:D4:D8'}
    motd = ''
    cli = {
## 'show tech-support'
'show tech-support': """show tech-support

 ***************** Show Version ******************

Switch: 1

System Description............................. Powerconnect 6224, 3.2.0.7
                                                VxWorks 6.5
Machine Type................................... Powerconnect 6224
Machine Model.................................. PCT6224
Serial Number.................................. CN0RN8562829801P0188A11
FRU Number..................................... 
Part Number.................................... BCM56314
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... A4BA.DB5D.D4D8
Software Version............................... 3.2.0.7
Operating System............................... VxWorks 6.5
Network Processing Device...................... BCM56314_A0
Additional Packages............................ FASTPATH QOS
                                                FASTPATH Multicast
                                                FASTPATH Stacking
                                                FASTPATH Routing
 or (q)uit                     

 ***************** Show SysInfo ******************

System Location................................ 
System Contact................................. 
System Object ID............................... 1.3.6.1.4.1.674.10895.3010
System Up Time................................. 24 days 12 hrs 18 mins 2 secs
10/100 Ethernet/802.3 interface(s)............. 1
Gig Ethernet/802.3 interface(s)................ 0
10Gig Ethernet/802.3 interface(s).............. 0
Virtual Ethernet/802.3 interface(s)............ 0

MIBs Supported:


 or (q)uit                     
RFC 1907 - SNMPv2-MIB              The MIB module for SNMPv2 entities
RFC 2819 - RMON-MIB                Remote Network Monitoring Management 
                                   Information Base
Broadcom-REF-MIB                   Broadcom Reference
SNMP-COMMUNITY-MIB                 This MIB module defines objects to help 
                                   support coexistence between SNMPv1, SNMPv2, 
                                   and SNMPv3.
SNMP-FRAMEWORK-MIB                 The SNMP Management Architecture MIB
SNMP-MPD-MIB                       The MIB for Message Processing and 
                                   Dispatching
SNMP-NOTIFICATION-MIB              The Notification MIB Module
SNMP-TARGET-MIB                    The Target MIB Module
SNMP-USER-BASED-SM-MIB             The management information definitions for 
                                   the SNMP User-based Security Model.
SNMP-VIEW-BASED-ACM-MIB            The management information definitions for 
                                   the View-based Access Control Model for SNMP.
USM-TARGET-TAG-MIB                 SNMP Research, Inc.
FASTPATH-POWER-ETHERNET-MIB        Fastpath Power Ethernet Extensions MIB
POWER-ETHERNET-MIB                 Power Ethernet MIB
SFLOW-MIB                          sFlow MIB
FASTPATH-ISDP-MIB                  Industry Standard Discovery Protocol MIB


 or (q)uit                     
LAG-MIB                            The Link Aggregation module for managing 
                                   IEEE 802.3ad
RFC 1213 - RFC1213-MIB             Management Information Base for Network 
                                   Management of TCP/IP-based internets: MIB-II
RFC 1493 - BRIDGE-MIB              Definitions of Managed Objects for Bridges 
                                   (dot1d)
RFC 2674 - P-BRIDGE-MIB            The Bridge MIB Extension module for managing 
                                   Priority and Multicast Filtering, defined by 
                                   IEEE 802.1D-1998.
RFC 2674 - Q-BRIDGE-MIB            The VLAN Bridge MIB module for managing 
                                   Virtual Bridged Local Area Networks
RFC 2737 - ENTITY-MIB              Entity MIB (Version 2)
RFC 2863 - IF-MIB                  The Interfaces Group MIB using SMIv2
RFC 3635 - Etherlike-MIB           Definitions of Managed Objects for the 
                                   Ethernet-like Interface Types
FASTPATH-SWITCHING-MIB             FASTPATH Switching - Layer 2
FASTPATH-INVENTORY-MIB             Unit and Slot configuration.
FASTPATH-PORTSECURITY-PRIVATE-MIB  Port Security MIB.
IEEE8021-PAE-MIB                   Port Access Entity module for managing IEEE 
                                   802.1X.
FASTPATH-RADIUS-AUTH-CLIENT-MIB    Broadcom FastPath Radius MIB


 or (q)uit                     
RADIUS-ACC-CLIENT-MIB              RADIUS Accounting Client MIB
RADIUS-AUTH-CLIENT-MIB             RADIUS Authentication Client MIB
FASTPATH-CAPTIVE-PORTAL-MIB        FastPath Captive Portal MIB
FASTPATH-MGMT-SECURITY-MIB         The Broadcom Private MIB for FastPath Mgmt 
                                   Security
IANA-ADDRESS-FAMILY-NUMBERS-MIB    The MIB module defines the 
                                   AddressFamilyNumbers textual convention.
RFC 1724 - RIPv2-MIB               RIP Version 2 MIB Extension
RFC 1850 - OSPF-MIB                OSPF Version 2 Management Information Base
RFC 1850 - OSPF-TRAP-MIB           The MIB module to describe traps for the 
                                   OSPF Version 2 Protocol.
RFC 2787 - VRRP-MIB                Definitions of Managed Objects for the 
                                   Virtual Router Redundancy Protocol
FASTPATH-ROUTING-MIB               FASTPATH Routing - Layer 3
FASTPATH-QOS-MIB                   FASTPATH Flex QOS Support
FASTPATH-QOS-ACL-MIB               FASTPATH Flex QOS ACL
FASTPATH-QOS-COS-MIB               FASTPATH Flex QOS COS
FASTPATH-QOS-AUTOVOIP-MIB          FASTPATH Flex QOS VOIP
RFC 3289 - DIFFSERV-DSCP-TC        Management Information Base for the Textual 
                                   Conventions used in DIFFSERV-MIB
RFC 3289 - DIFFSERV-MIB            Management Information Base for the 
                                   Differentiated Services Architecture

 or (q)uit                     
FASTPATH-QOS-DIFFSERV-EXTENSIONS-  FASTPATH Flex QOS DiffServ Private MIBs' 
MIB                                definitions
FASTPATH-QOS-DIFFSERV-PRIVATE-MIB  FASTPATH Flex QOS DiffServ Private MIBs' 
                                   definitions
RFC 2932 - IPMROUTE-MIB            IPv4 Multicast Routing MIB
draft-ietf-magma-mgmd-mib-03       MGMD MIB, includes IGMPv3 and MLDv2.
RFC 2934 - PIM-MIB                 Protocol Independent Multicast MIB for IPv4
DVMRP-STD-MIB                      Distance-Vector Multicast Routing Protocol 
                                   MIB
IANA-RTPROTO-MIB                   IANA IP Route Protocol and IP MRoute 
                                   Protocol Textual Conventions
FASTPATH-NSF-MIB                   The MIB module defines objects to configure 
                                   Non Stop Forwarding.
RFC 2465 - IPV6-MIB                Management Information Base for IP Version 
                                   6: Textual Conventions and General Group
RFC 2466 - IPV6-ICMP-MIB           Management Information Base for IP Version 
                                   6: ICMPv6 Group
RFC 3419 - TRANSPORT-ADDRESS-MIB   Textual Conventions for Transport Addresses
FASTPATH-ROUTING6-MIB              The Broadcom Private MIB for FastPath Ipv6 
                                   Routing

 or (q)uit                     


        Management    Standby    Preconfig     Plugged-in         Switch          Code  
Switch    Switch      Status     Model ID      Model ID           Status         Version
------ ------------ ------------- ------------- --------------------- --------
1      Mgmt Switch  PCT6224       PCT6224       OK                    3.2.0.7 

 or (q)uit                     

 ***************** Show Port All *****************

               Admin   Physical   Physical   Link   Link    LACP  
 Intf   Type    Mode    Mode       Status   Status  Trap    Mode  
------ ------ ------- ---------- ---------- ------ ------- -------
1/g1          Enable  Auto       100 Full   Up     Enable  Disable 
1/g2          Enable  Auto                  Down   Enable  Disable 
1/g3          Enable  Auto                  Down   Enable  Disable 
1/g4          Enable  Auto                  Down   Enable  Disable 
1/g5          Enable  Auto                  Down   Enable  Disable 
1/g6          Enable  Auto                  Down   Enable  Disable 
1/g7          Enable  Auto                  Down   Enable  Disable 
1/g8          Enable  Auto                  Down   Enable  Disable 
1/g9          Enable  Auto                  Down   Enable  Disable 
1/g10         Enable  Auto                  Down   Enable  Disable 
1/g11         Enable  Auto                  Down   Enable  Disable 
1/g12         Enable  Auto                  Down   Enable  Disable 
1/g13         Enable  Auto                  Down   Enable  Disable 
1/g14         Enable  Auto                  Down   Enable  Disable 
1/g15         Enable  Auto                  Down   Enable  Disable 
1/g16         Enable  Auto                  Down   Enable  Disable 
1/g17         Enable  Auto                  Down   Enable  Disable 
1/g18         Enable  Auto                  Down   Enable  Disable 

 or (q)uit                     

               Admin   Physical   Physical   Link   Link    LACP  
 Intf   Type    Mode    Mode       Status   Status  Trap    Mode  
------ ------ ------- ---------- ---------- ------ ------- -------
1/g19         Enable  Auto                  Down   Enable  Disable 
1/g20         Enable  Auto                  Down   Enable  Disable 
1/g21         Enable  Auto                  Down   Enable  Disable 
1/g22         Enable  Auto                  Down   Enable  Disable 
1/g23         Enable  Auto                  Down   Enable  Disable 
1/g24         Enable  Auto                  Down   Enable  Disable 
1/xg1         Enable  Auto                  Detach Enable  Disable 
1/xg2         Enable  Auto                  Detach Enable  Disable 
1/xg3         Enable  Auto                  Down   Enable  Disable 
1/xg4         Enable  Auto                  Down   Enable  Disable 
ch1           Enable                        Down   Disable Disable 
ch2           Enable                        Down   Disable Disable 
ch3           Enable                        Down   Disable Disable 
ch4           Enable                        Down   Disable Disable 
ch5           Enable                        Down   Disable Disable 
ch6           Enable                        Down   Disable Disable 
ch7           Enable                        Down   Disable Disable 
ch8           Enable                        Down   Disable Disable 

 or (q)uit                     

               Admin   Physical   Physical   Link   Link    LACP  
 Intf   Type    Mode    Mode       Status   Status  Trap    Mode  
------ ------ ------- ---------- ---------- ------ ------- -------
ch9           Enable                        Down   Disable Disable 
ch10          Enable                        Down   Disable Disable 
ch11          Enable                        Down   Disable Disable 
ch12          Enable                        Down   Disable Disable 
ch13          Enable                        Down   Disable Disable 
ch14          Enable                        Down   Disable Disable 
ch15          Enable                        Down   Disable Disable 
ch16          Enable                        Down   Disable Disable 
ch17          Enable                        Down   Disable Disable 
ch18          Enable                        Down   Disable Disable 
ch19          Enable                        Down   Disable Disable 
ch20          Enable                        Down   Disable Disable 
ch21          Enable                        Down   Disable Disable 
ch22          Enable                        Down   Disable Disable 
ch23          Enable                        Down   Disable Disable 
ch24          Enable                        Down   Disable Disable 
ch25          Enable                        Down   Disable Disable 
ch26          Enable                        Down   Disable Disable 

 or (q)uit                     

               Admin   Physical   Physical   Link   Link    LACP  
 Intf   Type    Mode    Mode       Status   Status  Trap    Mode  
------ ------ ------- ---------- ---------- ------ ------- -------
ch27          Enable                        Down   Disable Disable 
ch28          Enable                        Down   Disable Disable 
ch29          Enable                        Down   Disable Disable 
ch30          Enable                        Down   Disable Disable 
ch31          Enable                        Down   Disable Disable 
ch32          Enable                        Down   Disable Disable 
ch33          Enable                        Down   Disable Disable 
ch34          Enable                        Down   Disable Disable 
ch35          Enable                        Down   Disable Disable 
ch36          Enable                        Down   Disable Disable 
ch37          Enable                        Down   Disable Disable 
ch38          Enable                        Down   Disable Disable 
ch39          Enable                        Down   Disable Disable 
ch40          Enable                        Down   Disable Disable 
ch41          Enable                        Down   Disable Disable 
ch42          Enable                        Down   Disable Disable 
ch43          Enable                        Down   Disable Disable 
ch44          Enable                        Down   Disable Disable 

 or (q)uit                     

               Admin   Physical   Physical   Link   Link    LACP  
 Intf   Type    Mode    Mode       Status   Status  Trap    Mode  
------ ------ ------- ---------- ---------- ------ ------- -------
ch45          Enable                        Down   Disable Disable 
ch46          Enable                        Down   Disable Disable 
ch47          Enable                        Down   Disable Disable 
ch48          Enable                        Down   Disable Disable 
 or (q)uit                     

 ***************** Show Isdp Neighbors *****************

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf    Holdtime  Capability   Platform             Port ID               
---------------------- ------- --------- ------------ -------------------- ----------------------


 or (q)uit                     

 ***************** Show Logging ******************

Logging Client Local Port           : 514
CLI Command Logging                 : disabled
Console Logging                     : enabled
Console Logging Severity Filter     : warning
Buffered Logging                    : enabled
Persistent Logging                  : disabled
Persistent Logging Severity Filter  : error
Syslog Logging                      : enabled
Log Messages Received               : 436
Log Messages Dropped                : 40
Log Messages Relayed                : 0
 Event Log
 ---------

 or (q)uit                     
                                                                           Time
       File                             Line TaskID   Code             d  h  m  s

EVENT> bootos.c                          222 0F
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13506  1 24 37
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13502  1 19  3
EVENT> unitmgr.c                        5629 062D2D10 00000000      13502  1 36 44
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13502  1 18 33
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13502  1 18  3
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13194  8 44 27
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13194  8 29 37
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      13194  8 13 33
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      12924  0 35 47
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      12895  8 10  1
EVENT> unitmgr.c                        5629 08432B50 00000000      12895  8 10 37
EVENT> bootos.c                          222 0FFFFD20 AAAAAAAA      12895  8  8 53

 or (q)uit                     

Buffered (In-Memory) Logging        : enabled
Buffered Logging Wrapping Behavior  : On
Buffered Log Count                  : 35

<186> FEB 19 19:55:33 0.0.0.0-1 UNKN[268434720]: bootos.c(222) 1 %% Event(0xaaaaaaaa)
<189> FEB 19 19:55:33 0.0.0.0-1 UNKN[268434720]: bootos.c(239) 2 %% Starting code... BSP initialization complete, starting system application.
<190> FEB 19 19:56:01 172.17.100.200-1 UNITMGR[108254400]: unitmgr.c(6352) 294 %% No Potential unit to configure as Standby when unit 1 joined
<188> FEB 19 19:56:01 172.17.100.200-1 UNITMGR[138620896]: unitmgr.c(2240) 299 %% Power On Start complete on unit 1
<189> FEB 19 19:57:00 172.17.100.200-1 TRAPMGR[111117808]: traputil.c(611) 300 %% Cold Start: Unit: 0
<189> FEB 19 19:57:01 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 301 %% Unit 1 is the new stack master, Old stack master unit is 0


 or (q)uit                     
<189> FEB 19 19:57:01 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 303 %% Link Up: 1/0/23
<189> FEB 19 19:57:01 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 304 %% Link Up: 1/0/24
<189> FEB 19 19:57:01 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 305 %% Entity Database: Configuration Changed
<189> FEB 19 22:42:16 172.17.100.200-1 TRAPMGR[227642080]: traputil.c(611) 306 %% Temperature change alarm: Sensor ID: 0 Event: 1
<189> FEB 19 22:42:16 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 307 %% Temperature of unit 1 has exceeded the device specific limit
<189> FEB 20 03:56:00 172.17.100.200-1 TRAPMGR[227642080]: traputil.c(611) 308 %% Temperature change alarm: Sensor ID: 0 Event: 3
<190> MAR 16 05:35:46 172.17.100.200-1 USER_MGR[103960320]: user_mgr.c(1401) 309 %% User admin Failed to login because of authentication failures
<189> MAR 16 05:35:46 172.17.100.200-1 TRAPMGR[103960320]: traputil.c(611) 310 %% Failed User Login: Unit: 1 User ID: admin
<189> MAR 16 05:35:46 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 311 %% An invalid user tried to login through CLI from 192.168.2.127


 or (q)uit                     
<189> MAR 16 05:38:15 172.17.100.200-1 TRAPMGR[150806608]: traputil.c(611) 313 %% Link Up: VLAN- 1141
<190> MAR 16 05:47:07 81.94.165.50-1 NIM[103960320]: nim_intf_map_api.c(505) 418 %% NIM: out of bounds usp used U=0, S=0 P=0
<190> MAR 16 05:47:13 81.94.165.50-1 NIM[103960320]: nim_intf_map_api.c(505) 419 %% NIM: out of bounds usp used U=0, S=0 P=0
<189> MAR 16 05:48:42 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 420 %% Link Down: VLAN- 1141
<189> MAR 16 05:48:42 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 421 %% Link on VLAN- 1141 is failed
<189> MAR 16 05:50:37 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 424 %% Link Down: 1/0/23
<189> MAR 16 05:50:37 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 425 %% Link on 1/0/23 is failed
<189> MAR 16 05:50:38 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 426 %% Link Down: 1/0/24
<189> MAR 16 05:50:38 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 427 %% Link on 1/0/24 is failed


 or (q)uit                     
<190> MAR 16 05:52:52 81.94.165.50-1 USER_MGR[103960320]: user_mgr.c(1401) 429 %% User admin Failed to login because of authentication failures
<189> MAR 16 05:52:52 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 430 %% Failed User Login: Unit: 1 User ID: admin
<189> MAR 16 05:52:52 81.94.165.50-1 TRAPMGR[150806608]: traputil.c(611) 431 %% An invalid user tried to login through CLI from 81.94.161.4
<189> MAR 16 07:26:07 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 432 %% Multiple Users: Unit: 0 Slot: 5 Port: 1
<189> MAR 16 07:43:45 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 433 %% Multiple Users: Unit: 0 Slot: 5 Port: 1
<189> MAR 16 07:45:08 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 434 %% Multiple Users: Unit: 0 Slot: 5 Port: 1
<189> MAR 16 07:48:45 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 435 %% Multiple Users: Unit: 0 Slot: 5 Port: 1
<189> MAR 16 07:49:15 81.94.165.50-1 TRAPMGR[103960320]: traputil.c(611) 436 %% Multiple Users: Unit: 0 Slot: 5 Port: 1


 or (q)uit                     

Number of Traps Since Last Reset............... 27
Trap Log Capacity.............................. 256
Number of Traps Since Log Last Viewed.......... 0

Log System Up Time           Trap
--- ------------------------ -------------------------------------------------
  0 24 days 11:53:46         
                             Multiple Users: Unit: 0 Slot: 5 Port: 1         
  1 24 days 11:53:16         Multiple Users: Unit: 0 Slot: 5 Port: 1         
  2 24 days 11:49:39         Multiple Users: Unit: 0 Slot: 5 Port: 1         
  3 24 days 11:48:16         Multiple Users: Unit: 0 Slot: 5 Port: 1         
  4 24 days 11:30:38         Multiple Users: Unit: 0 Slot: 5 Port: 1         
  5 24 days 09:57:23         An invalid user tried to login through CLI from 
                             81.94.161.4                                     
  6 24 days 09:57:23         Failed User Login: Unit: 1 User ID: admin       
  7 24 days 09:56:11         Link Up: 1/0/1                                  
  8 24 days 09:55:09         Link on 1/0/24 is failed                        
  9 24 days 09:55:09         Link Down: 1/0/24                               
 10 24 days 09:55:08         Link on 1/0/23 is failed                        

 or (q)uit                     


Log System Up Time           Trap
--- ------------------------ -------------------------------------------------
 11 24 days 09:55:08         
                             Link Down: 1/0/23                               
 12 24 days 09:53:13         Link on VLAN- 1141 is failed                    
 13 24 days 09:53:13         Link Down: VLAN- 1141                           
 14 24 days 09:42:46         Link Up: VLAN- 1141                             
 15 24 days 09:42:46         Link Up: VLAN- 1141                             
 16 24 days 09:40:17         An invalid user tried to login through CLI from 
                             192.168.2.127                                   
 17 24 days 09:40:17         Failed User Login: Unit: 1 User ID: admin       
 18 0 days 08:00:31          Temperature change alarm: Sensor ID: 0 Event: 3 
 19 0 days 02:46:47          Temperature of unit 1 has exceeded the device   
                             specific limit                                  
 20 0 days 02:46:47          Temperature change alarm: Sensor ID: 0 Event: 1 
 21 0 days 00:01:32          Entity Database: Configuration Changed          
 22 0 days 00:01:32          Link Up: 1/0/24                                 
 23 0 days 00:01:32          Link Up: 1/0/23                                 

 or (q)uit                     


Log System Up Time           Trap
--- ------------------------ -------------------------------------------------
 24 0 days 00:01:32          
                             Power On Start has completed on unit 1.         
 25 0 days 00:01:32          Unit 1 is the new stack master, Old stack master 
                             unit is 0                                       
 26 0 days 00:01:31          Cold Start: Unit: 0                             

 or (q)uit                     

 ***************** Show Running Config ***********
!Current Configuration:
!System Description "Powerconnect 6224, 3.2.0.7, VxWorks 6.5"
!System Software Version 3.2.0.7
!Cut-through mode is configured as disabled
!
configure
vlan database
vlan 504,1141
exit
hostname "dell_6224"
stack
member 1 1
exit
ip address 81.94.165.50 255.255.255.192
ip default-gateway 81.94.165.1
ip address vlan 1141
interface vlan 504
name "itm-lab"
exit
interface vlan 1141
name "DHCP"

 or (q)uit                     
exit
username "admin" password 6253e1406b64bbe6ba7b00ac0bf81257 level 15 encrypted
no spanning-tree
!
interface ethernet 1/g1
switchport access vlan 1141
exit
!
interface ethernet 1/g23
switchport mode trunk
switchport trunk allowed vlan add 504,1141
exit
!
interface ethernet 1/g24
switchport mode trunk
switchport trunk allowed vlan add 504,1141
exit
snmp-server community private rw
snmp-server community public ro
enable password 6253e1406b64bbe6ba7b00ac0bf81257 encrypted
exit

 or (q)uit                     

 or (q)uit                     

Console Break-in Status........................ Enable

 or (q)uit                     

 ***************Show Debugging****************

SIP packet tracing disabled.
H323 packet tracing disabled.
SCCP packet tracing disabled.
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
