# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## EdgeCore.ES.get_vlans test
## Auto-generated by manage.py debug-script at 2011-03-17 12:03:52
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class EdgeCore_ES_get_vlans_Test(ScriptTestCase):
    script="EdgeCore.ES.get_vlans"
    vendor="EdgeCore"
    platform='ES3526XA-V2'
    version='1.1.0.29'
    input={}
    result=[{'name': 'DefaultVlan', 'vlan_id': 1},
 {'name': 'seg128-67', 'vlan_id': 104},
 {'name': 'manag', 'vlan_id': 900},
 {'name': '', 'vlan_id': 4093}]
    motd=' \n\n      CLI session with the ES3526XA is opened.\n      To end the CLI session, enter [Exit].\n\n'
    cli={
}
    snmp_get={}
    snmp_getnext={'1.3.6.1.2.1.17.7.1.4.2.1.3': [('1.3.6.1.2.1.17.7.1.4.2.1.3.0.1', '1'),
                                ('1.3.6.1.2.1.17.7.1.4.2.1.3.0.104', '104'),
                                ('1.3.6.1.2.1.17.7.1.4.2.1.3.0.900', '900'),
                                ('1.3.6.1.2.1.17.7.1.4.2.1.3.0.4093', '4093')],
 '1.3.6.1.2.1.17.7.1.4.3.1.1': [('1.3.6.1.2.1.17.7.1.4.3.1.1.1',
                                 'DefaultVlan'),
                                ('1.3.6.1.2.1.17.7.1.4.3.1.1.104',
                                 'seg128-67'),
                                ('1.3.6.1.2.1.17.7.1.4.3.1.1.900', 'manag'),
                                ('1.3.6.1.2.1.17.7.1.4.3.1.1.4093', '')]}
