# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## EdgeCore.ES.get_interface_status test
## Auto-generated by manage.py debug-script at 2011-03-04 21:58:41
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class EdgeCore_ES_get_interface_status_Test(ScriptTestCase):
    script="EdgeCore.ES.get_interface_status"
    vendor="EdgeCore"
    platform='ES3510'
    version='1.1.0.26'
    input={}
    result=[{'interface': 'Eth 1/1', 'status': True},
 {'interface': 'Eth 1/2', 'status': True},
 {'interface': 'Eth 1/3', 'status': False},
 {'interface': 'Eth 1/4', 'status': True},
 {'interface': 'Eth 1/5', 'status': True},
 {'interface': 'Eth 1/6', 'status': False},
 {'interface': 'Eth 1/7', 'status': True},
 {'interface': 'Eth 1/8', 'status': True},
 {'interface': 'Eth 1/9', 'status': True},
 {'interface': 'Eth 1/10', 'status': False},
 {'interface': 'VLAN900', 'status': True},
 {'interface': 'Console45', 'status': True},
 {'interface': 'VLAN101', 'status': True},
 {'interface': 'VLAN27', 'status': True},
 {'interface': 'VLAN1', 'status': True},
 {'interface': 'VLAN4093', 'status': True}]
    motd=' \n\n      CLI session with the ES3510 is opened.\n      To end the CLI session, enter [Exit].\n\n'
    cli={
}
    snmp_get={}
    snmp_getnext={'1.3.6.1.2.1.2.2.1.8': [('1.3.6.1.2.1.2.2.1.8.1', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.2', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.3', '7'),
                         ('1.3.6.1.2.1.2.2.1.8.4', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.5', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.6', '7'),
                         ('1.3.6.1.2.1.2.2.1.8.7', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.8', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.9', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.10', '7'),
                         ('1.3.6.1.2.1.2.2.1.8.45', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.1001', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.1027', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.1101', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.1900', '1'),
                         ('1.3.6.1.2.1.2.2.1.8.5093', '1')],
 '1.3.6.1.2.1.31.1.1.1.1': [('1.3.6.1.2.1.31.1.1.1.1.1', 'Port1'),
                            ('1.3.6.1.2.1.31.1.1.1.1.2', 'Port2'),
                            ('1.3.6.1.2.1.31.1.1.1.1.3', 'Port3'),
                            ('1.3.6.1.2.1.31.1.1.1.1.4', 'Port4'),
                            ('1.3.6.1.2.1.31.1.1.1.1.5', 'Port5'),
                            ('1.3.6.1.2.1.31.1.1.1.1.6', 'Port6'),
                            ('1.3.6.1.2.1.31.1.1.1.1.7', 'Port7'),
                            ('1.3.6.1.2.1.31.1.1.1.1.8', 'Port8'),
                            ('1.3.6.1.2.1.31.1.1.1.1.9', 'Port9'),
                            ('1.3.6.1.2.1.31.1.1.1.1.10', 'Port10'),
                            ('1.3.6.1.2.1.31.1.1.1.1.45', 'Console45'),
                            ('1.3.6.1.2.1.31.1.1.1.1.1001', 'VLAN1'),
                            ('1.3.6.1.2.1.31.1.1.1.1.1027', 'VLAN27'),
                            ('1.3.6.1.2.1.31.1.1.1.1.1101', 'VLAN101'),
                            ('1.3.6.1.2.1.31.1.1.1.1.1900', 'VLAN900'),
                            ('1.3.6.1.2.1.31.1.1.1.1.5093', 'VLAN4093')]}
