# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## EdgeCore.ES.get_chassis_id test
## Auto-generated by manage.py debug-script at 2010-11-26 18:34:59
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class EdgeCore_ES_get_chassis_id_Test(ScriptTestCase):
    script="EdgeCore.ES.get_chassis_id"
    vendor="EdgeCore"
    platform='ES4626-SFP'
    version='6.0.220.33'
    input={}
    result='00:12:CF:A3:CA:EC'
    motd='********\n'
    cli={
## 'show version 1'
'show version 1': """show version 1
  ES4626-SFP Device, Compiled on Apr 23 14:41:49 2010
  SoftWare Version ES4626-SFP_6.0.220.33
  BootRom Version ES4626-SFP_1.7.0
  HardWare Version 3.0
  Copyright (C) 2001-2007 by Accton Technology Corp.
  All rights reserved
  Uptime is 10 weeks, 4 days, 4 hours, 47 minutes""",
## 'show mac-address-table static'
'show mac-address-table static': """show mac-address-table static
Read mac address table....
Vlan Mac Address                 Type    Creator   Ports
---- --------------------------- ------- -------------------------------------
100  00-12-cf-a3-ca-ec           STATIC  System   CPU
101  00-12-cf-a3-ca-ec           STATIC  System   CPU
102  00-12-cf-a3-ca-ec           STATIC  System   CPU
103  00-12-cf-a3-ca-ec           STATIC  System   CPU
104  00-12-cf-a3-ca-ec           STATIC  System   CPU
105  00-12-cf-a3-ca-ec           STATIC  System   CPU
106  00-12-cf-a3-ca-ec           STATIC  System   CPU
107  00-12-cf-a3-ca-ec           STATIC  System   CPU
108  00-12-cf-a3-ca-ec           STATIC  System   CPU
109  00-12-cf-a3-ca-ec           STATIC  System   CPU
110  00-12-cf-a3-ca-ec           STATIC  System   CPU
111  00-12-cf-a3-ca-ec           STATIC  System   CPU
112  00-12-cf-a3-ca-ec           STATIC  System   CPU
113  00-12-cf-a3-ca-ec           STATIC  System   CPU
114  00-12-cf-a3-ca-ec           STATIC  System   CPU
115  00-12-cf-a3-ca-ec           STATIC  System   CPU
116  00-12-cf-a3-ca-ec           STATIC  System   CPU
117  00-12-cf-a3-ca-ec           STATIC  System   CPU
118  00-12-cf-a3-ca-ec           STATIC  System   CPU
119  00-12-cf-a3-ca-ec           STATIC  System   CPU
814  00-12-cf-a3-ca-ec           STATIC  System   CPU
815  00-12-cf-a3-ca-ec           STATIC  System   CPU
816  00-12-cf-a3-ca-ec           STATIC  System   CPU
817  00-12-cf-a3-ca-ec           STATIC  System   CPU
818  00-12-cf-a3-ca-ec           STATIC  System   CPU
819  00-12-cf-a3-ca-ec           STATIC  System   CPU
900  00-12-cf-a3-ca-ec           STATIC  System   CPU""",
## 'show system'
'show system': """show system
                             ^
% Invalid input detected at '^' marker.
""",
}
    snmp_get={}
    snmp_getnext={}
