# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## EdgeCore.ES.get_interface_status test
## Auto-generated by ./noc debug-script at 01.08.2012 17:02:26
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class EdgeCore_ES_get_interface_status_Test(ScriptTestCase):
    script = "EdgeCore.ES.get_interface_status"
    vendor = "EdgeCore"
    platform = "ES3528M"
    version = "1.3.7.10"
    input = {}
    result = [{'interface': 'Eth 1/1', 'mac': '00:12:CF:E6:DB:C1', 'status': True},
 {'interface': 'Eth 1/2', 'mac': '00:12:CF:E6:DB:C2', 'status': False},
 {'interface': 'Eth 1/3', 'mac': '00:12:CF:E6:DB:C3', 'status': False},
 {'interface': 'Eth 1/4', 'mac': '00:12:CF:E6:DB:C4', 'status': False},
 {'interface': 'Eth 1/5', 'mac': '00:12:CF:E6:DB:C5', 'status': False},
 {'interface': 'Eth 1/6', 'mac': '00:12:CF:E6:DB:C6', 'status': False},
 {'interface': 'Eth 1/7', 'mac': '00:12:CF:E6:DB:C7', 'status': False},
 {'interface': 'Eth 1/8', 'mac': '00:12:CF:E6:DB:C8', 'status': False},
 {'interface': 'Eth 1/9', 'mac': '00:12:CF:E6:DB:C9', 'status': False},
 {'interface': 'Eth 1/10', 'mac': '00:12:CF:E6:DB:CA', 'status': False},
 {'interface': 'Eth 1/11', 'mac': '00:12:CF:E6:DB:CB', 'status': False},
 {'interface': 'Eth 1/12', 'mac': '00:12:CF:E6:DB:CC', 'status': False},
 {'interface': 'Eth 1/13', 'mac': '00:12:CF:E6:DB:CD', 'status': False},
 {'interface': 'Eth 1/14', 'mac': '00:12:CF:E6:DB:CE', 'status': False},
 {'interface': 'Eth 1/15', 'mac': '00:12:CF:E6:DB:CF', 'status': False},
 {'interface': 'Eth 1/16', 'mac': '00:12:CF:E6:DB:D0', 'status': False},
 {'interface': 'Eth 1/17', 'mac': '00:12:CF:E6:DB:D1', 'status': False},
 {'interface': 'Eth 1/18', 'mac': '00:12:CF:E6:DB:D2', 'status': False},
 {'interface': 'Eth 1/19', 'mac': '00:12:CF:E6:DB:D3', 'status': False},
 {'interface': 'Eth 1/20', 'mac': '00:12:CF:E6:DB:D4', 'status': False},
 {'interface': 'Eth 1/21', 'mac': '00:12:CF:E6:DB:D5', 'status': False},
 {'interface': 'Eth 1/22', 'mac': '00:12:CF:E6:DB:D6', 'status': False},
 {'interface': 'Eth 1/23', 'mac': '00:12:CF:E6:DB:D7', 'status': False},
 {'interface': 'Eth 1/24', 'mac': '00:12:CF:E6:DB:D8', 'status': False},
 {'interface': 'Eth 1/25', 'mac': '00:12:CF:E6:DB:D9', 'status': False},
 {'interface': 'Eth 1/26', 'mac': '00:12:CF:E6:DB:DA', 'status': True},
 {'interface': 'Eth 1/27', 'mac': '00:12:CF:E6:DB:DB', 'status': False},
 {'interface': 'Eth 1/28', 'mac': '00:12:CF:E6:DB:DC', 'status': True},
 {'interface': 'VLAN 1', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 3', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 15', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 125', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 126', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 4000', 'mac': '00:12:CF:E6:DB:C0', 'status': True},
 {'interface': 'VLAN 4093', 'mac': '00:12:CF:E6:DB:C0', 'status': True}]
    motd = ''
    cli = {
## 'show version'
'show version': """show version
Unit 1
 Serial Number:           943001549
 Hardware Version:        R01
 Chip Device ID:          Marvell 98DX106-B0, 88E6095[F]
 EPLD Version:            0.07
 Number of Ports:         28
 Main Power Status:       Up
 Redundant Power Status:  Not present

Agent (Master)
 Unit ID:                 1
 Loader Version:          1.0.2.0
 Boot ROM Version:        1.2.0.1
 Operation Code Version:  1.3.7.10
""", 
'terminal length 0':  'terminal length 0\n', 
## 'show interface status'
'show interface status': """show interface status
Information of Eth 1/1
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C1
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Up
  Port Operation Status:  Up
  Operation Speed-duplex: 100full
  Port Uptime:            0w  0d  1h   34m  32s (5672 seconds)
  Flow Control Type:      None

Information of Eth 1/2
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C2
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/3
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C3
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/4
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C4
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/5
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C5
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/6
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C6
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/7
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C7
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/8
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C8
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/9
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-C9
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/10
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CA
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/11
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CB
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/12
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CC
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/13
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CD
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/14
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CE
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/15
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-CF
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/16
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D0
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/17
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D1
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/18
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D2
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/19
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D3
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/20
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D4
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/21
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D5
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/22
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D6
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/23
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D7
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/24
 Basic Information: 
  Port Type:              100TX
  Mac Address:            00-12-CF-E6-DB-D8
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             None
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 100full
  Flow Control Type:      None

Information of Eth 1/25
 Basic Information: 
  Port Type:              1000T
  Mac Address:            00-12-CF-E6-DB-D9
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           10half, 10full, 100half, 100full, 1000full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  VLAN Trunking:          Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             SFP preferred auto
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 1000full
  Flow Control Type:      None

Information of Eth 1/26
 Basic Information: 
  Port Type:              1000Base SFP
  Mac Address:            00-12-CF-E6-DB-DA
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           1000full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  VLAN Trunking:          Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             SFP preferred auto
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Up
  Port Operation Status:  Up
  Operation Speed-duplex: 1000full
  Port Uptime:            0w  1d  0h   11m  52s (87112 seconds)
  Flow Control Type:      None

Information of Eth 1/27
 Basic Information: 
  Port Type:              1000Base SFP
  Mac Address:            00-12-CF-E6-DB-DB
 Configuration: 
  Name:                   
  Port Admin:             Down
  Speed-duplex:           Auto
  Capabilities:           1000full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  VLAN Trunking:          Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             SFP preferred auto
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Down
  Operation Speed-duplex: 1000full
  Flow Control Type:      None

Information of Eth 1/28
 Basic Information: 
  Port Type:              1000Base SFP
  Mac Address:            00-12-CF-E6-DB-DC
 Configuration: 
  Name:                   
  Port Admin:             Up
  Speed-duplex:           Auto
  Capabilities:           1000full
  Broadcast Storm:        Enabled
  Broadcast Storm Limit:  64 Kbits/second
  Multicast Storm:        Disabled
  Multicast Storm Limit:  64 Kbits/second
  UnknownUnicast Storm:        Disabled
  UnknownUnicast Storm Limit:  64 Kbits/second
  Flow Control:           Disabled
  VLAN Trunking:          Disabled
  LACP:                   Disabled
  Port Security:          Disabled
  Max MAC Count:          0
  Port Security Action:   None
  Media Type:             SFP preferred auto
  Giga PHY mode: Auto preferred master
 Current Status: 
  Link Status:            Up
  Port Operation Status:  Up
  Operation Speed-duplex: 1000full
  Port Uptime:            13w  0d  15h   39m  26s (8350766 seconds)
  Flow Control Type:      None

Information of VLAN 1
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 3
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 15
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 125
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 126
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 4000
 MAC Address:             00-12-CF-E6-DB-C0

Information of VLAN 4093
 MAC Address:             00-12-CF-E6-DB-C0
""", 
## 'show system'
'show system': """show system
System Description: ES3528M
System OID String: 1.3.6.1.4.1.259.6.10.94
System Information
 System Up Time:          223 days, 20 hours, 12 minutes, and 18.43 seconds
 System Name:             EC3528M-Podvoiskogo-18-2
 System Location:         [NONE]
 System Contact:          [NONE]
 MAC Address (Unit1):     00-12-CF-E6-DB-C0
 Web Server:              Disabled
 Web Server Port:         80
 Web Secure Server:       Enabled
 Web Secure Server Port:  443
 Telnet Server:           Enable
 Telnet Server Port:      23
 Jumbo Frame:             Disabled """, 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
