# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## EdgeCore.ES.get_version test
## Auto-generated by manage.py debug-script at 2011-03-01 18:35:25
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class EdgeCore_ES_get_version_Test(ScriptTestCase):
    script="EdgeCore.ES.get_version"
    vendor="EdgeCore"
    platform='ES3510'
    version='1.1.0.29'
    input={}
    result={'platform': 'ES3510', 'vendor': 'EdgeCore', 'version': '1.1.0.29'}
    motd=' \n\n      CLI session with the ES3510 is opened.\n      To end the CLI session, enter [Exit].\n\n'
    cli={
}
    snmp_get={'1.3.6.1.2.1.1.1.0': 'Layer2+ Fast Ethernet Standalone Switch ES3510',
 '1.3.6.1.2.1.1.2.0': '(1, 3, 6, 1, 4, 1, 259, 8, 1, 5)',
 '1.3.6.1.4.1.259.8.1.5.1.1.3.1.6.1': '1.1.0.29'}
    snmp_getnext={}
