# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_version test
## Auto-generated by ./noc debug-script at 12.10.2012 17:54:09
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Cisco_IOS_get_version_Test(ScriptTestCase):
    script = "Cisco.IOS.get_version"
    vendor = "Cisco"
    platform = "C2951"
    version = "15.0(1)M5"
    input = {}
    result = {'attributes': {'image': 'C2951-UNIVERSALK9-M'},
 'platform': 'C2951',
 'vendor': 'Cisco',
 'version': '15.0(1)M5'}
    motd = ''
    cli = {
## 'show version'
'show version': """show version
Cisco IOS Software, C2951 Software (C2951-UNIVERSALK9-M), Version 15.0(1)M5, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2011 by Cisco Systems, Inc.
Compiled Wed 23-Feb-11 16:04 by prod_rel_team

ROM: System Bootstrap, Version 15.0(1r)M6, RELEASE SOFTWARE (fc1)

router04 uptime is 10 weeks, 2 days, 8 hours, 2 minutes
System returned to ROM by power-on
System restarted at 09:43:10 MSK Wed Aug 1 2012
System image file is "flash0:c2951-universalk9-mz.SPA.150-1.M5.bin"
Last reload type: Normal Reload


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco CISCO2951/K9 (revision 1.1) with 487424K/36864K bytes of memory.
Processor board ID FTX1504AT37
3 Gigabit Ethernet interfaces
1 Virtual Private Network (VPN) Module
DRAM configuration is 72 bits wide with parity enabled.
255K bytes of non-volatile configuration memory.
254464K bytes of ATA System CompactFlash 0 (Read/Write)


License Info:

License UDI:

-------------------------------------------------
Device#\t  PID\t\t\tSN
-------------------------------------------------
*0  \t  CISCO2951/K9          FTX1504AT37     



Technology Package License Information for Module:'c2951' 

----------------------------------------------------------------
Technology    Technology-package          Technology-package
              Current       Type          Next reboot  
-----------------------------------------------------------------
ipbase        ipbasek9      Permanent     ipbasek9
security      securityk9    Evaluation    securityk9
uc            None          None          None
data          None          None          None

Configuration register is 0x2102
""", 
'terminal length 0':  'terminal length 0\n', 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
