# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_version test
## Auto-generated by manage.py debug-script at 2010-09-29 01:08:16
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Cisco_IOS_get_version_Test(ScriptTestCase):
    script="Cisco.IOS.get_version"
    vendor="Cisco"
    platform='Catalyst 4500 L3 Switch'
    version='12.2(37)SG1'
    input={}
    result={'attributes': {'image': 'cat4500-IPBASEK9-M'},
 'platform': 'Catalyst 4500 L3 Switch',
 'vendor': 'Cisco',
 'version': '12.2(37)SG1'}
    motd=' \n\n'
    cli={
## 'show version'
'show version': """show version
Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500-IPBASEK9-M), Version 12.2(37)SG1, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2007 by Cisco Systems, Inc.
Compiled Mon 30-Jul-07 14:00 by prod_rel_team
Image text-base: 0x10000000, data-base: 0x1158DA3C

ROM: 12.2(31r)SG3
Pod Revision 14, Force Revision 31, Tie Revision 32

c4507eu_1 uptime is 2 years, 2 weeks, 10 hours, 56 minutes
Uptime for this control processor is 2 years, 2 weeks, 9 hours, 45 minutes
System returned to ROM by power-on
System restarted at 10:11:54 UTC Sun Sep 14 2008
System image file is "bootflash:cat4500-ipbasek9-mz.122-37.SG1.bin"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

cisco WS-C4507R (MPC8540) processor (revision 4) with 524288K bytes of memory.
Processor board ID FOX11210LG6
MPC8540 CPU at 667Mhz, Supervisor II-PLUS-10GE
Last reset from PowerUp
14 Virtual Ethernet interfaces
200 Gigabit Ethernet interfaces
4 Ten Gigabit Ethernet interfaces
511K bytes of non-volatile configuration memory.

Configuration register is 0x2101
""",
'terminal length 0':  'terminal length 0\n',
}
    snmp_get={}
    snmp_getnext={}
