# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_spanning_tree test
## Auto-generated by manage.py debug-script at 2010-10-15 18:04:38
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Cisco_IOS_get_spanning_tree_Test(ScriptTestCase):
    script="Cisco.IOS.get_spanning_tree"
    vendor="Cisco"
    platform='CBS31X0'
    version='12.2(50)SE3'
    input={}
    result={'configuration': {'MSTP': {'region': 'TI', 'revision': 0}},
 'instances': [{'bridge_id': '00:23:AB:53:1C:80',
                'bridge_priority': 32768,
                'id': 0,
                'interfaces': [{'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.5',
                                'edge': True,
                                'interface': 'Gi 1/0/5',
                                'point_to_point': True,
                                'port_id': '128.5',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.6',
                                'edge': True,
                                'interface': 'Gi 1/0/6',
                                'point_to_point': True,
                                'port_id': '128.6',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:01:E8:6D:1C:5C',
                                'designated_bridge_priority': 8192,
                                'designated_port_id': '128.25',
                                'edge': False,
                                'interface': 'Po 1',
                                'point_to_point': True,
                                'port_id': '128.256',
                                'priority': 128,
                                'role': 'root',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.264',
                                'edge': True,
                                'interface': 'Po 2',
                                'point_to_point': True,
                                'port_id': '128.264',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.272',
                                'edge': True,
                                'interface': 'Po 3',
                                'point_to_point': True,
                                'port_id': '128.272',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.280',
                                'edge': True,
                                'interface': 'Po 4',
                                'point_to_point': True,
                                'port_id': '128.280',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.288',
                                'edge': True,
                                'interface': 'Po 5',
                                'point_to_point': True,
                                'port_id': '128.288',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.296',
                                'edge': True,
                                'interface': 'Po 6',
                                'point_to_point': True,
                                'port_id': '128.296',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.304',
                                'edge': True,
                                'interface': 'Po 7',
                                'point_to_point': True,
                                'port_id': '128.304',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.312',
                                'edge': True,
                                'interface': 'Po 8',
                                'point_to_point': True,
                                'port_id': '128.312',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.320',
                                'edge': True,
                                'interface': 'Po 9',
                                'point_to_point': True,
                                'port_id': '128.320',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.328',
                                'edge': True,
                                'interface': 'Po 10',
                                'point_to_point': True,
                                'port_id': '128.328',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.336',
                                'edge': True,
                                'interface': 'Po 11',
                                'point_to_point': True,
                                'port_id': '128.336',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.344',
                                'edge': True,
                                'interface': 'Po 12',
                                'point_to_point': True,
                                'port_id': '128.344',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.352',
                                'edge': True,
                                'interface': 'Po 13',
                                'point_to_point': True,
                                'port_id': '128.352',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.360',
                                'edge': True,
                                'interface': 'Po 14',
                                'point_to_point': True,
                                'port_id': '128.360',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32768,
                                'designated_port_id': '128.34',
                                'edge': True,
                                'interface': 'Gi 2/0/6',
                                'point_to_point': True,
                                'port_id': '128.34',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'}],
                'root_id': '00:01:E8:6D:1C:5C',
                'root_priority': 8192,
                'vlans': '1,1000-4094'},
               {'bridge_id': '00:23:AB:53:1C:80',
                'bridge_priority': 32769,
                'id': 1,
                'interfaces': [{'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.5',
                                'edge': True,
                                'interface': 'Gi 1/0/5',
                                'point_to_point': True,
                                'port_id': '128.5',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.6',
                                'edge': True,
                                'interface': 'Gi 1/0/6',
                                'point_to_point': True,
                                'port_id': '128.6',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:01:E8:6D:1C:5C',
                                'designated_bridge_priority': 8193,
                                'designated_port_id': '128.25',
                                'edge': False,
                                'interface': 'Po 1',
                                'point_to_point': True,
                                'port_id': '96.256',
                                'priority': 96,
                                'role': 'root',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.264',
                                'edge': True,
                                'interface': 'Po 2',
                                'point_to_point': True,
                                'port_id': '128.264',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.272',
                                'edge': True,
                                'interface': 'Po 3',
                                'point_to_point': True,
                                'port_id': '128.272',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.280',
                                'edge': True,
                                'interface': 'Po 4',
                                'point_to_point': True,
                                'port_id': '128.280',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.288',
                                'edge': True,
                                'interface': 'Po 5',
                                'point_to_point': True,
                                'port_id': '128.288',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.296',
                                'edge': True,
                                'interface': 'Po 6',
                                'point_to_point': True,
                                'port_id': '128.296',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.304',
                                'edge': True,
                                'interface': 'Po 7',
                                'point_to_point': True,
                                'port_id': '128.304',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.312',
                                'edge': True,
                                'interface': 'Po 8',
                                'point_to_point': True,
                                'port_id': '128.312',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.320',
                                'edge': True,
                                'interface': 'Po 9',
                                'point_to_point': True,
                                'port_id': '128.320',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.328',
                                'edge': True,
                                'interface': 'Po 10',
                                'point_to_point': True,
                                'port_id': '128.328',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.336',
                                'edge': True,
                                'interface': 'Po 11',
                                'point_to_point': True,
                                'port_id': '128.336',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.344',
                                'edge': True,
                                'interface': 'Po 12',
                                'point_to_point': True,
                                'port_id': '128.344',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.352',
                                'edge': True,
                                'interface': 'Po 13',
                                'point_to_point': True,
                                'port_id': '128.352',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.360',
                                'edge': True,
                                'interface': 'Po 14',
                                'point_to_point': True,
                                'port_id': '128.360',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'},
                               {'designated_bridge_id': '00:23:AB:53:1C:80',
                                'designated_bridge_priority': 32769,
                                'designated_port_id': '128.34',
                                'edge': True,
                                'interface': 'Gi 2/0/6',
                                'point_to_point': True,
                                'port_id': '128.34',
                                'priority': 128,
                                'role': 'designated',
                                'state': 'forwarding'}],
                'root_id': '00:01:E8:6D:1C:5C',
                'root_priority': 8193,
                'vlans': '2-499'},
               {'bridge_id': '00:23:AB:53:1C:80',
                'bridge_priority': 32770,
                'id': 2,
                'interfaces': [{'designated_bridge_id': '00:01:E8:6D:1C:5C',
                                'designated_bridge_priority': 8194,
                                'designated_port_id': '128.25',
                                'edge': False,
                                'interface': 'Po 1',
                                'point_to_point': True,
                                'port_id': '160.256',
                                'priority': 160,
                                'role': 'root',
                                'state': 'forwarding'}],
                'root_id': '00:01:E8:6D:1C:5C',
                'root_priority': 8194,
                'vlans': '500-999'}],
 'mode': 'MSTP'}
    motd=' \nC\nThe system is a property of Innova Distribution LLC.\nPlease disconnect immediately if you are not authorized staff\n\n'
    cli={
## 'show spanning-tree'
'show spanning-tree': """show spanning-tree

MST0
  Spanning tree enabled protocol mstp
  Root ID    Priority    8192
             Address     0001.e86d.1c5c
             Cost        0
             Port        256 (Port-channel1)
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

  Bridge ID  Priority    32768  (priority 32768 sys-id-ext 0)
             Address     0023.ab53.1c80
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

Interface           Role Sts Cost      Prio.Nbr Type
------------------- ---- --- --------- -------- --------------------------------
Gi1/0/5             Desg FWD 20000     128.5    P2p Edge 
Gi1/0/6             Desg FWD 20000     128.6    P2p Edge 
Po1                 Root FWD 1000      128.256  P2p 
Po2                 Desg FWD 10000     128.264  P2p Edge 
Po3                 Desg FWD 10000     128.272  P2p Edge 
Po4                 Desg FWD 10000     128.280  P2p Edge 
Po5                 Desg FWD 10000     128.288  P2p Edge 
Po6                 Desg FWD 10000     128.296  P2p Edge 
Po7                 Desg FWD 10000     128.304  P2p Edge 
Po8                 Desg FWD 10000     128.312  P2p Edge 
Po9                 Desg FWD 10000     128.320  P2p Edge 
Po10                Desg FWD 10000     128.328  P2p Edge 
Po11                Desg FWD 10000     128.336  P2p Edge 
Po12                Desg FWD 10000     128.344  P2p Edge 
Po13                Desg FWD 10000     128.352  P2p Edge 
Po14                Desg FWD 10000     128.360  P2p Edge 
Gi2/0/6             Desg FWD 20000     128.34   P2p Edge 



MST1
  Spanning tree enabled protocol mstp
  Root ID    Priority    8193
             Address     0001.e86d.1c5c
             Cost        1000
             Port        256 (Port-channel1)
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

  Bridge ID  Priority    32769  (priority 32768 sys-id-ext 1)
             Address     0023.ab53.1c80
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

Interface           Role Sts Cost      Prio.Nbr Type
------------------- ---- --- --------- -------- --------------------------------
Gi1/0/5             Desg FWD 20000     128.5    P2p Edge 
Gi1/0/6             Desg FWD 20000     128.6    P2p Edge 
Po1                 Root FWD 1000       96.256  P2p 
Po2                 Desg FWD 10000     128.264  P2p Edge 
Po3                 Desg FWD 10000     128.272  P2p Edge 
Po4                 Desg FWD 10000     128.280  P2p Edge 
Po5                 Desg FWD 10000     128.288  P2p Edge 
Po6                 Desg FWD 10000     128.296  P2p Edge 
Po7                 Desg FWD 10000     128.304  P2p Edge 
Po8                 Desg FWD 10000     128.312  P2p Edge 
Po9                 Desg FWD 10000     128.320  P2p Edge 
Po10                Desg FWD 10000     128.328  P2p Edge 
Po11                Desg FWD 10000     128.336  P2p Edge 
Po12                Desg FWD 10000     128.344  P2p Edge 
Po13                Desg FWD 10000     128.352  P2p Edge 
Po14                Desg FWD 10000     128.360  P2p Edge 
Gi2/0/6             Desg FWD 20000     128.34   P2p Edge 



MST2
  Spanning tree enabled protocol mstp
  Root ID    Priority    8194
             Address     0001.e86d.1c5c
             Cost        1000
             Port        256 (Port-channel1)
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

  Bridge ID  Priority    32770  (priority 32768 sys-id-ext 2)
             Address     0023.ab53.1c80
             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec

Interface           Role Sts Cost      Prio.Nbr Type
------------------- ---- --- --------- -------- --------------------------------
Po1                 Root FWD 1000      160.256  P2p 

""",
## 'show spanning-tree mst detail'
'show spanning-tree mst detail': """show spanning-tree mst detail

##### MST0    vlans mapped:   1,1000-4094
Bridge        address 0023.ab53.1c80  priority      32768 (32768 sysid 0)
Root          address 0001.e86d.1c5c  priority      8192  (8192 sysid 0)
              port    Po1             path cost     0        
Regional Root address 0001.e86d.1c5c  priority      8192  (8192 sysid 0)
                                      internal cost 1000      rem hops 19
Operational   hello time 2 , forward delay 15, max age 20, txholdcount 6 
Configured    hello time 2 , forward delay 15, max age 20, max hops    20

GigabitEthernet1/0/5 of MST0 is designated forwarding 
Port info             port id          128.5  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id    128.5
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

GigabitEthernet1/0/6 of MST0 is designated forwarding 
Port info             port id          128.6  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id    128.6
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel1 of MST0 is root forwarding 
Port info             port id        128.256  priority    128  cost        1000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost           0
Designated bridge     address 0001.e86d.1c5c  priority   8192  port id   128.25
Timers: message expires in 4 sec, forward delay 0, forward transitions 2
Bpdus sent 8, received 736579

Port-channel2 of MST0 is designated forwarding 
Port info             port id        128.264  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.264
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel3 of MST0 is designated forwarding 
Port info             port id        128.272  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.272
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel4 of MST0 is designated forwarding 
Port info             port id        128.280  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.280
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel5 of MST0 is designated forwarding 
Port info             port id        128.288  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.288
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel6 of MST0 is designated forwarding 
Port info             port id        128.296  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.296
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel7 of MST0 is designated forwarding 
Port info             port id        128.304  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.304
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel8 of MST0 is designated forwarding 
Port info             port id        128.312  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.312
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel9 of MST0 is designated forwarding 
Port info             port id        128.320  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.320
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel10 of MST0 is designated forwarding 
Port info             port id        128.328  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.328
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel11 of MST0 is designated forwarding 
Port info             port id        128.336  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.336
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel12 of MST0 is designated forwarding 
Port info             port id        128.344  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.344
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel13 of MST0 is designated forwarding 
Port info             port id        128.352  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.352
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

Port-channel14 of MST0 is designated forwarding 
Port info             port id        128.360  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id  128.360
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus sent 0, received 0

GigabitEthernet2/0/6 of MST0 is designated forwarding 
Port info             port id         128.34  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8192  cost           0
Design. regional root address 0001.e86d.1c5c  priority   8192  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32768  port id   128.34
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
        pvst inconsistency timer expires in 20000 sec
Bpdus sent 0, received 0

##### MST1    vlans mapped:   2-499
Bridge        address 0023.ab53.1c80  priority      32769 (32768 sysid 1)
Root          address 0001.e86d.1c5c  priority      8193  (8192 sysid 1)
              port    Po1             cost          1000      rem hops 19

GigabitEthernet1/0/5 of MST1 is designated forwarding 
Port info             port id          128.5  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id    128.5
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

GigabitEthernet1/0/6 of MST1 is designated forwarding 
Port info             port id          128.6  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id    128.6
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel1 of MST1 is root forwarding 
Port info             port id         96.256  priority     96  cost        1000
Designated root       address 0001.e86d.1c5c  priority   8193  cost           0
Designated bridge     address 0001.e86d.1c5c  priority   8193  port id   128.25
Timers: message expires in 4 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 8, received 736576

Port-channel2 of MST1 is designated forwarding 
Port info             port id        128.264  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.264
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel3 of MST1 is designated forwarding 
Port info             port id        128.272  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.272
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel4 of MST1 is designated forwarding 
Port info             port id        128.280  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.280
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel5 of MST1 is designated forwarding 
Port info             port id        128.288  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.288
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel6 of MST1 is designated forwarding 
Port info             port id        128.296  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.296
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel7 of MST1 is designated forwarding 
Port info             port id        128.304  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.304
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel8 of MST1 is designated forwarding 
Port info             port id        128.312  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.312
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel9 of MST1 is designated forwarding 
Port info             port id        128.320  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.320
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel10 of MST1 is designated forwarding 
Port info             port id        128.328  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.328
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel11 of MST1 is designated forwarding 
Port info             port id        128.336  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.336
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel12 of MST1 is designated forwarding 
Port info             port id        128.344  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.344
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel13 of MST1 is designated forwarding 
Port info             port id        128.352  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.352
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

Port-channel14 of MST1 is designated forwarding 
Port info             port id        128.360  priority    128  cost       10000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id  128.360
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 0, received 0

GigabitEthernet2/0/6 of MST1 is designated forwarding 
Port info             port id         128.34  priority    128  cost       20000
Designated root       address 0001.e86d.1c5c  priority   8193  cost        1000
Designated bridge     address 0023.ab53.1c80  priority  32769  port id   128.34
Timers: message expires in 0 sec, forward delay 0, forward transitions 1
        pvst inconsistency timer expires in 20000 sec
Bpdus (MRecords) sent 0, received 0

##### MST2    vlans mapped:   500-999
Bridge        address 0023.ab53.1c80  priority      32770 (32768 sysid 2)
Root          address 0001.e86d.1c5c  priority      8194  (8192 sysid 2)
              port    Po1             cost          1000      rem hops 19

Port-channel1 of MST2 is root forwarding 
Port info             port id        160.256  priority    160  cost        1000
Designated root       address 0001.e86d.1c5c  priority   8194  cost           0
Designated bridge     address 0001.e86d.1c5c  priority   8194  port id   128.25
Timers: message expires in 4 sec, forward delay 0, forward transitions 1
Bpdus (MRecords) sent 8, received 736576
""",
'terminal length 0':  'terminal length 0\n',
## 'show spanning-tree mst configuration'
'show spanning-tree mst configuration': """show spanning-tree mst configuration
Name      [TI]
Revision  0     Instances configured 3

Instance  Vlans mapped
--------  ---------------------------------------------------------------------
0         1,1000-4094
1         2-499
2         500-999
-------------------------------------------------------------------------------""",
}
    snmp_get={}
    snmp_getnext={}
