# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_version test
## Auto-generated by ./noc debug-script at 11.10.2012 10:01:13
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Cisco_IOS_get_version_Test(ScriptTestCase):
    script = "Cisco.IOS.get_version"
    vendor = "Cisco"
    platform = "C181X"
    version = "12.4(24)T2"
    input = {}
    result = {'attributes': {'image': 'C181X-ADVENTERPRISEK9-M'},
 'platform': 'C181X',
 'vendor': 'Cisco',
 'version': '12.4(24)T2'}
    motd = ''
    cli = {
## 'show version'
'show version': """show version
Cisco IOS Software, C181X Software (C181X-ADVENTERPRISEK9-M), Version 12.4(24)T2, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2009 by Cisco Systems, Inc.
Compiled Tue 20-Oct-09 01:15 by prod_rel_team

ROM: System Bootstrap, Version 12.3(8r)YH12, RELEASE SOFTWARE (fc1)

C1812-ADL-L4 uptime is 9 weeks, 3 days, 12 hours, 35 minutes
System returned to ROM by power-on
System image file is "flash:c181x-adventerprisek9-mz.124-24.T2.bin"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco 1812 (MPC8500) processor (revision 0x400) with 354304K/38912K bytes of memory.
Processor board ID FHK114527A8, with hardware revision 0000

10 FastEthernet interfaces
1 ISDN Basic Rate interface
125952K bytes of ATA CompactFlash (Read/Write)

Configuration register is 0x2102
""", 
'terminal length 0':  'terminal length 0\n', 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
