# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_vlans test
## Auto-generated by ./noc debug-script at 08.08.2012 17:05:08
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Cisco_IOS_get_vlans_Test(ScriptTestCase):
    script = "Cisco.IOS.get_vlans"
    vendor = "Cisco"
    platform = "c3900e"
    version = "15.1(4)M4"
    input = {}
    result = [{'name': 'default', 'vlan_id': 1}]
    motd = ''
    cli = {
## 'show version'
'show version': """show version
Cisco IOS Software, C3900e Software (C3900e-UNIVERSALK9-M), Version 15.1(4)M4, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2012 by Cisco Systems, Inc.
Compiled Tue 20-Mar-12 22:07 by prod_rel_team

ROM: System Bootstrap, Version 15.1(1r)T4, RELEASE SOFTWARE (fc1)

dtln_gate uptime is 5 weeks, 4 days, 23 hours, 14 minutes
System returned to ROM by reload at 13:32:45 UTC Fri Jun 29 2012
System restarted at 13:34:08 UTC Fri Jun 29 2012
System image file is "flash:c3900e-universalk9-mz.SPA.151-4.M4.bin"
Last reload type: Normal Reload
Last reload reason: Reload Command



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco CISCO3945-CHASSIS (revision 1.0) with C3900-SPE250/K9 with 2064384K bytes of memory.
Processor board ID FCZ161220GG
4 Gigabit Ethernet interfaces
DRAM configuration is 72 bits wide with parity enabled.
256K bytes of non-volatile configuration memory.
250880K bytes of ATA System CompactFlash 0 (Read/Write)


License Info:

License UDI:

-------------------------------------------------
Device#\t  PID\t\t\tSN
-------------------------------------------------
*0  \t  C3900-SPE250/K9       FOC16014KMV     



Technology Package License Information for Module:'c3900e' 

-----------------------------------------------------------------
Technology    Technology-package           Technology-package
              Current       Type           Next reboot  
------------------------------------------------------------------
ipbase        ipbasek9      Permanent      ipbasek9
security      None          None           None
uc            None          None           None
data          None          None           None

Configuration register is 0x2102
""", 
'terminal length 0':  'terminal length 0\n', 
## 'show vlan-switch'
'show vlan-switch': """show vlan-switch

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    
1002 fddi-default                     act/unsup 
1003 token-ring-default               act/unsup 
1004 fddinet-default                  act/unsup 
1005 trnet-default                    act/unsup 

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        1002   1003
1002 fddi  101002     1500  -      -      -        -    -        1      1003
1003 tr    101003     1500  1005   0      -        -    srb      1      1002
1004 fdnet 101004     1500  -      -      1        ibm  -        0      0   
1005 trnet 101005     1500  -      -      1        ibm  -        0      0   """, 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
