# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_vlans test
## Auto-generated by ./noc debug-script at 2011-06-16 01:16:51
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class Cisco_IOS_get_vlans_Test(ScriptTestCase):
    script = "Cisco.IOS.get_vlans"
    vendor = "Cisco"
    platform = 'C3750'
    version = '12.2(35)SE2'
    input = {}
    result = [{'name': 'default', 'vlan_id': 1},
 {'name': 'SXGA_FO', 'vlan_id': 10},
 {'name': 'SXGA_FO_STATE', 'vlan_id': 11},
 {'name': 'Uplink', 'vlan_id': 50},
 {'name': 'SonicNet', 'vlan_id': 51},
 {'name': 'LisaNet', 'vlan_id': 52},
 {'name': 'Channel_Berlin', 'vlan_id': 53},
 {'name': 'SonicNeta_Inside', 'vlan_id': 71},
 {'name': 'LisaNet_Inside', 'vlan_id': 72},
 {'name': 'Area33_Inside', 'vlan_id': 73},
 {'name': 'Outside', 'vlan_id': 100},
 {'name': 'InsidePix', 'vlan_id': 101},
 {'name': 'StorageManagement', 'vlan_id': 102},
 {'name': 'NetworkManagement', 'vlan_id': 103},
 {'name': 'ADV-MGMT', 'vlan_id': 104},
 {'name': 'MegaServeMain', 'vlan_id': 105},
 {'name': 'ConsoleManagement', 'vlan_id': 106},
 {'name': 'WWWManage', 'vlan_id': 107},
 {'name': 'CPPManage', 'vlan_id': 108},
 {'name': 'DBSmanage', 'vlan_id': 109},
 {'name': 'WWW', 'vlan_id': 110},
 {'name': 'CPP', 'vlan_id': 111},
 {'name': 'DBS', 'vlan_id': 112},
 {'name': 'Main', 'vlan_id': 114},
 {'name': 'HPManage', 'vlan_id': 115},
 {'name': 'HPeth1', 'vlan_id': 116},
 {'name': 'Mail_Auth', 'vlan_id': 117},
 {'name': 'CSM', 'vlan_id': 118},
 {'name': 'CsmDNS', 'vlan_id': 119},
 {'name': 'Media', 'vlan_id': 120},
 {'name': 'CSM_Media', 'vlan_id': 121},
 {'name': 'DNS_CSM', 'vlan_id': 122},
 {'name': 'CSM_Mail', 'vlan_id': 123},
 {'name': 'XSAN_InterComm', 'vlan_id': 124},
 {'name': 'Images', 'vlan_id': 125},
 {'name': 'Scripts', 'vlan_id': 126},
 {'name': 'ImagesManage', 'vlan_id': 127},
 {'name': 'ScriptsManage', 'vlan_id': 128},
 {'name': 'CSM_Images', 'vlan_id': 129},
 {'name': 'CVS', 'vlan_id': 130},
 {'name': 'InetUsers', 'vlan_id': 131},
 {'name': 'test10', 'vlan_id': 132},
 {'name': 'MegaCluster2', 'vlan_id': 133},
 {'name': 'MegaCluster2Internal', 'vlan_id': 134},
 {'name': 'CacheImages', 'vlan_id': 135},
 {'name': 'ImagesCache2', 'vlan_id': 136},
 {'name': 'ImagesCache2_Manage', 'vlan_id': 137},
 {'name': 'MegaCluster3', 'vlan_id': 138},
 {'name': 'MegaCluster3_Internal', 'vlan_id': 139},
 {'name': 'MegaCluster3_Manage', 'vlan_id': 140},
 {'name': 'MegaCluster4', 'vlan_id': 141},
 {'name': 'MegaCluster4_Internal', 'vlan_id': 142},
 {'name': 'Scripts_2', 'vlan_id': 143},
 {'name': 'DBHelper__Manage', 'vlan_id': 144},
 {'name': 'DBHelper', 'vlan_id': 145},
 {'name': 'CPP_Big_Manage', 'vlan_id': 146},
 {'name': 'CPP_Big', 'vlan_id': 147},
 {'name': 'Mail', 'vlan_id': 148},
 {'name': 'DNS', 'vlan_id': 149},
 {'name': 'CacheManage', 'vlan_id': 150},
 {'name': 'Cache', 'vlan_id': 151},
 {'name': 'VideoManage', 'vlan_id': 152},
 {'name': 'Video', 'vlan_id': 153},
 {'name': 'MegaCluster5', 'vlan_id': 154},
 {'name': 'MegaCluster5_Internal', 'vlan_id': 155},
 {'name': 'SandBox_Manage', 'vlan_id': 156},
 {'name': 'bimages', 'vlan_id': 157},
 {'name': 'MegaCluster6', 'vlan_id': 158},
 {'name': 'MegaCluster6_Internal', 'vlan_id': 159},
 {'name': 'MegaCluster7', 'vlan_id': 160},
 {'name': 'MegaCluster7_Internal', 'vlan_id': 161},
 {'name': 'MegaCluster8', 'vlan_id': 162},
 {'name': 'MegaCluster8_Internal', 'vlan_id': 163},
 {'name': 'MegaCluster9', 'vlan_id': 164},
 {'name': 'MegaCluster9_Internal', 'vlan_id': 165},
 {'name': 'MegaCluster10', 'vlan_id': 166},
 {'name': 'MegaCluster10_Internal', 'vlan_id': 167},
 {'name': 'DoNotReply', 'vlan_id': 168},
 {'name': 'BookKeepers', 'vlan_id': 169},
 {'name': 'ClearSpace', 'vlan_id': 170},
 {'name': 'VPN Segment', 'vlan_id': 171},
 {'name': 'Sec. IP for Invite', 'vlan_id': 172},
 {'name': 'Iface for mail store', 'vlan_id': 173},
 {'name': 'SuperSecure', 'vlan_id': 174},
 {'name': 'Public access', 'vlan_id': 175},
 {'name': 'Billing', 'vlan_id': 176},
 {'name': 'CCM', 'vlan_id': 177},
 {'name': 'WWWGSA', 'vlan_id': 178},
 {'name': 'WWWGSAManage', 'vlan_id': 179},
 {'name': 'WWWBDA', 'vlan_id': 180},
 {'name': 'WWWBDAManage', 'vlan_id': 181},
 {'name': 'Partners', 'vlan_id': 182},
 {'name': 'Partners_Manage', 'vlan_id': 183},
 {'name': 'WWW_WAP', 'vlan_id': 184},
 {'name': 'WWW_WAP_Manage', 'vlan_id': 185},
 {'name': 'wwwbilling', 'vlan_id': 186},
 {'name': 'wwwbilling_manage', 'vlan_id': 187},
 {'name': 'scriptsbilling', 'vlan_id': 188},
 {'name': 'scriptsbilling_mgmt', 'vlan_id': 189},
 {'name': 'unreg', 'vlan_id': 190},
 {'name': 'unreg-manage', 'vlan_id': 191},
 {'name': 'rrd', 'vlan_id': 192},
 {'name': 'rrd-mgmt', 'vlan_id': 193},
 {'name': 'bimages-mgmt', 'vlan_id': 194},
 {'name': 'ADV', 'vlan_id': 195},
 {'name': 'Uplink_Int', 'vlan_id': 200},
 {'name': 'SonicNeta_Int', 'vlan_id': 201},
 {'name': 'LisaNet_Int', 'vlan_id': 202},
 {'name': 'Area33_Int', 'vlan_id': 203},
 {'name': 'Uplink_int', 'vlan_id': 204},
 {'name': 'Testing', 'vlan_id': 205},
 {'name': 'TestingManagement', 'vlan_id': 206}]
    motd = '\n'
    cli = {
## 'show version'
'show version': """show version
Cisco IOS Software, C3750 Software (C3750-ADVIPSERVICESK9-M), Version 12.2(35)SE2, RELEASE SOFTWARE (fc1)
Copyright (c) 1986-2007 by Cisco Systems, Inc.
Compiled Tue 06-Feb-07 05:07 by antonino
Image text-base: 0x00003000, data-base: 0x013D0448

ROM: Bootstrap program is C3750 boot loader
BOOTLDR: C3750 Boot Loader (C3750-HBOOT-M) Version 12.2(25r)SEE4, RELEASE SOFTWARE (fc1)

3750site3 uptime is 41 weeks, 2 hours, 26 minutes
System returned to ROM by power-on
System restarted at 18:47:24 UTC Wed Sep 1 2010
System image file is "flash:c3750-advipservicesk9-mz.122-35.SE2/c3750-advipservicesk9-mz.122-35.SE2.bin"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

cisco WS-C3750G-48TS (PowerPC405) processor (revision C0) with 118784K/12280K bytes of memory.
Processor board ID FCZ1103Y02M
Last reset from power-on
2 Virtual Ethernet interfaces
52 Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 00:1A:A1:FF:64:80
Motherboard assembly number     : 73-10218-08
Power supply part number        : 341-0107-01
Motherboard serial number       : FOC10511EVR
Power supply serial number      : AZS103702UH
Model revision number           : C0
Motherboard revision number     : C0
Model number                    : WS-C3750G-48TS-S
System serial number            : FCZ1103Y02M
Top Assembly Part Number        : 800-26857-01
Top Assembly Revision Number    : B0
Version ID                      : V03
CLEI Code Number                : CNMWU00ARC
Hardware Board Revision Number  : 0x09


Switch   Ports  Model              SW Version              SW Image            
------   -----  -----              ----------              ----------          
*    1   52     WS-C3750G-48TS     12.2(35)SE2             C3750-ADVIPSERVICESK


Configuration register is 0xF
""", 
'terminal length 0':  'terminal length 0\n', 
## 'show vlan brief'
'show vlan brief': """show vlan brief

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Gi1/0/14, Gi1/0/15, Gi1/0/16
                                                Gi1/0/17, Gi1/0/18, Gi1/0/19
                                                Gi1/0/20, Gi1/0/21, Gi1/0/22
                                                Gi1/0/23, Gi1/0/24, Gi1/0/25
                                                Gi1/0/26, Gi1/0/27, Gi1/0/28
                                                Gi1/0/29, Gi1/0/30, Gi1/0/31
                                                Gi1/0/32, Gi1/0/33, Gi1/0/34
                                                Gi1/0/35, Gi1/0/36, Gi1/0/37
                                                Gi1/0/38, Gi1/0/39, Gi1/0/40
                                                Gi1/0/41, Gi1/0/49, Gi1/0/50
                                                Gi1/0/51, Gi1/0/52
10   SXGA_FO                          active    
11   SXGA_FO_STATE                    active    
50   Uplink                           active    
51   SonicNet                         active    
52   LisaNet                          active    
53   Channel_Berlin                   active    
71   SonicNeta_Inside                 active    Gi1/0/2, Gi1/0/8
72   LisaNet_Inside                   active    Gi1/0/3
73   Area33_Inside                    active    
100  Outside                          active    Gi1/0/5
101  InsidePix                        active    Gi1/0/4, Gi1/0/6, Gi1/0/7
102  StorageManagement                active    Gi1/0/10, Gi1/0/11, Gi1/0/12
                                                Gi1/0/13, Gi1/0/47, Gi1/0/48
103  NetworkManagement                active    
104  ADV-MGMT                         active    
105  MegaServeMain                    active    
106  ConsoleManagement                active    
107  WWWManage                        active    
108  CPPManage                        active    
109  DBSmanage                        active    
110  WWW                              active    
111  CPP                              active    
112  DBS                              active    
114  Main                             active    
115  HPManage                         active    
116  HPeth1                           active    
117  Mail_Auth                        active    
118  CSM                              active    
119  CsmDNS                           active    
120  Media                            active    
121  CSM_Media                        active    
122  DNS_CSM                          active    
123  CSM_Mail                         active    
124  XSAN_InterComm                   active    
125  Images                           active    
126  Scripts                          active    
127  ImagesManage                     active    
128  ScriptsManage                    active    
129  CSM_Images                       active    
130  CVS                              active    
131  InetUsers                        active    
132  test10                           active    
133  MegaCluster2                     active    
134  MegaCluster2Internal             active    
135  CacheImages                      active    
136  ImagesCache2                     active    
137  ImagesCache2_Manage              active    
138  MegaCluster3                     active    
139  MegaCluster3_Internal            active    
140  MegaCluster3_Manage              active    
141  MegaCluster4                     active    
142  MegaCluster4_Internal            active    
143  Scripts_2                        active    
144  DBHelper__Manage                 active    
145  DBHelper                         active    
146  CPP_Big_Manage                   active    
147  CPP_Big                          active    
148  Mail                             active    
149  DNS                              active    
150  CacheManage                      active    
151  Cache                            active    
152  VideoManage                      active    
153  Video                            active    
154  MegaCluster5                     active    
155  MegaCluster5_Internal            active    
156  SandBox_Manage                   active    
157  bimages                          active    
158  MegaCluster6                     active    
159  MegaCluster6_Internal            active    
160  MegaCluster7                     active    
161  MegaCluster7_Internal            active    
162  MegaCluster8                     active    
163  MegaCluster8_Internal            active    
164  MegaCluster9                     active    
165  MegaCluster9_Internal            active    
166  MegaCluster10                    active    
167  MegaCluster10_Internal           active    
168  DoNotReply                       active    
169  BookKeepers                      active    
170  ClearSpace                       active    
171  VPN Segment                      active    
172  Sec. IP for Invite               active    
173  Iface for mail store             active    
174  SuperSecure                      active    
175  Public access                    active    
176  Billing                          active    
177  CCM                              active    Gi1/0/9, Gi1/0/42
178  WWWGSA                           active    
179  WWWGSAManage                     active    
180  WWWBDA                           active    
181  WWWBDAManage                     active    
182  Partners                         active    
183  Partners_Manage                  active    
184  WWW_WAP                          active    
185  WWW_WAP_Manage                   active    
186  wwwbilling                       active    
187  wwwbilling_manage                active    
188  scriptsbilling                   active    
189  scriptsbilling_mgmt              active    
190  unreg                            active    
191  unreg-manage                     active    
192  rrd                              active    
193  rrd-mgmt                         active    
194  bimages-mgmt                     active    
195  ADV                              active    
200  Uplink_Int                       active    
201  SonicNeta_Int                    active    
202  LisaNet_Int                      active    
203  Area33_Int                       active    
204  Uplink_int                       active    
205  Testing                          active    
206  TestingManagement                active    
1002 fddi-default                     act/unsup 
1003 trcrf-default                    act/unsup 
1004 fddinet-default                  act/unsup 
1005 trbrf-default                    act/unsup """, 
}
    snmp_get = {}
    snmp_getnext = {}
