# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## Cisco.IOS.get_mac_address_table test
## Auto-generated by manage.py debug-script at 2010-09-29 01:33:32
##----------------------------------------------------------------------
## Copyright (C) 2007-2010 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class Cisco_IOS_get_mac_address_table_Test(ScriptTestCase):
    script="Cisco.IOS.get_mac_address_table"
    vendor="Cisco"
    platform='Catalyst 4500 L3 Switch'
    version='12.2(37)SG1'
    input={}
    result=[
        {'mac': '00:19:E8:85:F6:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 1},
        {'mac': '00:01:D7:7B:4E:44', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 2},
        {'mac': '00:01:D7:7B:99:04', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 2},
        {'mac': '00:01:D7:81:46:11', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 2},
        {'mac': '00:14:1B:33:1C:C0', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 2},
        {'mac': '00:14:4F:9A:93:B4', 'type': 'D', 'interfaces': ['Gi 3/5'], 'vlan_id': 2},
        {'mac': '00:19:07:DA:AC:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 2},
        {'mac': '00:1C:F9:13:0C:00', 'type': 'D', 'interfaces': ['Gi 5/1'], 'vlan_id': 3},
        {'mac': '00:1C:B0:23:9E:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 3},
        {'mac': '00:19:E8:85:F6:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 5},
        {'mac': '00:1A:2F:8C:A4:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 5},
        {'mac': '00:1A:2F:8C:A4:00', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 5},
        {'mac': '00:14:1B:33:1C:C0', 'type': 'D', 'interfaces': ['Te 1/1'], 'vlan_id': 6}]
    motd=' \n\n'
    cli={
## 'show mac address-table'
'show mac address-table': """show mac address-table
Unicast Entries
 vlan   mac address     type        protocols               port
-------+---------------+--------+---------------------+--------------------
   1    0019.e885.f600   dynamic ip                    TenGigabitEthernet1/1 
   2    0001.d77b.4e44   dynamic ip                    TenGigabitEthernet1/1 
   2    0001.d77b.9904   dynamic ip                    TenGigabitEthernet1/1 
   2    0001.d781.4611   dynamic ip,other              TenGigabitEthernet1/1 
   2    0014.1b33.1cc0   dynamic assigned              TenGigabitEthernet1/1 
   2    0014.4f9a.93b4   dynamic ip,other              GigabitEthernet3/5    
   2    0019.07da.ac00   dynamic ip,assigned           TenGigabitEthernet1/1 
   3    001c.f913.0c00   dynamic other                 GigabitEthernet5/1    
   3    001c.582f.44bf    static ip,ipx,assigned,other Switch                
   3    001c.b023.9e00   dynamic ip,assigned           TenGigabitEthernet1/1 
   4    001c.582f.44bf    static ip,ipx,assigned,other Switch                
   5    0019.e885.f600   dynamic ip                    TenGigabitEthernet1/1 
   5    001a.2f8c.a400   dynamic ip                    TenGigabitEthernet1/1 
   5    001a.2f8c.a400   dynamic ip                    TenGigabitEthernet1/1 
   5    001c.582f.44bf    static ip,ipx,assigned,other Switch                
   6    0014.1b33.1cc0   dynamic ip,assigned           TenGigabitEthernet1/1 

Multicast Entries
 vlan    mac address     type    ports
-------+---------------+-------+--------------------------------------------
   1    ffff.ffff.ffff   system Te1/1
   2    ffff.ffff.ffff   system Te1/1
   3    0100.5e7f.fffd     igmp Gi3/1,Gi3/2,Gi3/3,Gi3/4,Gi5/1,Gi6/1,Gi6/2
                                Te1/1
   3    ffff.ffff.ffff   system Gi3/1,Gi3/2,Gi3/3,Gi3/4,Gi5/1,Gi6/1,Gi6/2
                                Gi7/1,Te1/1
   4    ffff.ffff.ffff   system Te1/1,Switch
   5    ffff.ffff.ffff   system Gi3/9,Gi3/16,Gi3/17,Gi3/18,Gi3/19,Gi3/20
                                Gi3/21,Gi3/22,Gi3/23,Gi3/24,Gi3/25,Gi3/26
                                Gi3/27,Gi3/28,Gi3/29,Gi3/30,Gi3/31,Gi3/32
                                Gi3/33,Gi3/34,Gi3/35,Gi3/36,Gi3/37,Gi3/38
                                Gi3/39,Gi3/41,Gi3/42,Gi3/43,Gi3/44,Gi3/45
                                Gi3/46,Te1/1
""",
'terminal length 0':  'terminal length 0\n',
}
    snmp_get={}
    snmp_getnext={}
