#!/bin/sh
#
# Service Activator daemon
#

getproparg() {
    val=`svcprop -p $1 $SMF_FMRI`
    [ -n "$val" ] && echo $val
}

if [ -z "$SMF_FMRI" ]; then
    echo "Error: SMF framework variables are not initialized"
    exit $SMF_EXIT_ERR
fi

PREFIX=`getproparg noc-activator/prefix`
PYTHON=`getproparg noc-activator/python`
PIDFILE=`getproparg noc-activator/pidfile`
LOGFILE=`getproparg noc-activator/logfile`
NAME=`getproparg noc-activator/name`
SAE_ADDRESS=`getproparg noc-activator/sae_address`
ACTIVATOR="$PREFIX/scripts/noc-activator.py"

case "$1" in
start)
    $PYTHON $ACTIVATOR -l$LOGFILE -p$PIDFILE -n$NAME -c$SAE_ADDRESS 2>&1
    ;;
stop)
    [ -f "$PIDFILE" ] && /usr/bin/kill -QUIT `/usr/bin/cat $PIDFILE` && rm -f $PIDFILE
    ;;
refresh)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|refresh}"
    exit $SMF_EXIT_ERR_CONFIG
    ;;
esac
exit $SMF_EXIT_OK