#!/bin/sh
#
# Cron daemon
#
getproparg() {
    val=`svcprop -p $1 $SMF_FMRI`
    [ -n "$val" ] && echo $val
}

if [ -z "$SMF_FMRI" ]; then
    echo "Error: SMF framework variables are not initialized"
    exit $SMF_EXIT_ERR
fi

PREFIX=`getproparg noc-cron/prefix`
PYTHON=`getproparg noc-cron/python`
PIDFILE=`getproparg noc-cron/pidfile`
LOGFILE=`getproparg noc-cron/logfile`
CRON="$PREFIX/scripts/noc-cron.py"

case "$1" in
start)
    $PYTHON $CRON -l$LOGFILE -p$PIDFILE 2>&1
    ;;
stop)
    [ -f "$PIDFILE" ] && /usr/bin/kill -QUIT `/usr/bin/cat $PIDFILE` && rm -f $PIDFILE
    ;;
refresh)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|refresh}"
    exit $SMF_EXIT_ERR_CONFIG
    ;;
esac
exit $SMF_EXIT_OK