#!/bin/sh
# Rebuild online HTML documentation from docbook xml
SRC=`dirname $0`/../share/doc/users_guide/xml/
rm $SRC/../html/*.html

cd $SRC
DOCBOOK_XSLT=`xslt-config --prefix`/share/xsl/docbook-xsl/html/chunk.xsl
XSLT_OPTIONS="--stringparam chunker.output.encoding utf-8"
XSLT_FLAGS="--xinclude --nonet $XSLT_OPTIONS -o ../html/"
xsltproc $XSLT_FLAGS $DOCBOOK_XSLT index.xml
