#!./bin/python
# ----------------------------------------------------------------------
# Fetch URL and feed to stdout
# ----------------------------------------------------------------------
# Copyright (C) 2007-2019 The NOC Project
# See LICENSE for details
# ---------------------------------------------------------------------

# Python modules
import sys
# NOC modules
from noc.core.fileutils import urlopen


def fetch(url):
    f = urlopen(url)
    print f.read()


if __name__ == "__main__":
    fetch(sys.argv[1])
