#!/bin/sh
#
#
#


getproparg() {
    val=`svcprop -p $1 $SMF_FMRI`
    [ -n "$val" ] && echo $val
}

if [ -z $SMF_FMRI ]; then
    echo "Error: SMF framework variables are not initialized"
    exit $SMF_EXIT_ERR
fi

NOCD_HOME=`getproparg nocd/prefix`
PYTHON=`getproparg nocd/python`
SOCKET=`getproparg nocd/socket`
PIDFILE=`getproparg nocd/pidfile`
MINSPARE=`getproparg nocd/minspare`
MAXSPARE=`getproparg nocd/maxspare`
MAXREQUESTS=`getproparg nocd/maxrequests`
MAXCHILDREN=`getproparg nocd/maxchildren`
NOCD="$NOCD_HOME/scripts/nocd-fastcgi.py"

case "$1" in
start)
    $PYTHON $NOCD -s$SOCKET -S$MINSPARE:$MAXSPARE -R$MAXREQUESTS -C$MAXCHILDREN -p$PIDFILE 2>&1
    ;;
stop)
    [ -f "$PIDFILE" ] && /usr/bin/kill -QUIT `/usr/bin/cat $PIDFILE`
    rm -f $SOCKET
    ;;
refresh)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|refresh}"
    exit $SMF_EXIT_ERR_CONFIG
    ;;
esac
exit $SMF_EXIT_OK