#!/bin/sh
##----------------------------------------------------------------------
## NOC post-install script
##----------------------------------------------------------------------
## Copyright (C) 2007-2009 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
PREFIX=/opt/noc

cd $PREFIX

# Copy configs and perform paths auto-discovery
sed_script=`mktemp tmp.XXXXXX`
rm $sed_script
for cmd in telnet ssh rsync pg_dump tar gzip smidump smilint fping; do
    echo "s@^\\($cmd *\\)=.*\$@"\\1= `which $cmd`"@" >> $sed_script
done

for d in etc/*.defaults; do
    conf=`echo $d|sed 's/.defaults$/.conf/'`
    sed -f $sed_script < $d > $conf
done
rm $sed_script

# Create local cache
[ ! -d "local" ] && mkdir local
[ ! -d "static/doc" ] && mkdir static/doc
chown noc:noc local static/doc

# Perform post-update to syncronize the rest
