#!/bin/sh
##----------------------------------------------------------------------
## NOC post-install script
##----------------------------------------------------------------------
## Copyright (C) 2007-2009 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
PREFIX=/opt/noc

cd $PREFIX
if [ ! -d "local" ]; then
    mkdir local
    chown noc:noc local
fi

python manage.py syncdb
python manage.py migrate
python manage.py sync-rules
