#!./bin/python
# NOC modules
from noc.lib.stomp.client import STOMPClient
from noc.lib.stomp.threadclient import ThreadedSTOMPClient
from noc.lib.debug import error_report
import time
import sys
import logging
 
STATS = []
SF = None
QUEUE = "/queue/t1"
TOPIC = "/topic/t1"

DEST = TOPIC


def callback(destination, body):
    global STATS, SF

    if body["cmd"] == "STOP":
        dt = time.time() - body["t"]
        n = body["n"]
        info = [body["polling"]]
        if body["synch"]:
            info += ["Synchronous"]
        if body["persistent"]:
            info += ["Persistent"]
        info = "[%s]" % ", ".join(info)
        print "Performance: %d messages in %s secs (%smsg/sec) %s" % (
            n, dt, n / dt, info)
        f = open(SF, "w")
        for n, dt in STATS:
            f.write("%s,%s\n" % (n, dt))
        f.close()
    elif body["cmd"] == "MESSAGE":
        dt = time.time() - body["t"]
        n = body["n"]
        STATS += [(n, dt)]


def get_client(addr, port, client_id=None, threaded=False):
    if threaded:
        return ThreadedSTOMPClient(addr, port, client_id=client_id)
    else:
        return STOMPClient(addr, port, client_id=client_id)


def main_producer(messages, synchronous=False, persistent=False,
                  threaded=False):
    client = get_client("127.0.0.1", 19705,
        client_id="producer", threaded=threaded)
    client.start()
    t0 = time.time()
    n = 0
    for i in range(messages):
        t = time.time()
        client.send({"cmd": "MESSAGE", "t": t, "n": n},
            destination=DEST, receipt=synchronous,
            persistent=persistent)
        n += 1
    client.send({"cmd": "STOP", "t": t0, "n": n,
                 "synch": synchronous,
                 "persistent": persistent,
                 "polling": client.factory.poller.__class__.__name__},
        destination=DEST, receipt=synchronous, persistent=persistent)
    client.stop()


def main_consumer(threaded=False):
    client = get_client("127.0.0.1", 19705,
        client_id="consumer", threaded=threaded)
    client.start()
    client.subscribe(DEST, callback=callback)
    client.wait()


def usage():
    print "STOMP Server Benchmark"
    print "Producer:"
    print "    %s [-v] [-s] [-P] [-Q] -p <n>" % sys.argv[0]
    print "Consumer:"
    print "    %s [-v] [-Q] -c <out>" % sys.argv[0]
    print "Where:"
    print "    -v    -- be verbose"
    print "    -s    -- synchronous messaging"
    print "    -P    -- persistent messaging"
    print "    <n>   -- generate <n> messages"
    print "   -Q     -- use queue instead of topic"
    print "   -t     -- use threaded client"
    print "    <out> -- write CSV report to file <out>"

 
if __name__ == "__main__":
    import getopt

    # Parse arguments
    is_producer = False
    verbose = False
    synchronous = False
    messages = None
    persistent = False
    threaded = False
    out = None
    optlist, optargs = getopt.getopt(sys.argv[1:], "vstPQp:c:")
    for k, v in optlist:
        if k == "-h":
            usage()
            sys.exit(0)
        if k == "-p":
            is_producer = True
            messages = int(v)
        elif k == "-P":
            persistent = True
        elif k == "-Q":
            DEST = QUEUE
        elif k == "-c":
            is_producer = False
            out = v
        elif k == "-v":
            verbose = True
        elif k == "-s":
            synchronous = True
        elif k == "-t":
            threaded = True
    # Setup logging
    if verbose:
        for h in logging.root.handlers:
             logging.root.removeHandler(h)
        logging.basicConfig(
            level=logging.DEBUG,
            format="%(asctime)s %(levelname)s %(message)s")
    # Run
    try:
        if is_producer:
            main_producer(messages=messages,
                synchronous=synchronous, persistent=persistent,
                threaded=threaded)
        else:
            SF = out
            main_consumer(threaded=threaded)
    except Exception:
        error_report()