#!/usr/bin/env python
import os,sys

if __name__=="__main__":
    d,p=os.path.split(sys.argv[0])
    sys.path.insert(0,os.path.join(d,".."))
    sys.path.insert(0,os.path.join(d,"..",".."))
    os.environ['DJANGO_SETTINGS_MODULE']="noc.settings"
    from noc.peer.models import PeeringPoint
    PeeringPoint.write_rconfig()
    