# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## DLink.DxS.get_arp test
## Auto-generated by manage.py debug-script at 2011-03-29 12:15:49
##----------------------------------------------------------------------
## Copyright (C) 2007-2011 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------
from noc.lib.test import ScriptTestCase
class DLink_DxS_get_arp_Test(ScriptTestCase):
    script="DLink.DxS.get_arp"
    vendor="DLink"
    platform='DGS-3120-24TC'
    version='1.01.B033'
    input={}
    result=[{'interface': 'System', 'ip': '172.16.13.0', 'mac': 'FF:FF:FF:FF:FF:FF'},
 {'interface': 'System', 'ip': '172.16.13.1', 'mac': '00:0C:76:28:8F:F6'},
 {'interface': 'System', 'ip': '172.16.13.4', 'mac': '5C:D9:98:3F:A0:E9'},
 {'interface': 'System', 'ip': '172.16.13.255', 'mac': 'FF:FF:FF:FF:FF:FF'}]
    motd='**********\n\n'
    cli={
## 'disable clipaging'
'disable clipaging': """disable clipaging
Command: disable clipaging

Success.                                                          
""", 
## 'show arpentry'
'show arpentry': """show arpentry
Command: show arpentry


 ARP Aging Time : 20

Interface      IP Address       MAC Address        Type
-------------  ---------------  -----------------  ---------------
System         172.16.13.0      FF-FF-FF-FF-FF-FF  Local/Broadcast
System         172.16.13.1      00-0C-76-28-8F-F6  Dynamic
System         172.16.13.4      5C-D9-98-3F-A0-E9  Local
System         172.16.13.255    FF-FF-FF-FF-FF-FF  Local/Broadcast

Total Entries: 4

""", 
}
    snmp_get={}
    snmp_getnext={}
