# -*- coding: utf-8 -*-
##----------------------------------------------------------------------
## DLink.DxS.get_resolver_config test
## Auto-generated by ./noc debug-script at 07.03.2012 10:14:24
##----------------------------------------------------------------------
## Copyright (C) 2007-2012 The NOC Project
## See LICENSE for details
##----------------------------------------------------------------------

## NOC modules
from noc.lib.test import ScriptTestCase


class DLink_DxS_get_resolver_config_Test(ScriptTestCase):
    script = "DLink.DxS.get_resolver_config"
    vendor = "DLink"
    platform = "DGS-3627G"
    version = "2.84.B10"
    input = {}
    result = {'nameservers': ['10.10.10.1', '10.10.10.2']}
    motd = ''
    cli = {
## 'show switch'
'show switch': """show switch
Command: show switch

Device Type       : DGS-3627G Gigabit Ethernet Switch
MAC Address       : 00-1C-F0-21-59-00
IP Address        : 10.111.0.128 (Manual)
VLAN Name         : default
Subnet Mask       : 255.255.255.0
Default Gateway\t  : 0.0.0.0
Boot PROM Version : Build 1.10-B09
Firmware Version  : Build 2.84.B10
Hardware Version  : 1A1G
System Name       : 
System Location   : Stoika 2
System Uptime     : 157 days, 18 hours, 56 minutes, 48 seconds
System Contact    : 
Spanning Tree     : Disabled
GVRP              : Disabled
IGMP Snooping     : Enabled
MLD Snooping      : Disabled
RIP               : Disabled
DVMRP             : Disabled
PIM               : Enabled
OSPF              : Disabled
OSPFv3            : Disabled
BGP               : Enabled
RIPng             : Disabled
TELNET            : Disabled
WEB               : Disabled
SNMP              : Enabled
RMON              : Disabled
SSL status        : Disabled
SSH status        : Enabled
802.1x            : Disabled
Jumbo Frame       : Off
Clipaging         : Disabled
MAC Notification  : Disabled
Port Mirror       : Disabled
SNTP              : Enabled
DHCP Relay        : Enabled
DNSR Status       : Disabled 
VRRP              : Disabled
HOL Prevention State : Enabled
Syslog Global State  : Enabled
Single IP Management : Disabled
Password Encryption Status : Enabled
DNS Resolver        : Disabled
""", 
## 'disable clipaging'
'disable clipaging': """disable clipaging
Command: disable clipaging

Success.                                                          
""", 
## 'show name_server'
'show name_server': """show name_server
Command: show name_server

 Name Server Timeout: 3 seconds

 Static Name Server Table:
 Server IP Address   Priority
 ------------------- --------
 10.10.10.1          Primary  
 10.10.10.2          Secondary

 Dynamic Name Server Table:
 Server IP Address   Priority
 ------------------- ---------
""", 
}
    snmp_get = {}
    snmp_getnext = {}
    http_get = {}
