#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          noc-activator
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the NOC Activator
### END INIT INFO

PREFIX=/opt/noc/
NAME=noc-activator
DAEMON=./scripts/$NAME.py
USER=root

test -x $PREFIX$DAEMON || exit 0
set -e

. /lib/lsb/init-functions

cd $PREFIX
case "$1" in
    start)
        echo -n "Starting $NAME: "
        su -l $USER -c "cd $PREFIX && $DAEMON start"
        echo "$NAME."
        ;;
    
    stop)
        echo -n "Stopping $NAME: "
        su -l $USER -c "cd $PREFIX && $DAEMON stop"
        echo "$NAME."
        ;;
    
    reload|restart|force-reload)
        $0 stop
        $0 start
        ;;

    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
